package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ban generated by hbm2java
 */
@Entity
@Table(name = "ban", catalog = "qlcb")
public class Ban implements java.io.Serializable {

	private Integer maBan;
	private DonVi donVi;
	private LoaiHinhBan loaiHinhBan;
	private String tenBan;
	private Date ngayThanhLap;
	private Date ngayManNhiem;
	private String moTa;
	private Byte trangThai;
	private Set<DanhGiaCanBo> danhGiaCanBos = new HashSet<DanhGiaCanBo>(0);
	private Set<ToCongTac> toCongTacs = new HashSet<ToCongTac>(0);
	private Set<DonVi> donVis = new HashSet<DonVi>(0);
	private Set<HopDongCongTac> hopDongCongTacs = new HashSet<HopDongCongTac>(0);
	private Set<ThongTinThamGiaBan> thongTinThamGiaBans = new HashSet<ThongTinThamGiaBan>(0);

	public Ban() {
	}

	public Ban(DonVi donVi, LoaiHinhBan loaiHinhBan, String tenBan, Date ngayThanhLap, Date ngayManNhiem, String moTa,
			Byte trangThai, Set<DanhGiaCanBo> danhGiaCanBos, Set<ToCongTac> toCongTacs, Set<DonVi> donVis,
			Set<HopDongCongTac> hopDongCongTacs, Set<ThongTinThamGiaBan> thongTinThamGiaBans) {
		this.donVi = donVi;
		this.loaiHinhBan = loaiHinhBan;
		this.tenBan = tenBan;
		this.ngayThanhLap = ngayThanhLap;
		this.ngayManNhiem = ngayManNhiem;
		this.moTa = moTa;
		this.trangThai = trangThai;
		this.danhGiaCanBos = danhGiaCanBos;
		this.toCongTacs = toCongTacs;
		this.donVis = donVis;
		this.hopDongCongTacs = hopDongCongTacs;
		this.thongTinThamGiaBans = thongTinThamGiaBans;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Ma_Ban", unique = true, nullable = false)
	public Integer getMaBan() {
		return this.maBan;
	}

	public void setMaBan(Integer maBan) {
		this.maBan = maBan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ma_Don_Vi")
	public DonVi getDonVi() {
		return this.donVi;
	}

	public void setDonVi(DonVi donVi) {
		this.donVi = donVi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ma_Loai_Ban")
	public LoaiHinhBan getLoaiHinhBan() {
		return this.loaiHinhBan;
	}

	public void setLoaiHinhBan(LoaiHinhBan loaiHinhBan) {
		this.loaiHinhBan = loaiHinhBan;
	}

	@Column(name = "Ten_Ban", length = 254)
	public String getTenBan() {
		return this.tenBan;
	}

	public void setTenBan(String tenBan) {
		this.tenBan = tenBan;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Ngay_Thanh_Lap", length = 10)
	public Date getNgayThanhLap() {
		return this.ngayThanhLap;
	}

	public void setNgayThanhLap(Date ngayThanhLap) {
		this.ngayThanhLap = ngayThanhLap;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Ngay_Man_Nhiem", length = 10)
	public Date getNgayManNhiem() {
		return this.ngayManNhiem;
	}

	public void setNgayManNhiem(Date ngayManNhiem) {
		this.ngayManNhiem = ngayManNhiem;
	}

	@Column(name = "Mo_Ta", length = 254)
	public String getMoTa() {
		return this.moTa;
	}

	public void setMoTa(String moTa) {
		this.moTa = moTa;
	}

	@Column(name = "Trang_Thai")
	public Byte getTrangThai() {
		return this.trangThai;
	}

	public void setTrangThai(Byte trangThai) {
		this.trangThai = trangThai;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ban")
	public Set<DanhGiaCanBo> getDanhGiaCanBos() {
		return this.danhGiaCanBos;
	}

	public void setDanhGiaCanBos(Set<DanhGiaCanBo> danhGiaCanBos) {
		this.danhGiaCanBos = danhGiaCanBos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ban")
	public Set<ToCongTac> getToCongTacs() {
		return this.toCongTacs;
	}

	public void setToCongTacs(Set<ToCongTac> toCongTacs) {
		this.toCongTacs = toCongTacs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ban")
	public Set<DonVi> getDonVis() {
		return this.donVis;
	}

	public void setDonVis(Set<DonVi> donVis) {
		this.donVis = donVis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ban")
	public Set<HopDongCongTac> getHopDongCongTacs() {
		return this.hopDongCongTacs;
	}

	public void setHopDongCongTacs(Set<HopDongCongTac> hopDongCongTacs) {
		this.hopDongCongTacs = hopDongCongTacs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ban")
	public Set<ThongTinThamGiaBan> getThongTinThamGiaBans() {
		return this.thongTinThamGiaBans;
	}

	public void setThongTinThamGiaBans(Set<ThongTinThamGiaBan> thongTinThamGiaBans) {
		this.thongTinThamGiaBans = thongTinThamGiaBans;
	}

}
