package com.springmvc.qlcb.model;
// Generated Apr 19, 2016 9:35:55 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ban generated by hbm2java
 */
@Entity
@Table(name = "ban", catalog = "qlcb_new")
public class Ban implements java.io.Serializable {

	private int id;
	private int maDonVi;
	private String tenBan;
	private Date ngayThanhLap;
	private Integer maTruongBan;
	private Set<CanboBan> canboBans = new HashSet<CanboBan>(0);

	public Ban() {
	}

	public Ban(int id, int maDonVi, String tenBan, Date ngayThanhLap) {
		this.id = id;
		this.maDonVi = maDonVi;
		this.tenBan = tenBan;
		this.ngayThanhLap = ngayThanhLap;
	}

	public Ban(int id, int maDonVi, String tenBan, Date ngayThanhLap, Integer maTruongBan, Set<CanboBan> canboBans) {
		this.id = id;
		this.maDonVi = maDonVi;
		this.tenBan = tenBan;
		this.ngayThanhLap = ngayThanhLap;
		this.maTruongBan = maTruongBan;
		this.canboBans = canboBans;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "MaDonVi", nullable = false)
	public int getMaDonVi() {
		return this.maDonVi;
	}

	public void setMaDonVi(int maDonVi) {
		this.maDonVi = maDonVi;
	}

	@Column(name = "TenBan", nullable = false, length = 45)
	public String getTenBan() {
		return this.tenBan;
	}

	public void setTenBan(String tenBan) {
		this.tenBan = tenBan;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NgayThanhLap", nullable = false, length = 10)
	public Date getNgayThanhLap() {
		return this.ngayThanhLap;
	}

	public void setNgayThanhLap(Date ngayThanhLap) {
		this.ngayThanhLap = ngayThanhLap;
	}

	@Column(name = "MaTruongBan")
	public Integer getMaTruongBan() {
		return this.maTruongBan;
	}

	public void setMaTruongBan(Integer maTruongBan) {
		this.maTruongBan = maTruongBan;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ban")
	public Set<CanboBan> getCanboBans() {
		return this.canboBans;
	}

	public void setCanboBans(Set<CanboBan> canboBans) {
		this.canboBans = canboBans;
	}

}
