package com.springmvc.qlcb.model;
// Generated Apr 25, 2016 2:33:53 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CanboGiadinhBanthan generated by hbm2java
 */
@Entity
@Table(name = "canbo_giadinh_banthan", catalog = "qlcb")
public class CanboGiadinhBanthan implements java.io.Serializable {

	private int id;
	private Canbo canbo;
	private Integer maThanhVienGiaDinh;
	private String quanHe;
	private String hoTen;
	private String ngaySinh;
	private String ghiChu;

	public CanboGiadinhBanthan() {
	}

	public CanboGiadinhBanthan(int id) {
		this.id = id;
	}

	public CanboGiadinhBanthan(int id, Canbo canbo, Integer maThanhVienGiaDinh, String quanHe, String hoTen,
			String ngaySinh, String ghiChu) {
		this.id = id;
		this.canbo = canbo;
		this.maThanhVienGiaDinh = maThanhVienGiaDinh;
		this.quanHe = quanHe;
		this.hoTen = hoTen;
		this.ngaySinh = ngaySinh;
		this.ghiChu = ghiChu;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaCanBo")
	public Canbo getCanbo() {
		return this.canbo;
	}

	public void setCanbo(Canbo canbo) {
		this.canbo = canbo;
	}

	@Column(name = "MaThanhVienGiaDinh")
	public Integer getMaThanhVienGiaDinh() {
		return this.maThanhVienGiaDinh;
	}

	public void setMaThanhVienGiaDinh(Integer maThanhVienGiaDinh) {
		this.maThanhVienGiaDinh = maThanhVienGiaDinh;
	}

	@Column(name = "QuanHe", length = 505)
	public String getQuanHe() {
		return this.quanHe;
	}

	public void setQuanHe(String quanHe) {
		this.quanHe = quanHe;
	}

	@Column(name = "HoTen", length = 45)
	public String getHoTen() {
		return this.hoTen;
	}

	public void setHoTen(String hoTen) {
		this.hoTen = hoTen;
	}

	@Column(name = "NgaySinh", length = 45)
	public String getNgaySinh() {
		return this.ngaySinh;
	}

	public void setNgaySinh(String ngaySinh) {
		this.ngaySinh = ngaySinh;
	}

	@Column(name = "GhiChu", length = 65535)
	public String getGhiChu() {
		return this.ghiChu;
	}

	public void setGhiChu(String ghiChu) {
		this.ghiChu = ghiChu;
	}

}
