package com.springmvc.qlcb.model;
// Generated Apr 21, 2016 1:56:09 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CanboDonviId generated by hbm2java
 */
@Embeddable
public class CanboDonviId implements java.io.Serializable {

	private int maCanBo;
	private int maDonVi;

	public CanboDonviId() {
	}

	public CanboDonviId(int maCanBo, int maDonVi) {
		this.maCanBo = maCanBo;
		this.maDonVi = maDonVi;
	}

	@Column(name = "MaCanBo", nullable = false)
	public int getMaCanBo() {
		return this.maCanBo;
	}

	public void setMaCanBo(int maCanBo) {
		this.maCanBo = maCanBo;
	}

	@Column(name = "MaDonVi", nullable = false)
	public int getMaDonVi() {
		return this.maDonVi;
	}

	public void setMaDonVi(int maDonVi) {
		this.maDonVi = maDonVi;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CanboDonviId))
			return false;
		CanboDonviId castOther = (CanboDonviId) other;

		return (this.getMaCanBo() == castOther.getMaCanBo()) && (this.getMaDonVi() == castOther.getMaDonVi());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMaCanBo();
		result = 37 * result + this.getMaDonVi();
		return result;
	}

}
