package com.springmvc.qlcb.model;
// Generated Apr 19, 2016 9:35:55 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CanboDonviId generated by hbm2java
 */
@Embeddable
public class CanboDonviId implements java.io.Serializable {

	private int idcanBo;
	private int iddonVi;

	public CanboDonviId() {
	}

	public CanboDonviId(int idcanBo, int iddonVi) {
		this.idcanBo = idcanBo;
		this.iddonVi = iddonVi;
	}

	@Column(name = "IDCanBo", nullable = false)
	public int getIdcanBo() {
		return this.idcanBo;
	}

	public void setIdcanBo(int idcanBo) {
		this.idcanBo = idcanBo;
	}

	@Column(name = "IDDonVi", nullable = false)
	public int getIddonVi() {
		return this.iddonVi;
	}

	public void setIddonVi(int iddonVi) {
		this.iddonVi = iddonVi;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CanboDonviId))
			return false;
		CanboDonviId castOther = (CanboDonviId) other;

		return (this.getIdcanBo() == castOther.getIdcanBo()) && (this.getIddonVi() == castOther.getIddonVi());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdcanBo();
		result = 37 * result + this.getIddonVi();
		return result;
	}

}
