package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CanBo generated by hbm2java
 */
@Entity
@Table(name = "can_bo", catalog = "qlcb")
public class CanBo implements java.io.Serializable {

	private Integer maCanBo;
	private ChucVu chucVu;
	private DonVi donVi;
	private String maQuanLy;
	private String hoTenCb;
	private Date ngayGiaNhap;
	private Date ngayTuyenDung;
	private Date ngayBienChe;
	private Date ngayRoiKhoi;
	private byte trangThai;
	private boolean dangHoatDong;
	private boolean thamGiaClbtt;
	private Set<QuaTrinhLuong> quaTrinhLuongs = new HashSet<QuaTrinhLuong>(0);
	private Set<ThanhVienGiaDinh> thanhVienGiaDinhs = new HashSet<ThanhVienGiaDinh>(0);
	private Set<DaoTaoBoiDuong> daoTaoBoiDuongs = new HashSet<DaoTaoBoiDuong>(0);
	private Set<DanhGiaCanBo> danhGiaCanBosForMaCbTuDanhGia = new HashSet<DanhGiaCanBo>(0);
	private LyLich lyLich;
	private Set<KyLuat> kyLuats = new HashSet<KyLuat>(0);
	private Set<KhenThuong> khenThuongs = new HashSet<KhenThuong>(0);
	private Set<ThongTinThamGiaBan> thongTinThamGiaBans = new HashSet<ThongTinThamGiaBan>(0);
	private Set<YeuCauThayDoiTtCb> yeuCauThayDoiTtCbsForMaCbAnhHuong = new HashSet<YeuCauThayDoiTtCb>(0);
	private Set<YeuCauThayDoiTtCb> yeuCauThayDoiTtCbsForMaCbYeuCau = new HashSet<YeuCauThayDoiTtCb>(0);
	private Set<DanhGiaCanBo> danhGiaCanBosForMaCbDanhGia = new HashSet<DanhGiaCanBo>(0);
	private Set<KienNghi> kienNghis = new HashSet<KienNghi>(0);
	private Set<QuaTrinhCongTac> quaTrinhCongTacs = new HashSet<QuaTrinhCongTac>(0);
	private Set<DacDiemLichSu> dacDiemLichSus = new HashSet<DacDiemLichSu>(0);
	private Set<DonVi> donVis = new HashSet<DonVi>(0);

	public CanBo() {
	}

	public CanBo(byte trangThai, boolean dangHoatDong, boolean thamGiaClbtt) {
		this.trangThai = trangThai;
		this.dangHoatDong = dangHoatDong;
		this.thamGiaClbtt = thamGiaClbtt;
	}

	public CanBo(ChucVu chucVu, DonVi donVi, String maQuanLy, String hoTenCb, Date ngayGiaNhap, Date ngayTuyenDung,
			Date ngayBienChe, Date ngayRoiKhoi, byte trangThai, boolean dangHoatDong, boolean thamGiaClbtt,
			Set<QuaTrinhLuong> quaTrinhLuongs, Set<ThanhVienGiaDinh> thanhVienGiaDinhs,
			Set<DaoTaoBoiDuong> daoTaoBoiDuongs, Set<DanhGiaCanBo> danhGiaCanBosForMaCbTuDanhGia, LyLich lyLich,
			Set<KyLuat> kyLuats, Set<KhenThuong> khenThuongs, Set<ThongTinThamGiaBan> thongTinThamGiaBans,
			Set<YeuCauThayDoiTtCb> yeuCauThayDoiTtCbsForMaCbAnhHuong,
			Set<YeuCauThayDoiTtCb> yeuCauThayDoiTtCbsForMaCbYeuCau, Set<DanhGiaCanBo> danhGiaCanBosForMaCbDanhGia,
			Set<KienNghi> kienNghis, Set<QuaTrinhCongTac> quaTrinhCongTacs, Set<DacDiemLichSu> dacDiemLichSus,
			Set<DonVi> donVis) {
		this.chucVu = chucVu;
		this.donVi = donVi;
		this.maQuanLy = maQuanLy;
		this.hoTenCb = hoTenCb;
		this.ngayGiaNhap = ngayGiaNhap;
		this.ngayTuyenDung = ngayTuyenDung;
		this.ngayBienChe = ngayBienChe;
		this.ngayRoiKhoi = ngayRoiKhoi;
		this.trangThai = trangThai;
		this.dangHoatDong = dangHoatDong;
		this.thamGiaClbtt = thamGiaClbtt;
		this.quaTrinhLuongs = quaTrinhLuongs;
		this.thanhVienGiaDinhs = thanhVienGiaDinhs;
		this.daoTaoBoiDuongs = daoTaoBoiDuongs;
		this.danhGiaCanBosForMaCbTuDanhGia = danhGiaCanBosForMaCbTuDanhGia;
		this.lyLich = lyLich;
		this.kyLuats = kyLuats;
		this.khenThuongs = khenThuongs;
		this.thongTinThamGiaBans = thongTinThamGiaBans;
		this.yeuCauThayDoiTtCbsForMaCbAnhHuong = yeuCauThayDoiTtCbsForMaCbAnhHuong;
		this.yeuCauThayDoiTtCbsForMaCbYeuCau = yeuCauThayDoiTtCbsForMaCbYeuCau;
		this.danhGiaCanBosForMaCbDanhGia = danhGiaCanBosForMaCbDanhGia;
		this.kienNghis = kienNghis;
		this.quaTrinhCongTacs = quaTrinhCongTacs;
		this.dacDiemLichSus = dacDiemLichSus;
		this.donVis = donVis;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Ma_Can_Bo", unique = true, nullable = false)
	public Integer getMaCanBo() {
		return this.maCanBo;
	}

	public void setMaCanBo(Integer maCanBo) {
		this.maCanBo = maCanBo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ma_CV_Chinh")
	public ChucVu getChucVu() {
		return this.chucVu;
	}

	public void setChucVu(ChucVu chucVu) {
		this.chucVu = chucVu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ma_DVCT_Chinh")
	public DonVi getDonVi() {
		return this.donVi;
	}

	public void setDonVi(DonVi donVi) {
		this.donVi = donVi;
	}

	@Column(name = "Ma_Quan_Ly", length = 254)
	public String getMaQuanLy() {
		return this.maQuanLy;
	}

	public void setMaQuanLy(String maQuanLy) {
		this.maQuanLy = maQuanLy;
	}

	@Column(name = "Ho_Ten_CB", length = 254)
	public String getHoTenCb() {
		return this.hoTenCb;
	}

	public void setHoTenCb(String hoTenCb) {
		this.hoTenCb = hoTenCb;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Ngay_Gia_Nhap", length = 10)
	public Date getNgayGiaNhap() {
		return this.ngayGiaNhap;
	}

	public void setNgayGiaNhap(Date ngayGiaNhap) {
		this.ngayGiaNhap = ngayGiaNhap;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Ngay_Tuyen_Dung", length = 10)
	public Date getNgayTuyenDung() {
		return this.ngayTuyenDung;
	}

	public void setNgayTuyenDung(Date ngayTuyenDung) {
		this.ngayTuyenDung = ngayTuyenDung;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Ngay_Bien_Che", length = 10)
	public Date getNgayBienChe() {
		return this.ngayBienChe;
	}

	public void setNgayBienChe(Date ngayBienChe) {
		this.ngayBienChe = ngayBienChe;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Ngay_Roi_Khoi", length = 10)
	public Date getNgayRoiKhoi() {
		return this.ngayRoiKhoi;
	}

	public void setNgayRoiKhoi(Date ngayRoiKhoi) {
		this.ngayRoiKhoi = ngayRoiKhoi;
	}

	@Column(name = "Trang_Thai", nullable = false)
	public byte getTrangThai() {
		return this.trangThai;
	}

	public void setTrangThai(byte trangThai) {
		this.trangThai = trangThai;
	}

	@Column(name = "DangHoatDong", nullable = false)
	public boolean isDangHoatDong() {
		return this.dangHoatDong;
	}

	public void setDangHoatDong(boolean dangHoatDong) {
		this.dangHoatDong = dangHoatDong;
	}

	@Column(name = "Tham_Gia_CLBTT", nullable = false)
	public boolean isThamGiaClbtt() {
		return this.thamGiaClbtt;
	}

	public void setThamGiaClbtt(boolean thamGiaClbtt) {
		this.thamGiaClbtt = thamGiaClbtt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "canBo")
	public Set<QuaTrinhLuong> getQuaTrinhLuongs() {
		return this.quaTrinhLuongs;
	}

	public void setQuaTrinhLuongs(Set<QuaTrinhLuong> quaTrinhLuongs) {
		this.quaTrinhLuongs = quaTrinhLuongs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "canBo")
	public Set<ThanhVienGiaDinh> getThanhVienGiaDinhs() {
		return this.thanhVienGiaDinhs;
	}

	public void setThanhVienGiaDinhs(Set<ThanhVienGiaDinh> thanhVienGiaDinhs) {
		this.thanhVienGiaDinhs = thanhVienGiaDinhs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "canBo")
	public Set<DaoTaoBoiDuong> getDaoTaoBoiDuongs() {
		return this.daoTaoBoiDuongs;
	}

	public void setDaoTaoBoiDuongs(Set<DaoTaoBoiDuong> daoTaoBoiDuongs) {
		this.daoTaoBoiDuongs = daoTaoBoiDuongs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "canBoByMaCbTuDanhGia")
	public Set<DanhGiaCanBo> getDanhGiaCanBosForMaCbTuDanhGia() {
		return this.danhGiaCanBosForMaCbTuDanhGia;
	}

	public void setDanhGiaCanBosForMaCbTuDanhGia(Set<DanhGiaCanBo> danhGiaCanBosForMaCbTuDanhGia) {
		this.danhGiaCanBosForMaCbTuDanhGia = danhGiaCanBosForMaCbTuDanhGia;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "canBo")
	public LyLich getLyLich() {
		return this.lyLich;
	}

	public void setLyLich(LyLich lyLich) {
		this.lyLich = lyLich;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "canBo")
	public Set<KyLuat> getKyLuats() {
		return this.kyLuats;
	}

	public void setKyLuats(Set<KyLuat> kyLuats) {
		this.kyLuats = kyLuats;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "canBo")
	public Set<KhenThuong> getKhenThuongs() {
		return this.khenThuongs;
	}

	public void setKhenThuongs(Set<KhenThuong> khenThuongs) {
		this.khenThuongs = khenThuongs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "canBo")
	public Set<ThongTinThamGiaBan> getThongTinThamGiaBans() {
		return this.thongTinThamGiaBans;
	}

	public void setThongTinThamGiaBans(Set<ThongTinThamGiaBan> thongTinThamGiaBans) {
		this.thongTinThamGiaBans = thongTinThamGiaBans;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "canBoByMaCbAnhHuong")
	public Set<YeuCauThayDoiTtCb> getYeuCauThayDoiTtCbsForMaCbAnhHuong() {
		return this.yeuCauThayDoiTtCbsForMaCbAnhHuong;
	}

	public void setYeuCauThayDoiTtCbsForMaCbAnhHuong(Set<YeuCauThayDoiTtCb> yeuCauThayDoiTtCbsForMaCbAnhHuong) {
		this.yeuCauThayDoiTtCbsForMaCbAnhHuong = yeuCauThayDoiTtCbsForMaCbAnhHuong;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "canBoByMaCbYeuCau")
	public Set<YeuCauThayDoiTtCb> getYeuCauThayDoiTtCbsForMaCbYeuCau() {
		return this.yeuCauThayDoiTtCbsForMaCbYeuCau;
	}

	public void setYeuCauThayDoiTtCbsForMaCbYeuCau(Set<YeuCauThayDoiTtCb> yeuCauThayDoiTtCbsForMaCbYeuCau) {
		this.yeuCauThayDoiTtCbsForMaCbYeuCau = yeuCauThayDoiTtCbsForMaCbYeuCau;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "canBoByMaCbDanhGia")
	public Set<DanhGiaCanBo> getDanhGiaCanBosForMaCbDanhGia() {
		return this.danhGiaCanBosForMaCbDanhGia;
	}

	public void setDanhGiaCanBosForMaCbDanhGia(Set<DanhGiaCanBo> danhGiaCanBosForMaCbDanhGia) {
		this.danhGiaCanBosForMaCbDanhGia = danhGiaCanBosForMaCbDanhGia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "canBo")
	public Set<KienNghi> getKienNghis() {
		return this.kienNghis;
	}

	public void setKienNghis(Set<KienNghi> kienNghis) {
		this.kienNghis = kienNghis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "canBo")
	public Set<QuaTrinhCongTac> getQuaTrinhCongTacs() {
		return this.quaTrinhCongTacs;
	}

	public void setQuaTrinhCongTacs(Set<QuaTrinhCongTac> quaTrinhCongTacs) {
		this.quaTrinhCongTacs = quaTrinhCongTacs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "canBo")
	public Set<DacDiemLichSu> getDacDiemLichSus() {
		return this.dacDiemLichSus;
	}

	public void setDacDiemLichSus(Set<DacDiemLichSu> dacDiemLichSus) {
		this.dacDiemLichSus = dacDiemLichSus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "canBo")
	public Set<DonVi> getDonVis() {
		return this.donVis;
	}

	public void setDonVis(Set<DonVi> donVis) {
		this.donVis = donVis;
	}

}
