package com.springmvc.qlcb.model;
// Generated Apr 25, 2016 1:43:12 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CanboBan generated by hbm2java
 */
@Entity
@Table(name = "canbo_ban", catalog = "qlcb")
public class CanboBan implements java.io.Serializable {

	private CanboBanId id;
	private Ban ban;
	private Canbo canbo;
	private Chucvuban chucvuban;

	public CanboBan() {
	}

	public CanboBan(CanboBanId id, Ban ban, Canbo canbo, Chucvuban chucvuban) {
		this.id = id;
		this.ban = ban;
		this.canbo = canbo;
		this.chucvuban = chucvuban;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idban", column = @Column(name = "IDBan", nullable = false)),
			@AttributeOverride(name = "idcanBo", column = @Column(name = "IDCanBo", nullable = false)) })
	public CanboBanId getId() {
		return this.id;
	}

	public void setId(CanboBanId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDBan", nullable = false, insertable = false, updatable = false)
	public Ban getBan() {
		return this.ban;
	}

	public void setBan(Ban ban) {
		this.ban = ban;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDCanBo", nullable = false, insertable = false, updatable = false)
	public Canbo getCanbo() {
		return this.canbo;
	}

	public void setCanbo(Canbo canbo) {
		this.canbo = canbo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ChucVu", nullable = false)
	public Chucvuban getChucvuban() {
		return this.chucvuban;
	}

	public void setChucvuban(Chucvuban chucvuban) {
		this.chucvuban = chucvuban;
	}

}
