package com.springmvc.qlcb.model;
// Generated Apr 25, 2016 1:43:12 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CanboGiadinhBanthan generated by hbm2java
 */
@Entity
@Table(name = "canbo_giadinh_banthan", catalog = "qlcb")
public class CanboGiadinhBanthan implements java.io.Serializable {

	private int id;
	private Canbo canbo;
	private Quanhe quanhe;
	private Thanhviengiadinh thanhviengiadinh;

	public CanboGiadinhBanthan() {
	}

	public CanboGiadinhBanthan(int id) {
		this.id = id;
	}

	public CanboGiadinhBanthan(int id, Canbo canbo, Quanhe quanhe, Thanhviengiadinh thanhviengiadinh) {
		this.id = id;
		this.canbo = canbo;
		this.quanhe = quanhe;
		this.thanhviengiadinh = thanhviengiadinh;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaCanBo")
	public Canbo getCanbo() {
		return this.canbo;
	}

	public void setCanbo(Canbo canbo) {
		this.canbo = canbo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QuanHe")
	public Quanhe getQuanhe() {
		return this.quanhe;
	}

	public void setQuanhe(Quanhe quanhe) {
		this.quanhe = quanhe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaThanhVienGiaDinh")
	public Thanhviengiadinh getThanhviengiadinh() {
		return this.thanhviengiadinh;
	}

	public void setThanhviengiadinh(Thanhviengiadinh thanhviengiadinh) {
		this.thanhviengiadinh = thanhviengiadinh;
	}

}
