package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CapChucVu generated by hbm2java
 */
@Entity
@Table(name = "cap_chuc_vu", catalog = "qlcb")
public class CapChucVu implements java.io.Serializable {

	private Byte maCap;
	private String tenCapCv;
	private Set<ChucVu> chucVus = new HashSet<ChucVu>(0);

	public CapChucVu() {
	}

	public CapChucVu(String tenCapCv, Set<ChucVu> chucVus) {
		this.tenCapCv = tenCapCv;
		this.chucVus = chucVus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Ma_Cap", unique = true, nullable = false)
	public Byte getMaCap() {
		return this.maCap;
	}

	public void setMaCap(Byte maCap) {
		this.maCap = maCap;
	}

	@Column(name = "Ten_Cap_CV", length = 254)
	public String getTenCapCv() {
		return this.tenCapCv;
	}

	public void setTenCapCv(String tenCapCv) {
		this.tenCapCv = tenCapCv;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "capChucVu")
	public Set<ChucVu> getChucVus() {
		return this.chucVus;
	}

	public void setChucVus(Set<ChucVu> chucVus) {
		this.chucVus = chucVus;
	}

}
