package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChieuHuongPhatTrien generated by hbm2java
 */
@Entity
@Table(name = "chieu_huong_phat_trien", catalog = "qlcb")
public class ChieuHuongPhatTrien implements java.io.Serializable {

	private Byte maChpt;
	private String tenChpt;
	private Set<DanhGiaCanBo> danhGiaCanBos = new HashSet<DanhGiaCanBo>(0);

	public ChieuHuongPhatTrien() {
	}

	public ChieuHuongPhatTrien(String tenChpt, Set<DanhGiaCanBo> danhGiaCanBos) {
		this.tenChpt = tenChpt;
		this.danhGiaCanBos = danhGiaCanBos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Ma_CHPT", unique = true, nullable = false)
	public Byte getMaChpt() {
		return this.maChpt;
	}

	public void setMaChpt(Byte maChpt) {
		this.maChpt = maChpt;
	}

	@Column(name = "Ten_CHPT", length = 254)
	public String getTenChpt() {
		return this.tenChpt;
	}

	public void setTenChpt(String tenChpt) {
		this.tenChpt = tenChpt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chieuHuongPhatTrien")
	public Set<DanhGiaCanBo> getDanhGiaCanBos() {
		return this.danhGiaCanBos;
	}

	public void setDanhGiaCanBos(Set<DanhGiaCanBo> danhGiaCanBos) {
		this.danhGiaCanBos = danhGiaCanBos;
	}

}
