package com.springmvc.qlcb.model;
// Generated Apr 25, 2016 1:43:12 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Chucvudonvi generated by hbm2java
 */
@Entity
@Table(name = "chucvudonvi", catalog = "qlcb")
public class Chucvudonvi implements java.io.Serializable {

	private int maChucVu;
	private String tenChucVu;
	private Set<CanboDonvi> canboDonvis = new HashSet<CanboDonvi>(0);

	public Chucvudonvi() {
	}

	public Chucvudonvi(int maChucVu, String tenChucVu) {
		this.maChucVu = maChucVu;
		this.tenChucVu = tenChucVu;
	}

	public Chucvudonvi(int maChucVu, String tenChucVu, Set<CanboDonvi> canboDonvis) {
		this.maChucVu = maChucVu;
		this.tenChucVu = tenChucVu;
		this.canboDonvis = canboDonvis;
	}

	@Id

	@Column(name = "MaChucVu", unique = true, nullable = false)
	public int getMaChucVu() {
		return this.maChucVu;
	}

	public void setMaChucVu(int maChucVu) {
		this.maChucVu = maChucVu;
	}

	@Column(name = "TenChucVu", nullable = false, length = 200)
	public String getTenChucVu() {
		return this.tenChucVu;
	}

	public void setTenChucVu(String tenChucVu) {
		this.tenChucVu = tenChucVu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chucvudonvi")
	public Set<CanboDonvi> getCanboDonvis() {
		return this.canboDonvis;
	}

	public void setCanboDonvis(Set<CanboDonvi> canboDonvis) {
		this.canboDonvis = canboDonvis;
	}

}
