package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChucVu generated by hbm2java
 */
@Entity
@Table(name = "chuc_vu", catalog = "qlcb")
public class ChucVu implements java.io.Serializable {

	private Short maChucVu;
	private CapChucVu capChucVu;
	private String tenChucVu;
	private Set<ThongTinThamGiaBan> thongTinThamGiaBans = new HashSet<ThongTinThamGiaBan>(0);
	private Set<CanBo> canBos = new HashSet<CanBo>(0);

	public ChucVu() {
	}

	public ChucVu(CapChucVu capChucVu, String tenChucVu, Set<ThongTinThamGiaBan> thongTinThamGiaBans,
			Set<CanBo> canBos) {
		this.capChucVu = capChucVu;
		this.tenChucVu = tenChucVu;
		this.thongTinThamGiaBans = thongTinThamGiaBans;
		this.canBos = canBos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Ma_Chuc_Vu", unique = true, nullable = false)
	public Short getMaChucVu() {
		return this.maChucVu;
	}

	public void setMaChucVu(Short maChucVu) {
		this.maChucVu = maChucVu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ma_Cap")
	public CapChucVu getCapChucVu() {
		return this.capChucVu;
	}

	public void setCapChucVu(CapChucVu capChucVu) {
		this.capChucVu = capChucVu;
	}

	@Column(name = "Ten_Chuc_Vu", length = 254)
	public String getTenChucVu() {
		return this.tenChucVu;
	}

	public void setTenChucVu(String tenChucVu) {
		this.tenChucVu = tenChucVu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chucVu")
	public Set<ThongTinThamGiaBan> getThongTinThamGiaBans() {
		return this.thongTinThamGiaBans;
	}

	public void setThongTinThamGiaBans(Set<ThongTinThamGiaBan> thongTinThamGiaBans) {
		this.thongTinThamGiaBans = thongTinThamGiaBans;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chucVu")
	public Set<CanBo> getCanBos() {
		return this.canBos;
	}

	public void setCanBos(Set<CanBo> canBos) {
		this.canBos = canBos;
	}

}
