package com.springmvc.qlcb.model;
// Generated Apr 25, 2016 1:43:12 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Chucvuban generated by hbm2java
 */
@Entity
@Table(name = "chucvuban", catalog = "qlcb")
public class Chucvuban implements java.io.Serializable {

	private int maChucVu;
	private String tenChucVu;
	private Set<CanboBan> canboBans = new HashSet<CanboBan>(0);

	public Chucvuban() {
	}

	public Chucvuban(int maChucVu, String tenChucVu) {
		this.maChucVu = maChucVu;
		this.tenChucVu = tenChucVu;
	}

	public Chucvuban(int maChucVu, String tenChucVu, Set<CanboBan> canboBans) {
		this.maChucVu = maChucVu;
		this.tenChucVu = tenChucVu;
		this.canboBans = canboBans;
	}

	@Id

	@Column(name = "MaChucVu", unique = true, nullable = false)
	public int getMaChucVu() {
		return this.maChucVu;
	}

	public void setMaChucVu(int maChucVu) {
		this.maChucVu = maChucVu;
	}

	@Column(name = "TenChucVu", nullable = false, length = 200)
	public String getTenChucVu() {
		return this.tenChucVu;
	}

	public void setTenChucVu(String tenChucVu) {
		this.tenChucVu = tenChucVu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chucvuban")
	public Set<CanboBan> getCanboBans() {
		return this.canboBans;
	}

	public void setCanboBans(Set<CanboBan> canboBans) {
		this.canboBans = canboBans;
	}

}
