package com.springmvc.qlcb.model;
// Generated Apr 19, 2016 9:35:55 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Chucvuban generated by hbm2java
 */
@Entity
@Table(name = "chucvuban", catalog = "qlcb_new")
public class Chucvuban implements java.io.Serializable {

	private int id;
	private String tenChucVu;
	private Set<CanboBan> canboBans = new HashSet<CanboBan>(0);

	public Chucvuban() {
	}

	public Chucvuban(int id, String tenChucVu) {
		this.id = id;
		this.tenChucVu = tenChucVu;
	}

	public Chucvuban(int id, String tenChucVu, Set<CanboBan> canboBans) {
		this.id = id;
		this.tenChucVu = tenChucVu;
		this.canboBans = canboBans;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "TenChucVu", nullable = false, length = 200)
	public String getTenChucVu() {
		return this.tenChucVu;
	}

	public void setTenChucVu(String tenChucVu) {
		this.tenChucVu = tenChucVu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chucvuban")
	public Set<CanboBan> getCanboBans() {
		return this.canboBans;
	}

	public void setCanboBans(Set<CanboBan> canboBans) {
		this.canboBans = canboBans;
	}

}
