package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CongTacNuocNgoaiId generated by hbm2java
 */
@Embeddable
public class CongTacNuocNgoaiId implements java.io.Serializable {

	private long maCtnn;
	private int maCb;

	public CongTacNuocNgoaiId() {
	}

	public CongTacNuocNgoaiId(long maCtnn, int maCb) {
		this.maCtnn = maCtnn;
		this.maCb = maCb;
	}

	@Column(name = "Ma_CTNN", nullable = false)
	public long getMaCtnn() {
		return this.maCtnn;
	}

	public void setMaCtnn(long maCtnn) {
		this.maCtnn = maCtnn;
	}

	@Column(name = "Ma_CB", nullable = false)
	public int getMaCb() {
		return this.maCb;
	}

	public void setMaCb(int maCb) {
		this.maCb = maCb;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CongTacNuocNgoaiId))
			return false;
		CongTacNuocNgoaiId castOther = (CongTacNuocNgoaiId) other;

		return (this.getMaCtnn() == castOther.getMaCtnn()) && (this.getMaCb() == castOther.getMaCb());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getMaCtnn();
		result = 37 * result + this.getMaCb();
		return result;
	}

}
