package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CongTacVien generated by hbm2java
 */
@Entity
@Table(name = "cong_tac_vien", catalog = "qlcb")
public class CongTacVien implements java.io.Serializable {

	private Integer maCtv;
	private String hoTenCtv;
	private Set<HopDongCongTac> hopDongCongTacs = new HashSet<HopDongCongTac>(0);

	public CongTacVien() {
	}

	public CongTacVien(String hoTenCtv, Set<HopDongCongTac> hopDongCongTacs) {
		this.hoTenCtv = hoTenCtv;
		this.hopDongCongTacs = hopDongCongTacs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Ma_CTV", unique = true, nullable = false)
	public Integer getMaCtv() {
		return this.maCtv;
	}

	public void setMaCtv(Integer maCtv) {
		this.maCtv = maCtv;
	}

	@Column(name = "Ho_Ten_CTV", length = 254)
	public String getHoTenCtv() {
		return this.hoTenCtv;
	}

	public void setHoTenCtv(String hoTenCtv) {
		this.hoTenCtv = hoTenCtv;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "congTacVien")
	public Set<HopDongCongTac> getHopDongCongTacs() {
		return this.hopDongCongTacs;
	}

	public void setHopDongCongTacs(Set<HopDongCongTac> hopDongCongTacs) {
		this.hopDongCongTacs = hopDongCongTacs;
	}

}
