package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CongTacNuocNgoai generated by hbm2java
 */
@Entity
@Table(name = "cong_tac_nuoc_ngoai", catalog = "qlcb")
public class CongTacNuocNgoai implements java.io.Serializable {

	private CongTacNuocNgoaiId id;
	private Date tuNgay;
	private Date denNgay;
	private String diaDiem;
	private String noiDung;
	private String capCuDi;
	private String kinhPhi;

	public CongTacNuocNgoai() {
	}

	public CongTacNuocNgoai(CongTacNuocNgoaiId id, Date tuNgay, Date denNgay) {
		this.id = id;
		this.tuNgay = tuNgay;
		this.denNgay = denNgay;
	}

	public CongTacNuocNgoai(CongTacNuocNgoaiId id, Date tuNgay, Date denNgay, String diaDiem, String noiDung,
			String capCuDi, String kinhPhi) {
		this.id = id;
		this.tuNgay = tuNgay;
		this.denNgay = denNgay;
		this.diaDiem = diaDiem;
		this.noiDung = noiDung;
		this.capCuDi = capCuDi;
		this.kinhPhi = kinhPhi;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "maCtnn", column = @Column(name = "Ma_CTNN", nullable = false)),
			@AttributeOverride(name = "maCb", column = @Column(name = "Ma_CB", nullable = false)) })
	public CongTacNuocNgoaiId getId() {
		return this.id;
	}

	public void setId(CongTacNuocNgoaiId id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Tu_Ngay", nullable = false, length = 10)
	public Date getTuNgay() {
		return this.tuNgay;
	}

	public void setTuNgay(Date tuNgay) {
		this.tuNgay = tuNgay;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Den_Ngay", nullable = false, length = 10)
	public Date getDenNgay() {
		return this.denNgay;
	}

	public void setDenNgay(Date denNgay) {
		this.denNgay = denNgay;
	}

	@Column(name = "Dia_Diem", length = 254)
	public String getDiaDiem() {
		return this.diaDiem;
	}

	public void setDiaDiem(String diaDiem) {
		this.diaDiem = diaDiem;
	}

	@Column(name = "Noi_Dung", length = 254)
	public String getNoiDung() {
		return this.noiDung;
	}

	public void setNoiDung(String noiDung) {
		this.noiDung = noiDung;
	}

	@Column(name = "Cap_Cu_Di", length = 254)
	public String getCapCuDi() {
		return this.capCuDi;
	}

	public void setCapCuDi(String capCuDi) {
		this.capCuDi = capCuDi;
	}

	@Column(name = "Kinh_Phi", length = 254)
	public String getKinhPhi() {
		return this.kinhPhi;
	}

	public void setKinhPhi(String kinhPhi) {
		this.kinhPhi = kinhPhi;
	}

}
