package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DacDiemLichSuId generated by hbm2java
 */
@Embeddable
public class DacDiemLichSuId implements java.io.Serializable {

	private long maDdls;
	private int maCb;

	public DacDiemLichSuId() {
	}

	public DacDiemLichSuId(long maDdls, int maCb) {
		this.maDdls = maDdls;
		this.maCb = maCb;
	}

	@Column(name = "Ma_DDLS", nullable = false)
	public long getMaDdls() {
		return this.maDdls;
	}

	public void setMaDdls(long maDdls) {
		this.maDdls = maDdls;
	}

	@Column(name = "Ma_CB", nullable = false)
	public int getMaCb() {
		return this.maCb;
	}

	public void setMaCb(int maCb) {
		this.maCb = maCb;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DacDiemLichSuId))
			return false;
		DacDiemLichSuId castOther = (DacDiemLichSuId) other;

		return (this.getMaDdls() == castOther.getMaDdls()) && (this.getMaCb() == castOther.getMaCb());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getMaDdls();
		result = 37 * result + this.getMaCb();
		return result;
	}

}
