package com.springmvc.qlcb.model;
// Generated Apr 23, 2016 3:25:20 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Dacdienlichsubanthan generated by hbm2java
 */
@Entity
@Table(name = "dacdienlichsubanthan", catalog = "qlcb")
public class Dacdienlichsubanthan implements java.io.Serializable {

	private int maDdls;
	private Canbo canbo;
	private String noidung1;
	private String noidung2;
	private String noiDung3;
	private String ghichu;

	public Dacdienlichsubanthan() {
	}

	public Dacdienlichsubanthan(int maDdls, Canbo canbo, String noidung1, String noidung2, String noiDung3) {
		this.maDdls = maDdls;
		this.canbo = canbo;
		this.noidung1 = noidung1;
		this.noidung2 = noidung2;
		this.noiDung3 = noiDung3;
	}

	public Dacdienlichsubanthan(int maDdls, Canbo canbo, String noidung1, String noidung2, String noiDung3,
			String ghichu) {
		this.maDdls = maDdls;
		this.canbo = canbo;
		this.noidung1 = noidung1;
		this.noidung2 = noidung2;
		this.noiDung3 = noiDung3;
		this.ghichu = ghichu;
	}

	@Id

	@Column(name = "MaDDLS", unique = true, nullable = false)
	public int getMaDdls() {
		return this.maDdls;
	}

	public void setMaDdls(int maDdls) {
		this.maDdls = maDdls;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaCanBo", nullable = false)
	public Canbo getCanbo() {
		return this.canbo;
	}

	public void setCanbo(Canbo canbo) {
		this.canbo = canbo;
	}

	@Column(name = "Noidung1", nullable = false, length = 65535)
	public String getNoidung1() {
		return this.noidung1;
	}

	public void setNoidung1(String noidung1) {
		this.noidung1 = noidung1;
	}

	@Column(name = "Noidung2", nullable = false, length = 65535)
	public String getNoidung2() {
		return this.noidung2;
	}

	public void setNoidung2(String noidung2) {
		this.noidung2 = noidung2;
	}

	@Column(name = "NoiDung3", nullable = false, length = 65535)
	public String getNoiDung3() {
		return this.noiDung3;
	}

	public void setNoiDung3(String noiDung3) {
		this.noiDung3 = noiDung3;
	}

	@Column(name = "Ghichu", length = 65535)
	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

}
