package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DacDiemLichSu generated by hbm2java
 */
@Entity
@Table(name = "dac_diem_lich_su", catalog = "qlcb")
public class DacDiemLichSu implements java.io.Serializable {

	private DacDiemLichSuId id;
	private CanBo canBo;
	private String suKien;
	private Date tuThoiDiem;
	private Date denThoiDiem;
	private String nguoiNhanKhaiBao;
	private String noiDung;

	public DacDiemLichSu() {
	}

	public DacDiemLichSu(DacDiemLichSuId id, CanBo canBo) {
		this.id = id;
		this.canBo = canBo;
	}

	public DacDiemLichSu(DacDiemLichSuId id, CanBo canBo, String suKien, Date tuThoiDiem, Date denThoiDiem,
			String nguoiNhanKhaiBao, String noiDung) {
		this.id = id;
		this.canBo = canBo;
		this.suKien = suKien;
		this.tuThoiDiem = tuThoiDiem;
		this.denThoiDiem = denThoiDiem;
		this.nguoiNhanKhaiBao = nguoiNhanKhaiBao;
		this.noiDung = noiDung;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "maDdls", column = @Column(name = "Ma_DDLS", nullable = false)),
			@AttributeOverride(name = "maCb", column = @Column(name = "Ma_CB", nullable = false)) })
	public DacDiemLichSuId getId() {
		return this.id;
	}

	public void setId(DacDiemLichSuId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ma_CB", nullable = false, insertable = false, updatable = false)
	public CanBo getCanBo() {
		return this.canBo;
	}

	public void setCanBo(CanBo canBo) {
		this.canBo = canBo;
	}

	@Column(name = "Su_Kien", length = 254)
	public String getSuKien() {
		return this.suKien;
	}

	public void setSuKien(String suKien) {
		this.suKien = suKien;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Tu_Thoi_Diem", length = 10)
	public Date getTuThoiDiem() {
		return this.tuThoiDiem;
	}

	public void setTuThoiDiem(Date tuThoiDiem) {
		this.tuThoiDiem = tuThoiDiem;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Den_Thoi_Diem", length = 10)
	public Date getDenThoiDiem() {
		return this.denThoiDiem;
	}

	public void setDenThoiDiem(Date denThoiDiem) {
		this.denThoiDiem = denThoiDiem;
	}

	@Column(name = "Nguoi_Nhan_Khai_Bao", length = 254)
	public String getNguoiNhanKhaiBao() {
		return this.nguoiNhanKhaiBao;
	}

	public void setNguoiNhanKhaiBao(String nguoiNhanKhaiBao) {
		this.nguoiNhanKhaiBao = nguoiNhanKhaiBao;
	}

	@Column(name = "Noi_Dung", length = 254)
	public String getNoiDung() {
		return this.noiDung;
	}

	public void setNoiDung(String noiDung) {
		this.noiDung = noiDung;
	}

}
