package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DanhGiaCanBoId generated by hbm2java
 */
@Embeddable
public class DanhGiaCanBoId implements java.io.Serializable {

	private int maCbTuDanhGia;
	private Date ngayDanhGia;

	public DanhGiaCanBoId() {
	}

	public DanhGiaCanBoId(int maCbTuDanhGia, Date ngayDanhGia) {
		this.maCbTuDanhGia = maCbTuDanhGia;
		this.ngayDanhGia = ngayDanhGia;
	}

	@Column(name = "Ma_CB_Tu_Danh_Gia", nullable = false)
	public int getMaCbTuDanhGia() {
		return this.maCbTuDanhGia;
	}

	public void setMaCbTuDanhGia(int maCbTuDanhGia) {
		this.maCbTuDanhGia = maCbTuDanhGia;
	}

	@Column(name = "Ngay_Danh_Gia", nullable = false, length = 10)
	public Date getNgayDanhGia() {
		return this.ngayDanhGia;
	}

	public void setNgayDanhGia(Date ngayDanhGia) {
		this.ngayDanhGia = ngayDanhGia;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DanhGiaCanBoId))
			return false;
		DanhGiaCanBoId castOther = (DanhGiaCanBoId) other;

		return (this.getMaCbTuDanhGia() == castOther.getMaCbTuDanhGia())
				&& ((this.getNgayDanhGia() == castOther.getNgayDanhGia())
						|| (this.getNgayDanhGia() != null && castOther.getNgayDanhGia() != null
								&& this.getNgayDanhGia().equals(castOther.getNgayDanhGia())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMaCbTuDanhGia();
		result = 37 * result + (getNgayDanhGia() == null ? 0 : this.getNgayDanhGia().hashCode());
		return result;
	}

}
