package com.springmvc.qlcb.model;
// Generated Apr 19, 2016 9:35:55 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Danhgiacanbo generated by hbm2java
 */
@Entity
@Table(name = "danhgiacanbo", catalog = "qlcb_new")
public class Danhgiacanbo implements java.io.Serializable {

	private int iddanhGiaCanBo;
	private Canbo canboByMaNguoiDanhGia;
	private Canbo canboByMaCbduocDanhGia;
	private Mucdohoanthanh mucdohoanthanh;
	private Quy quy;
	private String noiDung;
	private Date ngayDanhGia;
	private int nam;
	private boolean laQuanLyHienTai;
	private String chucVuHienTaiNguoiDanhGia;

	public Danhgiacanbo() {
	}

	public Danhgiacanbo(int iddanhGiaCanBo, Canbo canboByMaNguoiDanhGia, Canbo canboByMaCbduocDanhGia,
			Mucdohoanthanh mucdohoanthanh, Quy quy, String noiDung, Date ngayDanhGia, int nam,
			boolean laQuanLyHienTai) {
		this.iddanhGiaCanBo = iddanhGiaCanBo;
		this.canboByMaNguoiDanhGia = canboByMaNguoiDanhGia;
		this.canboByMaCbduocDanhGia = canboByMaCbduocDanhGia;
		this.mucdohoanthanh = mucdohoanthanh;
		this.quy = quy;
		this.noiDung = noiDung;
		this.ngayDanhGia = ngayDanhGia;
		this.nam = nam;
		this.laQuanLyHienTai = laQuanLyHienTai;
	}

	public Danhgiacanbo(int iddanhGiaCanBo, Canbo canboByMaNguoiDanhGia, Canbo canboByMaCbduocDanhGia,
			Mucdohoanthanh mucdohoanthanh, Quy quy, String noiDung, Date ngayDanhGia, int nam, boolean laQuanLyHienTai,
			String chucVuHienTaiNguoiDanhGia) {
		this.iddanhGiaCanBo = iddanhGiaCanBo;
		this.canboByMaNguoiDanhGia = canboByMaNguoiDanhGia;
		this.canboByMaCbduocDanhGia = canboByMaCbduocDanhGia;
		this.mucdohoanthanh = mucdohoanthanh;
		this.quy = quy;
		this.noiDung = noiDung;
		this.ngayDanhGia = ngayDanhGia;
		this.nam = nam;
		this.laQuanLyHienTai = laQuanLyHienTai;
		this.chucVuHienTaiNguoiDanhGia = chucVuHienTaiNguoiDanhGia;
	}

	@Id

	@Column(name = "IDDanhGiaCanBo", unique = true, nullable = false)
	public int getIddanhGiaCanBo() {
		return this.iddanhGiaCanBo;
	}

	public void setIddanhGiaCanBo(int iddanhGiaCanBo) {
		this.iddanhGiaCanBo = iddanhGiaCanBo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaNguoiDanhGia", nullable = false)
	public Canbo getCanboByMaNguoiDanhGia() {
		return this.canboByMaNguoiDanhGia;
	}

	public void setCanboByMaNguoiDanhGia(Canbo canboByMaNguoiDanhGia) {
		this.canboByMaNguoiDanhGia = canboByMaNguoiDanhGia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaCBDuocDanhGia", nullable = false)
	public Canbo getCanboByMaCbduocDanhGia() {
		return this.canboByMaCbduocDanhGia;
	}

	public void setCanboByMaCbduocDanhGia(Canbo canboByMaCbduocDanhGia) {
		this.canboByMaCbduocDanhGia = canboByMaCbduocDanhGia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MucDoHoanThanh", nullable = false)
	public Mucdohoanthanh getMucdohoanthanh() {
		return this.mucdohoanthanh;
	}

	public void setMucdohoanthanh(Mucdohoanthanh mucdohoanthanh) {
		this.mucdohoanthanh = mucdohoanthanh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Quy", nullable = false)
	public Quy getQuy() {
		return this.quy;
	}

	public void setQuy(Quy quy) {
		this.quy = quy;
	}

	@Column(name = "NoiDung", nullable = false, length = 65535)
	public String getNoiDung() {
		return this.noiDung;
	}

	public void setNoiDung(String noiDung) {
		this.noiDung = noiDung;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NgayDanhGia", nullable = false, length = 10)
	public Date getNgayDanhGia() {
		return this.ngayDanhGia;
	}

	public void setNgayDanhGia(Date ngayDanhGia) {
		this.ngayDanhGia = ngayDanhGia;
	}

	@Column(name = "Nam", nullable = false)
	public int getNam() {
		return this.nam;
	}

	public void setNam(int nam) {
		this.nam = nam;
	}

	@Column(name = "LaQuanLyHienTai", nullable = false)
	public boolean isLaQuanLyHienTai() {
		return this.laQuanLyHienTai;
	}

	public void setLaQuanLyHienTai(boolean laQuanLyHienTai) {
		this.laQuanLyHienTai = laQuanLyHienTai;
	}

	@Column(name = "ChucVuHienTaiNguoiDanhGia", length = 65535)
	public String getChucVuHienTaiNguoiDanhGia() {
		return this.chucVuHienTaiNguoiDanhGia;
	}

	public void setChucVuHienTaiNguoiDanhGia(String chucVuHienTaiNguoiDanhGia) {
		this.chucVuHienTaiNguoiDanhGia = chucVuHienTaiNguoiDanhGia;
	}

}
