package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DanhGiaCanBo generated by hbm2java
 */
@Entity
@Table(name = "danh_gia_can_bo", catalog = "qlcb")
public class DanhGiaCanBo implements java.io.Serializable {

	private DanhGiaCanBoId id;
	private Ban ban;
	private CanBo canBoByMaCbTuDanhGia;
	private CanBo canBoByMaCbDanhGia;
	private ChieuHuongPhatTrien chieuHuongPhatTrien;
	private DonVi donVi;
	private MucDoHoanThanh mucDoHoanThanhByMaMdhtTuDanhGia;
	private MucDoHoanThanh mucDoHoanThanhByMaMdht;
	private String noiDungTuDanhGia;
	private Date thoiGianMuonChuyen;
	private String nguyenVongDaoTao;
	private String noiDungDanhGia;
	private String dinhHuong;

	public DanhGiaCanBo() {
	}

	public DanhGiaCanBo(DanhGiaCanBoId id, CanBo canBoByMaCbTuDanhGia) {
		this.id = id;
		this.canBoByMaCbTuDanhGia = canBoByMaCbTuDanhGia;
	}

	public DanhGiaCanBo(DanhGiaCanBoId id, Ban ban, CanBo canBoByMaCbTuDanhGia, CanBo canBoByMaCbDanhGia,
			ChieuHuongPhatTrien chieuHuongPhatTrien, DonVi donVi, MucDoHoanThanh mucDoHoanThanhByMaMdhtTuDanhGia,
			MucDoHoanThanh mucDoHoanThanhByMaMdht, String noiDungTuDanhGia, Date thoiGianMuonChuyen,
			String nguyenVongDaoTao, String noiDungDanhGia, String dinhHuong) {
		this.id = id;
		this.ban = ban;
		this.canBoByMaCbTuDanhGia = canBoByMaCbTuDanhGia;
		this.canBoByMaCbDanhGia = canBoByMaCbDanhGia;
		this.chieuHuongPhatTrien = chieuHuongPhatTrien;
		this.donVi = donVi;
		this.mucDoHoanThanhByMaMdhtTuDanhGia = mucDoHoanThanhByMaMdhtTuDanhGia;
		this.mucDoHoanThanhByMaMdht = mucDoHoanThanhByMaMdht;
		this.noiDungTuDanhGia = noiDungTuDanhGia;
		this.thoiGianMuonChuyen = thoiGianMuonChuyen;
		this.nguyenVongDaoTao = nguyenVongDaoTao;
		this.noiDungDanhGia = noiDungDanhGia;
		this.dinhHuong = dinhHuong;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "maCbTuDanhGia", column = @Column(name = "Ma_CB_Tu_Danh_Gia", nullable = false)),
			@AttributeOverride(name = "ngayDanhGia", column = @Column(name = "Ngay_Danh_Gia", nullable = false, length = 10)) })
	public DanhGiaCanBoId getId() {
		return this.id;
	}

	public void setId(DanhGiaCanBoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ma_Ban_Muon_Den")
	public Ban getBan() {
		return this.ban;
	}

	public void setBan(Ban ban) {
		this.ban = ban;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ma_CB_Tu_Danh_Gia", nullable = false, insertable = false, updatable = false)
	public CanBo getCanBoByMaCbTuDanhGia() {
		return this.canBoByMaCbTuDanhGia;
	}

	public void setCanBoByMaCbTuDanhGia(CanBo canBoByMaCbTuDanhGia) {
		this.canBoByMaCbTuDanhGia = canBoByMaCbTuDanhGia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ma_CB_Danh_Gia")
	public CanBo getCanBoByMaCbDanhGia() {
		return this.canBoByMaCbDanhGia;
	}

	public void setCanBoByMaCbDanhGia(CanBo canBoByMaCbDanhGia) {
		this.canBoByMaCbDanhGia = canBoByMaCbDanhGia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ma_CHPT")
	public ChieuHuongPhatTrien getChieuHuongPhatTrien() {
		return this.chieuHuongPhatTrien;
	}

	public void setChieuHuongPhatTrien(ChieuHuongPhatTrien chieuHuongPhatTrien) {
		this.chieuHuongPhatTrien = chieuHuongPhatTrien;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ma_DV_Muon_Den")
	public DonVi getDonVi() {
		return this.donVi;
	}

	public void setDonVi(DonVi donVi) {
		this.donVi = donVi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ma_MDHT_Tu_Danh_Gia")
	public MucDoHoanThanh getMucDoHoanThanhByMaMdhtTuDanhGia() {
		return this.mucDoHoanThanhByMaMdhtTuDanhGia;
	}

	public void setMucDoHoanThanhByMaMdhtTuDanhGia(MucDoHoanThanh mucDoHoanThanhByMaMdhtTuDanhGia) {
		this.mucDoHoanThanhByMaMdhtTuDanhGia = mucDoHoanThanhByMaMdhtTuDanhGia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ma_MDHT")
	public MucDoHoanThanh getMucDoHoanThanhByMaMdht() {
		return this.mucDoHoanThanhByMaMdht;
	}

	public void setMucDoHoanThanhByMaMdht(MucDoHoanThanh mucDoHoanThanhByMaMdht) {
		this.mucDoHoanThanhByMaMdht = mucDoHoanThanhByMaMdht;
	}

	@Column(name = "Noi_Dung_Tu_Danh_Gia", length = 65535)
	public String getNoiDungTuDanhGia() {
		return this.noiDungTuDanhGia;
	}

	public void setNoiDungTuDanhGia(String noiDungTuDanhGia) {
		this.noiDungTuDanhGia = noiDungTuDanhGia;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Thoi_Gian_Muon_Chuyen", length = 10)
	public Date getThoiGianMuonChuyen() {
		return this.thoiGianMuonChuyen;
	}

	public void setThoiGianMuonChuyen(Date thoiGianMuonChuyen) {
		this.thoiGianMuonChuyen = thoiGianMuonChuyen;
	}

	@Column(name = "Nguyen_Vong_Dao_Tao", length = 65535)
	public String getNguyenVongDaoTao() {
		return this.nguyenVongDaoTao;
	}

	public void setNguyenVongDaoTao(String nguyenVongDaoTao) {
		this.nguyenVongDaoTao = nguyenVongDaoTao;
	}

	@Column(name = "Noi_Dung_Danh_Gia", length = 65535)
	public String getNoiDungDanhGia() {
		return this.noiDungDanhGia;
	}

	public void setNoiDungDanhGia(String noiDungDanhGia) {
		this.noiDungDanhGia = noiDungDanhGia;
	}

	@Column(name = "Dinh_Huong", length = 65535)
	public String getDinhHuong() {
		return this.dinhHuong;
	}

	public void setDinhHuong(String dinhHuong) {
		this.dinhHuong = dinhHuong;
	}

}
