package com.springmvc.qlcb.model;
// Generated Apr 25, 2016 2:33:53 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.Length;

/**
 * Dantoc generated by hbm2java
 */
@Entity
@Table(name = "dantoc", catalog = "qlcb")
public class Dantoc implements java.io.Serializable {

	private int maDanToc;
	@NotNull(message="không để trống") 
	@Length(max=10,min=3, message="không để trống") 
	private String tenDanToc;
	private Set<Lylich> lyliches = new HashSet<Lylich>(0);

	public Dantoc() {
	}

	public Dantoc(int maDanToc, String tenDanToc) {
		this.maDanToc = maDanToc;
		this.tenDanToc = tenDanToc;
	}

	public Dantoc(int maDanToc, String tenDanToc, Set<Lylich> lyliches) {
		this.maDanToc = maDanToc;
		this.tenDanToc = tenDanToc;
		this.lyliches = lyliches;
	}

	@Id

	@Column(name = "MaDanToc", unique = true, nullable = false)
	public int getMaDanToc() {
		return this.maDanToc;
	}

	public void setMaDanToc(int maDanToc) {
		this.maDanToc = maDanToc;
	}

	@Column(name = "TenDanToc", nullable = false, length = 200)
	public String getTenDanToc() {
		return this.tenDanToc;
	}

	public void setTenDanToc(String tenDanToc) {
		this.tenDanToc = tenDanToc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dantoc")
	public Set<Lylich> getLyliches() {
		return this.lyliches;
	}

	public void setLyliches(Set<Lylich> lyliches) {
		this.lyliches = lyliches;
	}

}
