package com.springmvc.qlcb.model;
// Generated Apr 19, 2016 9:35:55 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Dantoc generated by hbm2java
 */
@Entity
@Table(name = "dantoc", catalog = "qlcb_new")
public class Dantoc implements java.io.Serializable {

	private int id;
	private String tenDanToc;
	private Set<Lylich> lyliches = new HashSet<Lylich>(0);

	public Dantoc() {
	}

	public Dantoc(int id, String tenDanToc) {
		this.id = id;
		this.tenDanToc = tenDanToc;
	}

	public Dantoc(int id, String tenDanToc, Set<Lylich> lyliches) {
		this.id = id;
		this.tenDanToc = tenDanToc;
		this.lyliches = lyliches;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "TenDanToc", nullable = false, length = 200)
	public String getTenDanToc() {
		return this.tenDanToc;
	}

	public void setTenDanToc(String tenDanToc) {
		this.tenDanToc = tenDanToc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dantoc")
	public Set<Lylich> getLyliches() {
		return this.lyliches;
	}

	public void setLyliches(Set<Lylich> lyliches) {
		this.lyliches = lyliches;
	}

}
