package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DanToc generated by hbm2java
 */
@Entity
@Table(name = "dan_toc", catalog = "qlcb")
public class DanToc implements java.io.Serializable {

	private Short maDanToc;
	private String tenDanToc;
	private Set<LyLich> lyLiches = new HashSet<LyLich>(0);

	public DanToc() {
	}

	public DanToc(String tenDanToc, Set<LyLich> lyLiches) {
		this.tenDanToc = tenDanToc;
		this.lyLiches = lyLiches;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Ma_Dan_Toc", unique = true, nullable = false)
	public Short getMaDanToc() {
		return this.maDanToc;
	}

	public void setMaDanToc(Short maDanToc) {
		this.maDanToc = maDanToc;
	}

	@Column(name = "Ten_Dan_Toc", length = 63)
	public String getTenDanToc() {
		return this.tenDanToc;
	}

	public void setTenDanToc(String tenDanToc) {
		this.tenDanToc = tenDanToc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "danToc")
	public Set<LyLich> getLyLiches() {
		return this.lyLiches;
	}

	public void setLyLiches(Set<LyLich> lyLiches) {
		this.lyLiches = lyLiches;
	}

}
