package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DaoTaoBoiDuong generated by hbm2java
 */
@Entity
@Table(name = "dao_tao_boi_duong", catalog = "qlcb")
public class DaoTaoBoiDuong implements java.io.Serializable {

	private DaoTaoBoiDuongId id;
	private CanBo canBo;
	private String tenTruong;
	private String nganhHoc;
	private Date thoiGianHoc;
	private Date tgKetThuc;
	private String hinhThucHoc;
	private String vanBangChungChi;

	public DaoTaoBoiDuong() {
	}

	public DaoTaoBoiDuong(DaoTaoBoiDuongId id, CanBo canBo) {
		this.id = id;
		this.canBo = canBo;
	}

	public DaoTaoBoiDuong(DaoTaoBoiDuongId id, CanBo canBo, String tenTruong, String nganhHoc, Date thoiGianHoc,
			Date tgKetThuc, String hinhThucHoc, String vanBangChungChi) {
		this.id = id;
		this.canBo = canBo;
		this.tenTruong = tenTruong;
		this.nganhHoc = nganhHoc;
		this.thoiGianHoc = thoiGianHoc;
		this.tgKetThuc = tgKetThuc;
		this.hinhThucHoc = hinhThucHoc;
		this.vanBangChungChi = vanBangChungChi;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "maDtbd", column = @Column(name = "Ma_DTBD", nullable = false)),
			@AttributeOverride(name = "maCb", column = @Column(name = "Ma_CB", nullable = false)) })
	public DaoTaoBoiDuongId getId() {
		return this.id;
	}

	public void setId(DaoTaoBoiDuongId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ma_CB", nullable = false, insertable = false, updatable = false)
	public CanBo getCanBo() {
		return this.canBo;
	}

	public void setCanBo(CanBo canBo) {
		this.canBo = canBo;
	}

	@Column(name = "Ten_Truong", length = 254)
	public String getTenTruong() {
		return this.tenTruong;
	}

	public void setTenTruong(String tenTruong) {
		this.tenTruong = tenTruong;
	}

	@Column(name = "Nganh_Hoc", length = 254)
	public String getNganhHoc() {
		return this.nganhHoc;
	}

	public void setNganhHoc(String nganhHoc) {
		this.nganhHoc = nganhHoc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Thoi_Gian_Hoc", length = 10)
	public Date getThoiGianHoc() {
		return this.thoiGianHoc;
	}

	public void setThoiGianHoc(Date thoiGianHoc) {
		this.thoiGianHoc = thoiGianHoc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TG_Ket_Thuc", length = 10)
	public Date getTgKetThuc() {
		return this.tgKetThuc;
	}

	public void setTgKetThuc(Date tgKetThuc) {
		this.tgKetThuc = tgKetThuc;
	}

	@Column(name = "Hinh_Thuc_Hoc", length = 254)
	public String getHinhThucHoc() {
		return this.hinhThucHoc;
	}

	public void setHinhThucHoc(String hinhThucHoc) {
		this.hinhThucHoc = hinhThucHoc;
	}

	@Column(name = "Van_Bang_Chung_Chi", length = 254)
	public String getVanBangChungChi() {
		return this.vanBangChungChi;
	}

	public void setVanBangChungChi(String vanBangChungChi) {
		this.vanBangChungChi = vanBangChungChi;
	}

}
