package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DaoTaoBoiDuongId generated by hbm2java
 */
@Embeddable
public class DaoTaoBoiDuongId implements java.io.Serializable {

	private long maDtbd;
	private int maCb;

	public DaoTaoBoiDuongId() {
	}

	public DaoTaoBoiDuongId(long maDtbd, int maCb) {
		this.maDtbd = maDtbd;
		this.maCb = maCb;
	}

	@Column(name = "Ma_DTBD", nullable = false)
	public long getMaDtbd() {
		return this.maDtbd;
	}

	public void setMaDtbd(long maDtbd) {
		this.maDtbd = maDtbd;
	}

	@Column(name = "Ma_CB", nullable = false)
	public int getMaCb() {
		return this.maCb;
	}

	public void setMaCb(int maCb) {
		this.maCb = maCb;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DaoTaoBoiDuongId))
			return false;
		DaoTaoBoiDuongId castOther = (DaoTaoBoiDuongId) other;

		return (this.getMaDtbd() == castOther.getMaDtbd()) && (this.getMaCb() == castOther.getMaCb());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getMaDtbd();
		result = 37 * result + this.getMaCb();
		return result;
	}

}
