package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DienKhenThuong generated by hbm2java
 */
@Entity
@Table(name = "dien_khen_thuong", catalog = "qlcb")
public class DienKhenThuong implements java.io.Serializable {

	private Short maDien;
	private String tenDien;
	private Long mucThuongKhung;
	private Set<MucThuongTheoDien> mucThuongTheoDiens = new HashSet<MucThuongTheoDien>(0);
	private Set<KhenThuong> khenThuongs = new HashSet<KhenThuong>(0);

	public DienKhenThuong() {
	}

	public DienKhenThuong(String tenDien, Long mucThuongKhung, Set<MucThuongTheoDien> mucThuongTheoDiens,
			Set<KhenThuong> khenThuongs) {
		this.tenDien = tenDien;
		this.mucThuongKhung = mucThuongKhung;
		this.mucThuongTheoDiens = mucThuongTheoDiens;
		this.khenThuongs = khenThuongs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Ma_Dien", unique = true, nullable = false)
	public Short getMaDien() {
		return this.maDien;
	}

	public void setMaDien(Short maDien) {
		this.maDien = maDien;
	}

	@Column(name = "Ten_Dien", length = 254)
	public String getTenDien() {
		return this.tenDien;
	}

	public void setTenDien(String tenDien) {
		this.tenDien = tenDien;
	}

	@Column(name = "Muc_Thuong_Khung")
	public Long getMucThuongKhung() {
		return this.mucThuongKhung;
	}

	public void setMucThuongKhung(Long mucThuongKhung) {
		this.mucThuongKhung = mucThuongKhung;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dienKhenThuong")
	public Set<MucThuongTheoDien> getMucThuongTheoDiens() {
		return this.mucThuongTheoDiens;
	}

	public void setMucThuongTheoDiens(Set<MucThuongTheoDien> mucThuongTheoDiens) {
		this.mucThuongTheoDiens = mucThuongTheoDiens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dienKhenThuong")
	public Set<KhenThuong> getKhenThuongs() {
		return this.khenThuongs;
	}

	public void setKhenThuongs(Set<KhenThuong> khenThuongs) {
		this.khenThuongs = khenThuongs;
	}

}
