package com.springmvc.qlcb.model;
// Generated Apr 19, 2016 9:35:55 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Donvi generated by hbm2java
 */
@Entity
@Table(name = "donvi", catalog = "qlcb_new")
public class Donvi implements java.io.Serializable {

	private int id;
	private String tenDonVi;
	private int maKhoi;
	private Integer maTruongDonVi;
	private Date ngayThanhLap;
	private String moTa;
	private Set<CanboDonvi> canboDonvis = new HashSet<CanboDonvi>(0);

	public Donvi() {
	}

	public Donvi(int id, String tenDonVi, int maKhoi, Date ngayThanhLap) {
		this.id = id;
		this.tenDonVi = tenDonVi;
		this.maKhoi = maKhoi;
		this.ngayThanhLap = ngayThanhLap;
	}

	public Donvi(int id, String tenDonVi, int maKhoi, Integer maTruongDonVi, Date ngayThanhLap, String moTa,
			Set<CanboDonvi> canboDonvis) {
		this.id = id;
		this.tenDonVi = tenDonVi;
		this.maKhoi = maKhoi;
		this.maTruongDonVi = maTruongDonVi;
		this.ngayThanhLap = ngayThanhLap;
		this.moTa = moTa;
		this.canboDonvis = canboDonvis;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "TenDonVi", nullable = false, length = 250)
	public String getTenDonVi() {
		return this.tenDonVi;
	}

	public void setTenDonVi(String tenDonVi) {
		this.tenDonVi = tenDonVi;
	}

	@Column(name = "MaKhoi", nullable = false)
	public int getMaKhoi() {
		return this.maKhoi;
	}

	public void setMaKhoi(int maKhoi) {
		this.maKhoi = maKhoi;
	}

	@Column(name = "MaTruongDonVi")
	public Integer getMaTruongDonVi() {
		return this.maTruongDonVi;
	}

	public void setMaTruongDonVi(Integer maTruongDonVi) {
		this.maTruongDonVi = maTruongDonVi;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NgayThanhLap", nullable = false, length = 10)
	public Date getNgayThanhLap() {
		return this.ngayThanhLap;
	}

	public void setNgayThanhLap(Date ngayThanhLap) {
		this.ngayThanhLap = ngayThanhLap;
	}

	@Column(name = "MoTa", length = 65535)
	public String getMoTa() {
		return this.moTa;
	}

	public void setMoTa(String moTa) {
		this.moTa = moTa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "donvi")
	public Set<CanboDonvi> getCanboDonvis() {
		return this.canboDonvis;
	}

	public void setCanboDonvis(Set<CanboDonvi> canboDonvis) {
		this.canboDonvis = canboDonvis;
	}

}
