package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DonVi generated by hbm2java
 */
@Entity
@Table(name = "don_vi", catalog = "qlcb")
public class DonVi implements java.io.Serializable {

	private Short maDv;
	private Ban ban;
	private CanBo canBo;
	private Khoi khoi;
	private String kyHieuDv;
	private String tenDonVi;
	private Date ngayThanhLap;
	private String chucNangDv;
	private String diaChi;
	private String email;
	private String soDienThoai;
	private String moTa;
	private Byte trangThai;
	private Set<CanBo> canBos = new HashSet<CanBo>(0);
	private Set<DanhGiaCanBo> danhGiaCanBos = new HashSet<DanhGiaCanBo>(0);
	private Set<Ban> bans = new HashSet<Ban>(0);

	public DonVi() {
	}

	public DonVi(String kyHieuDv) {
		this.kyHieuDv = kyHieuDv;
	}

	public DonVi(Ban ban, CanBo canBo, Khoi khoi, String kyHieuDv, String tenDonVi, Date ngayThanhLap,
			String chucNangDv, String diaChi, String email, String soDienThoai, String moTa, Byte trangThai,
			Set<CanBo> canBos, Set<DanhGiaCanBo> danhGiaCanBos, Set<Ban> bans) {
		this.ban = ban;
		this.canBo = canBo;
		this.khoi = khoi;
		this.kyHieuDv = kyHieuDv;
		this.tenDonVi = tenDonVi;
		this.ngayThanhLap = ngayThanhLap;
		this.chucNangDv = chucNangDv;
		this.diaChi = diaChi;
		this.email = email;
		this.soDienThoai = soDienThoai;
		this.moTa = moTa;
		this.trangThai = trangThai;
		this.canBos = canBos;
		this.danhGiaCanBos = danhGiaCanBos;
		this.bans = bans;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Ma_DV", unique = true, nullable = false)
	public Short getMaDv() {
		return this.maDv;
	}

	public void setMaDv(Short maDv) {
		this.maDv = maDv;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ma_Ban_Chap_Hanh")
	public Ban getBan() {
		return this.ban;
	}

	public void setBan(Ban ban) {
		this.ban = ban;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ma_Truong_DV")
	public CanBo getCanBo() {
		return this.canBo;
	}

	public void setCanBo(CanBo canBo) {
		this.canBo = canBo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ma_Khoi")
	public Khoi getKhoi() {
		return this.khoi;
	}

	public void setKhoi(Khoi khoi) {
		this.khoi = khoi;
	}

	@Column(name = "Ky_Hieu_DV", nullable = false, length = 32)
	public String getKyHieuDv() {
		return this.kyHieuDv;
	}

	public void setKyHieuDv(String kyHieuDv) {
		this.kyHieuDv = kyHieuDv;
	}

	@Column(name = "Ten_Don_Vi", length = 254)
	public String getTenDonVi() {
		return this.tenDonVi;
	}

	public void setTenDonVi(String tenDonVi) {
		this.tenDonVi = tenDonVi;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Ngay_Thanh_Lap", length = 10)
	public Date getNgayThanhLap() {
		return this.ngayThanhLap;
	}

	public void setNgayThanhLap(Date ngayThanhLap) {
		this.ngayThanhLap = ngayThanhLap;
	}

	@Column(name = "Chuc_Nang_DV", length = 254)
	public String getChucNangDv() {
		return this.chucNangDv;
	}

	public void setChucNangDv(String chucNangDv) {
		this.chucNangDv = chucNangDv;
	}

	@Column(name = "Dia_Chi", length = 254)
	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	@Column(name = "Email", length = 126)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "So_Dien_Thoai", length = 62)
	public String getSoDienThoai() {
		return this.soDienThoai;
	}

	public void setSoDienThoai(String soDienThoai) {
		this.soDienThoai = soDienThoai;
	}

	@Column(name = "Mo_Ta", length = 254)
	public String getMoTa() {
		return this.moTa;
	}

	public void setMoTa(String moTa) {
		this.moTa = moTa;
	}

	@Column(name = "Trang_Thai")
	public Byte getTrangThai() {
		return this.trangThai;
	}

	public void setTrangThai(Byte trangThai) {
		this.trangThai = trangThai;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "donVi")
	public Set<CanBo> getCanBos() {
		return this.canBos;
	}

	public void setCanBos(Set<CanBo> canBos) {
		this.canBos = canBos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "donVi")
	public Set<DanhGiaCanBo> getDanhGiaCanBos() {
		return this.danhGiaCanBos;
	}

	public void setDanhGiaCanBos(Set<DanhGiaCanBo> danhGiaCanBos) {
		this.danhGiaCanBos = danhGiaCanBos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "donVi")
	public Set<Ban> getBans() {
		return this.bans;
	}

	public void setBans(Set<Ban> bans) {
		this.bans = bans;
	}

}
