package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HopDongCongTacId generated by hbm2java
 */
@Embeddable
public class HopDongCongTacId implements java.io.Serializable {

	private int maBan;
	private int maCtv;
	private Date ngayBatDau;

	public HopDongCongTacId() {
	}

	public HopDongCongTacId(int maBan, int maCtv, Date ngayBatDau) {
		this.maBan = maBan;
		this.maCtv = maCtv;
		this.ngayBatDau = ngayBatDau;
	}

	@Column(name = "Ma_Ban", nullable = false)
	public int getMaBan() {
		return this.maBan;
	}

	public void setMaBan(int maBan) {
		this.maBan = maBan;
	}

	@Column(name = "Ma_CTV", nullable = false)
	public int getMaCtv() {
		return this.maCtv;
	}

	public void setMaCtv(int maCtv) {
		this.maCtv = maCtv;
	}

	@Column(name = "Ngay_Bat_Dau", nullable = false, length = 19)
	public Date getNgayBatDau() {
		return this.ngayBatDau;
	}

	public void setNgayBatDau(Date ngayBatDau) {
		this.ngayBatDau = ngayBatDau;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HopDongCongTacId))
			return false;
		HopDongCongTacId castOther = (HopDongCongTacId) other;

		return (this.getMaBan() == castOther.getMaBan()) && (this.getMaCtv() == castOther.getMaCtv())
				&& ((this.getNgayBatDau() == castOther.getNgayBatDau())
						|| (this.getNgayBatDau() != null && castOther.getNgayBatDau() != null
								&& this.getNgayBatDau().equals(castOther.getNgayBatDau())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMaBan();
		result = 37 * result + this.getMaCtv();
		result = 37 * result + (getNgayBatDau() == null ? 0 : this.getNgayBatDau().hashCode());
		return result;
	}

}
