package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HopDongCongTac generated by hbm2java
 */
@Entity
@Table(name = "hop_dong_cong_tac", catalog = "qlcb")
public class HopDongCongTac implements java.io.Serializable {

	private HopDongCongTacId id;
	private Ban ban;
	private CongTacVien congTacVien;
	private Date ngayKetThuc;
	private String nhiemVu;
	private Long tienLuongKhoan;

	public HopDongCongTac() {
	}

	public HopDongCongTac(HopDongCongTacId id, Ban ban, CongTacVien congTacVien) {
		this.id = id;
		this.ban = ban;
		this.congTacVien = congTacVien;
	}

	public HopDongCongTac(HopDongCongTacId id, Ban ban, CongTacVien congTacVien, Date ngayKetThuc, String nhiemVu,
			Long tienLuongKhoan) {
		this.id = id;
		this.ban = ban;
		this.congTacVien = congTacVien;
		this.ngayKetThuc = ngayKetThuc;
		this.nhiemVu = nhiemVu;
		this.tienLuongKhoan = tienLuongKhoan;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "maBan", column = @Column(name = "Ma_Ban", nullable = false)),
			@AttributeOverride(name = "maCtv", column = @Column(name = "Ma_CTV", nullable = false)),
			@AttributeOverride(name = "ngayBatDau", column = @Column(name = "Ngay_Bat_Dau", nullable = false, length = 19)) })
	public HopDongCongTacId getId() {
		return this.id;
	}

	public void setId(HopDongCongTacId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ma_Ban", nullable = false, insertable = false, updatable = false)
	public Ban getBan() {
		return this.ban;
	}

	public void setBan(Ban ban) {
		this.ban = ban;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ma_CTV", nullable = false, insertable = false, updatable = false)
	public CongTacVien getCongTacVien() {
		return this.congTacVien;
	}

	public void setCongTacVien(CongTacVien congTacVien) {
		this.congTacVien = congTacVien;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Ngay_Ket_Thuc", length = 10)
	public Date getNgayKetThuc() {
		return this.ngayKetThuc;
	}

	public void setNgayKetThuc(Date ngayKetThuc) {
		this.ngayKetThuc = ngayKetThuc;
	}

	@Column(name = "Nhiem_Vu", length = 254)
	public String getNhiemVu() {
		return this.nhiemVu;
	}

	public void setNhiemVu(String nhiemVu) {
		this.nhiemVu = nhiemVu;
	}

	@Column(name = "Tien_Luong_Khoan")
	public Long getTienLuongKhoan() {
		return this.tienLuongKhoan;
	}

	public void setTienLuongKhoan(Long tienLuongKhoan) {
		this.tienLuongKhoan = tienLuongKhoan;
	}

}
