package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * KhenThuongId generated by hbm2java
 */
@Embeddable
public class KhenThuongId implements java.io.Serializable {

	private long maKhenThuong;
	private int maCb;

	public KhenThuongId() {
	}

	public KhenThuongId(long maKhenThuong, int maCb) {
		this.maKhenThuong = maKhenThuong;
		this.maCb = maCb;
	}

	@Column(name = "Ma_Khen_Thuong", nullable = false)
	public long getMaKhenThuong() {
		return this.maKhenThuong;
	}

	public void setMaKhenThuong(long maKhenThuong) {
		this.maKhenThuong = maKhenThuong;
	}

	@Column(name = "Ma_CB", nullable = false)
	public int getMaCb() {
		return this.maCb;
	}

	public void setMaCb(int maCb) {
		this.maCb = maCb;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof KhenThuongId))
			return false;
		KhenThuongId castOther = (KhenThuongId) other;

		return (this.getMaKhenThuong() == castOther.getMaKhenThuong()) && (this.getMaCb() == castOther.getMaCb());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getMaKhenThuong();
		result = 37 * result + this.getMaCb();
		return result;
	}

}
