package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Khoi generated by hbm2java
 */
@Entity
@Table(name = "khoi", catalog = "qlcb")
public class Khoi implements java.io.Serializable {

	private Byte maKhoi;
	private Khoi khoi;
	private String tenKhoi;
	private String moTa;
	private Set<Khoi> khois = new HashSet<Khoi>(0);
	private Set<DonVi> donVis = new HashSet<DonVi>(0);

	public Khoi() {
	}

	public Khoi(Khoi khoi, String tenKhoi, String moTa, Set<Khoi> khois, Set<DonVi> donVis) {
		this.khoi = khoi;
		this.tenKhoi = tenKhoi;
		this.moTa = moTa;
		this.khois = khois;
		this.donVis = donVis;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Ma_Khoi", unique = true, nullable = false)
	public Byte getMaKhoi() {
		return this.maKhoi;
	}

	public void setMaKhoi(Byte maKhoi) {
		this.maKhoi = maKhoi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ma_Khoi_Cap_Tren")
	public Khoi getKhoi() {
		return this.khoi;
	}

	public void setKhoi(Khoi khoi) {
		this.khoi = khoi;
	}

	@Column(name = "Ten_Khoi", length = 254)
	public String getTenKhoi() {
		return this.tenKhoi;
	}

	public void setTenKhoi(String tenKhoi) {
		this.tenKhoi = tenKhoi;
	}

	@Column(name = "Mo_Ta", length = 254)
	public String getMoTa() {
		return this.moTa;
	}

	public void setMoTa(String moTa) {
		this.moTa = moTa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "khoi")
	public Set<Khoi> getKhois() {
		return this.khois;
	}

	public void setKhois(Set<Khoi> khois) {
		this.khois = khois;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "khoi")
	public Set<DonVi> getDonVis() {
		return this.donVis;
	}

	public void setDonVis(Set<DonVi> donVis) {
		this.donVis = donVis;
	}

}
