package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * KienNghiId generated by hbm2java
 */
@Embeddable
public class KienNghiId implements java.io.Serializable {

	private Date thoiGian;
	private int maCbKienNghi;

	public KienNghiId() {
	}

	public KienNghiId(Date thoiGian, int maCbKienNghi) {
		this.thoiGian = thoiGian;
		this.maCbKienNghi = maCbKienNghi;
	}

	@Column(name = "Thoi_Gian", nullable = false, length = 19)
	public Date getThoiGian() {
		return this.thoiGian;
	}

	public void setThoiGian(Date thoiGian) {
		this.thoiGian = thoiGian;
	}

	@Column(name = "Ma_CB_Kien_Nghi", nullable = false)
	public int getMaCbKienNghi() {
		return this.maCbKienNghi;
	}

	public void setMaCbKienNghi(int maCbKienNghi) {
		this.maCbKienNghi = maCbKienNghi;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof KienNghiId))
			return false;
		KienNghiId castOther = (KienNghiId) other;

		return ((this.getThoiGian() == castOther.getThoiGian()) || (this.getThoiGian() != null
				&& castOther.getThoiGian() != null && this.getThoiGian().equals(castOther.getThoiGian())))
				&& (this.getMaCbKienNghi() == castOther.getMaCbKienNghi());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getThoiGian() == null ? 0 : this.getThoiGian().hashCode());
		result = 37 * result + this.getMaCbKienNghi();
		return result;
	}

}
