package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * KienNghi generated by hbm2java
 */
@Entity
@Table(name = "kien_nghi", catalog = "qlcb")
public class KienNghi implements java.io.Serializable {

	private KienNghiId id;
	private CanBo canBo;
	private String tenKienNghi;
	private String noiDung;
	private String fileUrl;
	private Byte trangThai;

	public KienNghi() {
	}

	public KienNghi(KienNghiId id, CanBo canBo) {
		this.id = id;
		this.canBo = canBo;
	}

	public KienNghi(KienNghiId id, CanBo canBo, String tenKienNghi, String noiDung, String fileUrl, Byte trangThai) {
		this.id = id;
		this.canBo = canBo;
		this.tenKienNghi = tenKienNghi;
		this.noiDung = noiDung;
		this.fileUrl = fileUrl;
		this.trangThai = trangThai;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "thoiGian", column = @Column(name = "Thoi_Gian", nullable = false, length = 19)),
			@AttributeOverride(name = "maCbKienNghi", column = @Column(name = "Ma_CB_Kien_Nghi", nullable = false)) })
	public KienNghiId getId() {
		return this.id;
	}

	public void setId(KienNghiId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ma_CB_Kien_Nghi", nullable = false, insertable = false, updatable = false)
	public CanBo getCanBo() {
		return this.canBo;
	}

	public void setCanBo(CanBo canBo) {
		this.canBo = canBo;
	}

	@Column(name = "Ten_Kien_Nghi", length = 254)
	public String getTenKienNghi() {
		return this.tenKienNghi;
	}

	public void setTenKienNghi(String tenKienNghi) {
		this.tenKienNghi = tenKienNghi;
	}

	@Column(name = "Noi_Dung", length = 65535)
	public String getNoiDung() {
		return this.noiDung;
	}

	public void setNoiDung(String noiDung) {
		this.noiDung = noiDung;
	}

	@Column(name = "File_URL", length = 254)
	public String getFileUrl() {
		return this.fileUrl;
	}

	public void setFileUrl(String fileUrl) {
		this.fileUrl = fileUrl;
	}

	@Column(name = "Trang_Thai")
	public Byte getTrangThai() {
		return this.trangThai;
	}

	public void setTrangThai(Byte trangThai) {
		this.trangThai = trangThai;
	}

}
