package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * KieuLoaiHinhBan generated by hbm2java
 */
@Entity
@Table(name = "kieu_loai_hinh_ban", catalog = "qlcb")
public class KieuLoaiHinhBan implements java.io.Serializable {

	private byte maKlhb;
	private String tenKlhb;
	private String moTa;
	private Set<LoaiHinhBan> loaiHinhBans = new HashSet<LoaiHinhBan>(0);

	public KieuLoaiHinhBan() {
	}

	public KieuLoaiHinhBan(byte maKlhb) {
		this.maKlhb = maKlhb;
	}

	public KieuLoaiHinhBan(byte maKlhb, String tenKlhb, String moTa, Set<LoaiHinhBan> loaiHinhBans) {
		this.maKlhb = maKlhb;
		this.tenKlhb = tenKlhb;
		this.moTa = moTa;
		this.loaiHinhBans = loaiHinhBans;
	}

	@Id

	@Column(name = "Ma_KLHB", unique = true, nullable = false)
	public byte getMaKlhb() {
		return this.maKlhb;
	}

	public void setMaKlhb(byte maKlhb) {
		this.maKlhb = maKlhb;
	}

	@Column(name = "Ten_KLHB", length = 62)
	public String getTenKlhb() {
		return this.tenKlhb;
	}

	public void setTenKlhb(String tenKlhb) {
		this.tenKlhb = tenKlhb;
	}

	@Column(name = "Mo_Ta", length = 254)
	public String getMoTa() {
		return this.moTa;
	}

	public void setMoTa(String moTa) {
		this.moTa = moTa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kieuLoaiHinhBan")
	public Set<LoaiHinhBan> getLoaiHinhBans() {
		return this.loaiHinhBans;
	}

	public void setLoaiHinhBans(Set<LoaiHinhBan> loaiHinhBans) {
		this.loaiHinhBans = loaiHinhBans;
	}

}
