package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * KqXetThiDua generated by hbm2java
 */
@Entity
@Table(name = "kq_xet_thi_dua", catalog = "qlcb")
public class KqXetThiDua implements java.io.Serializable {

	private Integer maDsKhenThuong;
	private short namDanhGia;
	private short quyDanhGia;
	private Date thoiDiemXet;
	private Set<MucThuongTheoDien> mucThuongTheoDiens = new HashSet<MucThuongTheoDien>(0);
	private Set<KhenThuong> khenThuongs = new HashSet<KhenThuong>(0);

	public KqXetThiDua() {
	}

	public KqXetThiDua(short namDanhGia, short quyDanhGia) {
		this.namDanhGia = namDanhGia;
		this.quyDanhGia = quyDanhGia;
	}

	public KqXetThiDua(short namDanhGia, short quyDanhGia, Date thoiDiemXet, Set<MucThuongTheoDien> mucThuongTheoDiens,
			Set<KhenThuong> khenThuongs) {
		this.namDanhGia = namDanhGia;
		this.quyDanhGia = quyDanhGia;
		this.thoiDiemXet = thoiDiemXet;
		this.mucThuongTheoDiens = mucThuongTheoDiens;
		this.khenThuongs = khenThuongs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Ma_DS_Khen_Thuong", unique = true, nullable = false)
	public Integer getMaDsKhenThuong() {
		return this.maDsKhenThuong;
	}

	public void setMaDsKhenThuong(Integer maDsKhenThuong) {
		this.maDsKhenThuong = maDsKhenThuong;
	}

	@Column(name = "Nam_Danh_Gia", nullable = false)
	public short getNamDanhGia() {
		return this.namDanhGia;
	}

	public void setNamDanhGia(short namDanhGia) {
		this.namDanhGia = namDanhGia;
	}

	@Column(name = "Quy_Danh_Gia", nullable = false)
	public short getQuyDanhGia() {
		return this.quyDanhGia;
	}

	public void setQuyDanhGia(short quyDanhGia) {
		this.quyDanhGia = quyDanhGia;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Thoi_Diem_Xet", length = 10)
	public Date getThoiDiemXet() {
		return this.thoiDiemXet;
	}

	public void setThoiDiemXet(Date thoiDiemXet) {
		this.thoiDiemXet = thoiDiemXet;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kqXetThiDua")
	public Set<MucThuongTheoDien> getMucThuongTheoDiens() {
		return this.mucThuongTheoDiens;
	}

	public void setMucThuongTheoDiens(Set<MucThuongTheoDien> mucThuongTheoDiens) {
		this.mucThuongTheoDiens = mucThuongTheoDiens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kqXetThiDua")
	public Set<KhenThuong> getKhenThuongs() {
		return this.khenThuongs;
	}

	public void setKhenThuongs(Set<KhenThuong> khenThuongs) {
		this.khenThuongs = khenThuongs;
	}

}
