package com.springmvc.qlcb.model;
// Generated Apr 23, 2016 3:25:20 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Kyluat generated by hbm2java
 */
@Entity
@Table(name = "kyluat", catalog = "qlcb")
public class Kyluat implements java.io.Serializable {

	private int maKyLuat;
	private Canbo canbo;
	private Date ngayKyLuat;
	private String noiDung;
	private String lyDo;
	private String hinhThucKyLuat;
	private Integer nguoiXacNhanKyLuat;
	private boolean daXacNhan;

	public Kyluat() {
	}

	public Kyluat(int maKyLuat, Canbo canbo, Date ngayKyLuat, String hinhThucKyLuat, boolean daXacNhan) {
		this.maKyLuat = maKyLuat;
		this.canbo = canbo;
		this.ngayKyLuat = ngayKyLuat;
		this.hinhThucKyLuat = hinhThucKyLuat;
		this.daXacNhan = daXacNhan;
	}

	public Kyluat(int maKyLuat, Canbo canbo, Date ngayKyLuat, String noiDung, String lyDo, String hinhThucKyLuat,
			Integer nguoiXacNhanKyLuat, boolean daXacNhan) {
		this.maKyLuat = maKyLuat;
		this.canbo = canbo;
		this.ngayKyLuat = ngayKyLuat;
		this.noiDung = noiDung;
		this.lyDo = lyDo;
		this.hinhThucKyLuat = hinhThucKyLuat;
		this.nguoiXacNhanKyLuat = nguoiXacNhanKyLuat;
		this.daXacNhan = daXacNhan;
	}

	@Id

	@Column(name = "MaKyLuat", unique = true, nullable = false)
	public int getMaKyLuat() {
		return this.maKyLuat;
	}

	public void setMaKyLuat(int maKyLuat) {
		this.maKyLuat = maKyLuat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaCanBo", nullable = false)
	public Canbo getCanbo() {
		return this.canbo;
	}

	public void setCanbo(Canbo canbo) {
		this.canbo = canbo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NgayKyLuat", nullable = false, length = 10)
	public Date getNgayKyLuat() {
		return this.ngayKyLuat;
	}

	public void setNgayKyLuat(Date ngayKyLuat) {
		this.ngayKyLuat = ngayKyLuat;
	}

	@Column(name = "NoiDung", length = 65535)
	public String getNoiDung() {
		return this.noiDung;
	}

	public void setNoiDung(String noiDung) {
		this.noiDung = noiDung;
	}

	@Column(name = "LyDo", length = 65535)
	public String getLyDo() {
		return this.lyDo;
	}

	public void setLyDo(String lyDo) {
		this.lyDo = lyDo;
	}

	@Column(name = "HinhThucKyLuat", nullable = false, length = 65535)
	public String getHinhThucKyLuat() {
		return this.hinhThucKyLuat;
	}

	public void setHinhThucKyLuat(String hinhThucKyLuat) {
		this.hinhThucKyLuat = hinhThucKyLuat;
	}

	@Column(name = "NguoiXacNhanKyLuat")
	public Integer getNguoiXacNhanKyLuat() {
		return this.nguoiXacNhanKyLuat;
	}

	public void setNguoiXacNhanKyLuat(Integer nguoiXacNhanKyLuat) {
		this.nguoiXacNhanKyLuat = nguoiXacNhanKyLuat;
	}

	@Column(name = "DaXacNhan", nullable = false)
	public boolean isDaXacNhan() {
		return this.daXacNhan;
	}

	public void setDaXacNhan(boolean daXacNhan) {
		this.daXacNhan = daXacNhan;
	}

}
