package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * KyLuatId generated by hbm2java
 */
@Embeddable
public class KyLuatId implements java.io.Serializable {

	private long maKyLuat;
	private int maCb;

	public KyLuatId() {
	}

	public KyLuatId(long maKyLuat, int maCb) {
		this.maKyLuat = maKyLuat;
		this.maCb = maCb;
	}

	@Column(name = "Ma_Ky_Luat", nullable = false)
	public long getMaKyLuat() {
		return this.maKyLuat;
	}

	public void setMaKyLuat(long maKyLuat) {
		this.maKyLuat = maKyLuat;
	}

	@Column(name = "Ma_CB", nullable = false)
	public int getMaCb() {
		return this.maCb;
	}

	public void setMaCb(int maCb) {
		this.maCb = maCb;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof KyLuatId))
			return false;
		KyLuatId castOther = (KyLuatId) other;

		return (this.getMaKyLuat() == castOther.getMaKyLuat()) && (this.getMaCb() == castOther.getMaCb());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getMaKyLuat();
		result = 37 * result + this.getMaCb();
		return result;
	}

}
