package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * KyLuat generated by hbm2java
 */
@Entity
@Table(name = "ky_luat", catalog = "qlcb")
public class KyLuat implements java.io.Serializable {

	private KyLuatId id;
	private CanBo canBo;
	private Date ngayQuyetDinh;
	private String hinhThuc;
	private String capRaQuyetDinh;
	private String lyDoKyLuat;

	public KyLuat() {
	}

	public KyLuat(KyLuatId id, CanBo canBo) {
		this.id = id;
		this.canBo = canBo;
	}

	public KyLuat(KyLuatId id, CanBo canBo, Date ngayQuyetDinh, String hinhThuc, String capRaQuyetDinh,
			String lyDoKyLuat) {
		this.id = id;
		this.canBo = canBo;
		this.ngayQuyetDinh = ngayQuyetDinh;
		this.hinhThuc = hinhThuc;
		this.capRaQuyetDinh = capRaQuyetDinh;
		this.lyDoKyLuat = lyDoKyLuat;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "maKyLuat", column = @Column(name = "Ma_Ky_Luat", nullable = false)),
			@AttributeOverride(name = "maCb", column = @Column(name = "Ma_CB", nullable = false)) })
	public KyLuatId getId() {
		return this.id;
	}

	public void setId(KyLuatId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ma_CB", nullable = false, insertable = false, updatable = false)
	public CanBo getCanBo() {
		return this.canBo;
	}

	public void setCanBo(CanBo canBo) {
		this.canBo = canBo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Ngay_Quyet_Dinh", length = 10)
	public Date getNgayQuyetDinh() {
		return this.ngayQuyetDinh;
	}

	public void setNgayQuyetDinh(Date ngayQuyetDinh) {
		this.ngayQuyetDinh = ngayQuyetDinh;
	}

	@Column(name = "Hinh_Thuc", length = 62)
	public String getHinhThuc() {
		return this.hinhThuc;
	}

	public void setHinhThuc(String hinhThuc) {
		this.hinhThuc = hinhThuc;
	}

	@Column(name = "Cap_Ra_Quyet_Dinh", length = 62)
	public String getCapRaQuyetDinh() {
		return this.capRaQuyetDinh;
	}

	public void setCapRaQuyetDinh(String capRaQuyetDinh) {
		this.capRaQuyetDinh = capRaQuyetDinh;
	}

	@Column(name = "Ly_Do_Ky_Luat", length = 254)
	public String getLyDoKyLuat() {
		return this.lyDoKyLuat;
	}

	public void setLyDoKyLuat(String lyDoKyLuat) {
		this.lyDoKyLuat = lyDoKyLuat;
	}

}
