package com.springmvc.qlcb.model;
// Generated Apr 19, 2016 9:35:55 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Loaiquanhe generated by hbm2java
 */
@Entity
@Table(name = "loaiquanhe", catalog = "qlcb_new")
public class Loaiquanhe implements java.io.Serializable {

	private int id;
	private String tenLoaiQuanHe;
	private Set<Thanhviengiadinh> thanhviengiadinhs = new HashSet<Thanhviengiadinh>(0);

	public Loaiquanhe() {
	}

	public Loaiquanhe(int id, String tenLoaiQuanHe) {
		this.id = id;
		this.tenLoaiQuanHe = tenLoaiQuanHe;
	}

	public Loaiquanhe(int id, String tenLoaiQuanHe, Set<Thanhviengiadinh> thanhviengiadinhs) {
		this.id = id;
		this.tenLoaiQuanHe = tenLoaiQuanHe;
		this.thanhviengiadinhs = thanhviengiadinhs;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "TenLoaiQuanHe", nullable = false, length = 200)
	public String getTenLoaiQuanHe() {
		return this.tenLoaiQuanHe;
	}

	public void setTenLoaiQuanHe(String tenLoaiQuanHe) {
		this.tenLoaiQuanHe = tenLoaiQuanHe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loaiquanhe")
	public Set<Thanhviengiadinh> getThanhviengiadinhs() {
		return this.thanhviengiadinhs;
	}

	public void setThanhviengiadinhs(Set<Thanhviengiadinh> thanhviengiadinhs) {
		this.thanhviengiadinhs = thanhviengiadinhs;
	}

}
