package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * LyLich generated by hbm2java
 */
@Entity
@Table(name = "ly_lich", catalog = "qlcb")
public class LyLich implements java.io.Serializable {

	private int maCb;
	private CanBo canBo;
	private DanToc danToc;
	private TonGiao tonGiao;
	private TrinhDoChuyenMon trinhDoChuyenMon;
	private TrinhDoLyLuanChinhTri trinhDoLyLuanChinhTri;
	private String soHieuCb;
	private String hoTenKhaiSinh;
	private String tenGoiKhac;
	private Boolean gioiTinh;
	private String capUyHienTai;
	private String capUyKiem;
	private String chucDanh;
	private Float phuCapChucVu;
	private Date ngaySinh;
	private String noiSinh;
	private String soCmnd;
	private Date ngayCapCmnd;
	private String noiCapCmnd;
	private String queQuan;
	private String noiOHienNay;
	private String dienThoai;
	private String thanhPhanGiaDinhXuatThan;
	private Date ngayThamGiaCm;
	private String ngheNghiepTruocDo;
	private Date ngayDuocTuyenDung;
	private String coQuanTuyenDung;
	private String diaChiCoQuanTuyenDung;
	private Date ngayVaoDang;
	private Date ngayChinhThuc;
	private String ngayThamGiaCacToChucChinhTriXaHoi;
	private Date ngayNhapNgu;
	private Date ngayXuatNgu;
	private String quanHamChucVuCaoNhat;
	private String trinhDoHocVan;
	private String hocHam;
	private String chuyenNganh;
	private String ngoaiNgu;
	private String dacDiemLichSu;
	private String lamViecTrongCheDoCu;
	private String coThanNhanNuocNgoai;
	private String thamGiaCacToChucNuocNgoai;
	private String congTacChinhDangLam;
	private String danhHieuDuocPhong;
	private String soTruongCongTac;
	private String congViecLamLauNhat;
	private String khenThuong;
	private String kyLuat;
	private String tinhTrangSucKhoe;
	private Float chieuCao;
	private Float canNang;
	private String nhomMau;
	private String loaiThuongBinh;
	private Boolean giaDinhLietSy;
	private Long luongThuNhapNam;
	private String nguonThuKhac;
	private String loaiNhaDuocCap;
	private Integer dienTichNhaDuocCap;
	private String loaiNhaTuXay;
	private Integer dienTichNhaTuXay;
	private Integer dienTichDatODuocCap;
	private Integer dienTichDatOTuMua;
	private Integer dienTichDatSanXuat;

	public LyLich() {
	}

	public LyLich(CanBo canBo) {
		this.canBo = canBo;
	}

	public LyLich(CanBo canBo, DanToc danToc, TonGiao tonGiao, TrinhDoChuyenMon trinhDoChuyenMon,
			TrinhDoLyLuanChinhTri trinhDoLyLuanChinhTri, String soHieuCb, String hoTenKhaiSinh, String tenGoiKhac,
			Boolean gioiTinh, String capUyHienTai, String capUyKiem, String chucDanh, Float phuCapChucVu, Date ngaySinh,
			String noiSinh, String soCmnd, Date ngayCapCmnd, String noiCapCmnd, String queQuan, String noiOHienNay,
			String dienThoai, String thanhPhanGiaDinhXuatThan, Date ngayThamGiaCm, String ngheNghiepTruocDo,
			Date ngayDuocTuyenDung, String coQuanTuyenDung, String diaChiCoQuanTuyenDung, Date ngayVaoDang,
			Date ngayChinhThuc, String ngayThamGiaCacToChucChinhTriXaHoi, Date ngayNhapNgu, Date ngayXuatNgu,
			String quanHamChucVuCaoNhat, String trinhDoHocVan, String hocHam, String chuyenNganh, String ngoaiNgu,
			String dacDiemLichSu, String lamViecTrongCheDoCu, String coThanNhanNuocNgoai,
			String thamGiaCacToChucNuocNgoai, String congTacChinhDangLam, String danhHieuDuocPhong,
			String soTruongCongTac, String congViecLamLauNhat, String khenThuong, String kyLuat,
			String tinhTrangSucKhoe, Float chieuCao, Float canNang, String nhomMau, String loaiThuongBinh,
			Boolean giaDinhLietSy, Long luongThuNhapNam, String nguonThuKhac, String loaiNhaDuocCap,
			Integer dienTichNhaDuocCap, String loaiNhaTuXay, Integer dienTichNhaTuXay, Integer dienTichDatODuocCap,
			Integer dienTichDatOTuMua, Integer dienTichDatSanXuat) {
		this.canBo = canBo;
		this.danToc = danToc;
		this.tonGiao = tonGiao;
		this.trinhDoChuyenMon = trinhDoChuyenMon;
		this.trinhDoLyLuanChinhTri = trinhDoLyLuanChinhTri;
		this.soHieuCb = soHieuCb;
		this.hoTenKhaiSinh = hoTenKhaiSinh;
		this.tenGoiKhac = tenGoiKhac;
		this.gioiTinh = gioiTinh;
		this.capUyHienTai = capUyHienTai;
		this.capUyKiem = capUyKiem;
		this.chucDanh = chucDanh;
		this.phuCapChucVu = phuCapChucVu;
		this.ngaySinh = ngaySinh;
		this.noiSinh = noiSinh;
		this.soCmnd = soCmnd;
		this.ngayCapCmnd = ngayCapCmnd;
		this.noiCapCmnd = noiCapCmnd;
		this.queQuan = queQuan;
		this.noiOHienNay = noiOHienNay;
		this.dienThoai = dienThoai;
		this.thanhPhanGiaDinhXuatThan = thanhPhanGiaDinhXuatThan;
		this.ngayThamGiaCm = ngayThamGiaCm;
		this.ngheNghiepTruocDo = ngheNghiepTruocDo;
		this.ngayDuocTuyenDung = ngayDuocTuyenDung;
		this.coQuanTuyenDung = coQuanTuyenDung;
		this.diaChiCoQuanTuyenDung = diaChiCoQuanTuyenDung;
		this.ngayVaoDang = ngayVaoDang;
		this.ngayChinhThuc = ngayChinhThuc;
		this.ngayThamGiaCacToChucChinhTriXaHoi = ngayThamGiaCacToChucChinhTriXaHoi;
		this.ngayNhapNgu = ngayNhapNgu;
		this.ngayXuatNgu = ngayXuatNgu;
		this.quanHamChucVuCaoNhat = quanHamChucVuCaoNhat;
		this.trinhDoHocVan = trinhDoHocVan;
		this.hocHam = hocHam;
		this.chuyenNganh = chuyenNganh;
		this.ngoaiNgu = ngoaiNgu;
		this.dacDiemLichSu = dacDiemLichSu;
		this.lamViecTrongCheDoCu = lamViecTrongCheDoCu;
		this.coThanNhanNuocNgoai = coThanNhanNuocNgoai;
		this.thamGiaCacToChucNuocNgoai = thamGiaCacToChucNuocNgoai;
		this.congTacChinhDangLam = congTacChinhDangLam;
		this.danhHieuDuocPhong = danhHieuDuocPhong;
		this.soTruongCongTac = soTruongCongTac;
		this.congViecLamLauNhat = congViecLamLauNhat;
		this.khenThuong = khenThuong;
		this.kyLuat = kyLuat;
		this.tinhTrangSucKhoe = tinhTrangSucKhoe;
		this.chieuCao = chieuCao;
		this.canNang = canNang;
		this.nhomMau = nhomMau;
		this.loaiThuongBinh = loaiThuongBinh;
		this.giaDinhLietSy = giaDinhLietSy;
		this.luongThuNhapNam = luongThuNhapNam;
		this.nguonThuKhac = nguonThuKhac;
		this.loaiNhaDuocCap = loaiNhaDuocCap;
		this.dienTichNhaDuocCap = dienTichNhaDuocCap;
		this.loaiNhaTuXay = loaiNhaTuXay;
		this.dienTichNhaTuXay = dienTichNhaTuXay;
		this.dienTichDatODuocCap = dienTichDatODuocCap;
		this.dienTichDatOTuMua = dienTichDatOTuMua;
		this.dienTichDatSanXuat = dienTichDatSanXuat;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "canBo"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "Ma_CB", unique = true, nullable = false)
	public int getMaCb() {
		return this.maCb;
	}

	public void setMaCb(int maCb) {
		this.maCb = maCb;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public CanBo getCanBo() {
		return this.canBo;
	}

	public void setCanBo(CanBo canBo) {
		this.canBo = canBo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Dan_Toc")
	public DanToc getDanToc() {
		return this.danToc;
	}

	public void setDanToc(DanToc danToc) {
		this.danToc = danToc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ton_Giao")
	public TonGiao getTonGiao() {
		return this.tonGiao;
	}

	public void setTonGiao(TonGiao tonGiao) {
		this.tonGiao = tonGiao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Cap_Do_TDCM")
	public TrinhDoChuyenMon getTrinhDoChuyenMon() {
		return this.trinhDoChuyenMon;
	}

	public void setTrinhDoChuyenMon(TrinhDoChuyenMon trinhDoChuyenMon) {
		this.trinhDoChuyenMon = trinhDoChuyenMon;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Cap_Do_CTLL")
	public TrinhDoLyLuanChinhTri getTrinhDoLyLuanChinhTri() {
		return this.trinhDoLyLuanChinhTri;
	}

	public void setTrinhDoLyLuanChinhTri(TrinhDoLyLuanChinhTri trinhDoLyLuanChinhTri) {
		this.trinhDoLyLuanChinhTri = trinhDoLyLuanChinhTri;
	}

	@Column(name = "So_Hieu_CB", length = 30)
	public String getSoHieuCb() {
		return this.soHieuCb;
	}

	public void setSoHieuCb(String soHieuCb) {
		this.soHieuCb = soHieuCb;
	}

	@Column(name = "Ho_Ten_Khai_Sinh", length = 254)
	public String getHoTenKhaiSinh() {
		return this.hoTenKhaiSinh;
	}

	public void setHoTenKhaiSinh(String hoTenKhaiSinh) {
		this.hoTenKhaiSinh = hoTenKhaiSinh;
	}

	@Column(name = "Ten_Goi_Khac", length = 254)
	public String getTenGoiKhac() {
		return this.tenGoiKhac;
	}

	public void setTenGoiKhac(String tenGoiKhac) {
		this.tenGoiKhac = tenGoiKhac;
	}

	@Column(name = "Gioi_Tinh")
	public Boolean getGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(Boolean gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	@Column(name = "Cap_Uy_Hien_Tai", length = 254)
	public String getCapUyHienTai() {
		return this.capUyHienTai;
	}

	public void setCapUyHienTai(String capUyHienTai) {
		this.capUyHienTai = capUyHienTai;
	}

	@Column(name = "Cap_Uy_Kiem", length = 254)
	public String getCapUyKiem() {
		return this.capUyKiem;
	}

	public void setCapUyKiem(String capUyKiem) {
		this.capUyKiem = capUyKiem;
	}

	@Column(name = "Chuc_Danh", length = 62)
	public String getChucDanh() {
		return this.chucDanh;
	}

	public void setChucDanh(String chucDanh) {
		this.chucDanh = chucDanh;
	}

	@Column(name = "Phu_Cap_Chuc_Vu", precision = 12, scale = 0)
	public Float getPhuCapChucVu() {
		return this.phuCapChucVu;
	}

	public void setPhuCapChucVu(Float phuCapChucVu) {
		this.phuCapChucVu = phuCapChucVu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Ngay_Sinh", length = 10)
	public Date getNgaySinh() {
		return this.ngaySinh;
	}

	public void setNgaySinh(Date ngaySinh) {
		this.ngaySinh = ngaySinh;
	}

	@Column(name = "Noi_Sinh", length = 254)
	public String getNoiSinh() {
		return this.noiSinh;
	}

	public void setNoiSinh(String noiSinh) {
		this.noiSinh = noiSinh;
	}

	@Column(name = "So_CMND", length = 254)
	public String getSoCmnd() {
		return this.soCmnd;
	}

	public void setSoCmnd(String soCmnd) {
		this.soCmnd = soCmnd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Ngay_Cap_CMND", length = 10)
	public Date getNgayCapCmnd() {
		return this.ngayCapCmnd;
	}

	public void setNgayCapCmnd(Date ngayCapCmnd) {
		this.ngayCapCmnd = ngayCapCmnd;
	}

	@Column(name = "Noi_Cap_CMND", length = 254)
	public String getNoiCapCmnd() {
		return this.noiCapCmnd;
	}

	public void setNoiCapCmnd(String noiCapCmnd) {
		this.noiCapCmnd = noiCapCmnd;
	}

	@Column(name = "Que_Quan", length = 254)
	public String getQueQuan() {
		return this.queQuan;
	}

	public void setQueQuan(String queQuan) {
		this.queQuan = queQuan;
	}

	@Column(name = "Noi_O_Hien_Nay", length = 254)
	public String getNoiOHienNay() {
		return this.noiOHienNay;
	}

	public void setNoiOHienNay(String noiOHienNay) {
		this.noiOHienNay = noiOHienNay;
	}

	@Column(name = "Dien_Thoai", length = 254)
	public String getDienThoai() {
		return this.dienThoai;
	}

	public void setDienThoai(String dienThoai) {
		this.dienThoai = dienThoai;
	}

	@Column(name = "Thanh_Phan_Gia_Dinh_Xuat_Than", length = 254)
	public String getThanhPhanGiaDinhXuatThan() {
		return this.thanhPhanGiaDinhXuatThan;
	}

	public void setThanhPhanGiaDinhXuatThan(String thanhPhanGiaDinhXuatThan) {
		this.thanhPhanGiaDinhXuatThan = thanhPhanGiaDinhXuatThan;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Ngay_Tham_Gia_CM", length = 10)
	public Date getNgayThamGiaCm() {
		return this.ngayThamGiaCm;
	}

	public void setNgayThamGiaCm(Date ngayThamGiaCm) {
		this.ngayThamGiaCm = ngayThamGiaCm;
	}

	@Column(name = "Nghe_Nghiep_Truoc_Do", length = 254)
	public String getNgheNghiepTruocDo() {
		return this.ngheNghiepTruocDo;
	}

	public void setNgheNghiepTruocDo(String ngheNghiepTruocDo) {
		this.ngheNghiepTruocDo = ngheNghiepTruocDo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Ngay_Duoc_Tuyen_Dung", length = 10)
	public Date getNgayDuocTuyenDung() {
		return this.ngayDuocTuyenDung;
	}

	public void setNgayDuocTuyenDung(Date ngayDuocTuyenDung) {
		this.ngayDuocTuyenDung = ngayDuocTuyenDung;
	}

	@Column(name = "Co_Quan_Tuyen_Dung", length = 254)
	public String getCoQuanTuyenDung() {
		return this.coQuanTuyenDung;
	}

	public void setCoQuanTuyenDung(String coQuanTuyenDung) {
		this.coQuanTuyenDung = coQuanTuyenDung;
	}

	@Column(name = "Dia_Chi_Co_Quan_Tuyen_Dung", length = 254)
	public String getDiaChiCoQuanTuyenDung() {
		return this.diaChiCoQuanTuyenDung;
	}

	public void setDiaChiCoQuanTuyenDung(String diaChiCoQuanTuyenDung) {
		this.diaChiCoQuanTuyenDung = diaChiCoQuanTuyenDung;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Ngay_Vao_Dang", length = 10)
	public Date getNgayVaoDang() {
		return this.ngayVaoDang;
	}

	public void setNgayVaoDang(Date ngayVaoDang) {
		this.ngayVaoDang = ngayVaoDang;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Ngay_Chinh_Thuc", length = 10)
	public Date getNgayChinhThuc() {
		return this.ngayChinhThuc;
	}

	public void setNgayChinhThuc(Date ngayChinhThuc) {
		this.ngayChinhThuc = ngayChinhThuc;
	}

	@Column(name = "Ngay_Tham_Gia_Cac_To_Chuc_Chinh_Tri_Xa_Hoi", length = 254)
	public String getNgayThamGiaCacToChucChinhTriXaHoi() {
		return this.ngayThamGiaCacToChucChinhTriXaHoi;
	}

	public void setNgayThamGiaCacToChucChinhTriXaHoi(String ngayThamGiaCacToChucChinhTriXaHoi) {
		this.ngayThamGiaCacToChucChinhTriXaHoi = ngayThamGiaCacToChucChinhTriXaHoi;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Ngay_Nhap_Ngu", length = 10)
	public Date getNgayNhapNgu() {
		return this.ngayNhapNgu;
	}

	public void setNgayNhapNgu(Date ngayNhapNgu) {
		this.ngayNhapNgu = ngayNhapNgu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Ngay_Xuat_Ngu", length = 10)
	public Date getNgayXuatNgu() {
		return this.ngayXuatNgu;
	}

	public void setNgayXuatNgu(Date ngayXuatNgu) {
		this.ngayXuatNgu = ngayXuatNgu;
	}

	@Column(name = "Quan_Ham_Chuc_Vu_Cao_Nhat", length = 254)
	public String getQuanHamChucVuCaoNhat() {
		return this.quanHamChucVuCaoNhat;
	}

	public void setQuanHamChucVuCaoNhat(String quanHamChucVuCaoNhat) {
		this.quanHamChucVuCaoNhat = quanHamChucVuCaoNhat;
	}

	@Column(name = "Trinh_Do_Hoc_Van", length = 254)
	public String getTrinhDoHocVan() {
		return this.trinhDoHocVan;
	}

	public void setTrinhDoHocVan(String trinhDoHocVan) {
		this.trinhDoHocVan = trinhDoHocVan;
	}

	@Column(name = "Hoc_Ham", length = 254)
	public String getHocHam() {
		return this.hocHam;
	}

	public void setHocHam(String hocHam) {
		this.hocHam = hocHam;
	}

	@Column(name = "Chuyen_Nganh", length = 62)
	public String getChuyenNganh() {
		return this.chuyenNganh;
	}

	public void setChuyenNganh(String chuyenNganh) {
		this.chuyenNganh = chuyenNganh;
	}

	@Column(name = "Ngoai_Ngu", length = 254)
	public String getNgoaiNgu() {
		return this.ngoaiNgu;
	}

	public void setNgoaiNgu(String ngoaiNgu) {
		this.ngoaiNgu = ngoaiNgu;
	}

	@Column(name = "Dac_Diem_Lich_Su", length = 65535)
	public String getDacDiemLichSu() {
		return this.dacDiemLichSu;
	}

	public void setDacDiemLichSu(String dacDiemLichSu) {
		this.dacDiemLichSu = dacDiemLichSu;
	}

	@Column(name = "Lam_Viec_Trong_Che_Do_Cu", length = 254)
	public String getLamViecTrongCheDoCu() {
		return this.lamViecTrongCheDoCu;
	}

	public void setLamViecTrongCheDoCu(String lamViecTrongCheDoCu) {
		this.lamViecTrongCheDoCu = lamViecTrongCheDoCu;
	}

	@Column(name = "Co_Than_Nhan_Nuoc_Ngoai", length = 254)
	public String getCoThanNhanNuocNgoai() {
		return this.coThanNhanNuocNgoai;
	}

	public void setCoThanNhanNuocNgoai(String coThanNhanNuocNgoai) {
		this.coThanNhanNuocNgoai = coThanNhanNuocNgoai;
	}

	@Column(name = "Tham_Gia_Cac_To_Chuc_Nuoc_Ngoai", length = 254)
	public String getThamGiaCacToChucNuocNgoai() {
		return this.thamGiaCacToChucNuocNgoai;
	}

	public void setThamGiaCacToChucNuocNgoai(String thamGiaCacToChucNuocNgoai) {
		this.thamGiaCacToChucNuocNgoai = thamGiaCacToChucNuocNgoai;
	}

	@Column(name = "Cong_Tac_Chinh_Dang_Lam", length = 254)
	public String getCongTacChinhDangLam() {
		return this.congTacChinhDangLam;
	}

	public void setCongTacChinhDangLam(String congTacChinhDangLam) {
		this.congTacChinhDangLam = congTacChinhDangLam;
	}

	@Column(name = "Danh_Hieu_Duoc_Phong", length = 254)
	public String getDanhHieuDuocPhong() {
		return this.danhHieuDuocPhong;
	}

	public void setDanhHieuDuocPhong(String danhHieuDuocPhong) {
		this.danhHieuDuocPhong = danhHieuDuocPhong;
	}

	@Column(name = "So_Truong_Cong_Tac", length = 254)
	public String getSoTruongCongTac() {
		return this.soTruongCongTac;
	}

	public void setSoTruongCongTac(String soTruongCongTac) {
		this.soTruongCongTac = soTruongCongTac;
	}

	@Column(name = "Cong_Viec_Lam_Lau_Nhat", length = 254)
	public String getCongViecLamLauNhat() {
		return this.congViecLamLauNhat;
	}

	public void setCongViecLamLauNhat(String congViecLamLauNhat) {
		this.congViecLamLauNhat = congViecLamLauNhat;
	}

	@Column(name = "Khen_Thuong", length = 254)
	public String getKhenThuong() {
		return this.khenThuong;
	}

	public void setKhenThuong(String khenThuong) {
		this.khenThuong = khenThuong;
	}

	@Column(name = "Ky_Luat", length = 254)
	public String getKyLuat() {
		return this.kyLuat;
	}

	public void setKyLuat(String kyLuat) {
		this.kyLuat = kyLuat;
	}

	@Column(name = "Tinh_Trang_Suc_Khoe", length = 254)
	public String getTinhTrangSucKhoe() {
		return this.tinhTrangSucKhoe;
	}

	public void setTinhTrangSucKhoe(String tinhTrangSucKhoe) {
		this.tinhTrangSucKhoe = tinhTrangSucKhoe;
	}

	@Column(name = "Chieu_Cao", precision = 12, scale = 0)
	public Float getChieuCao() {
		return this.chieuCao;
	}

	public void setChieuCao(Float chieuCao) {
		this.chieuCao = chieuCao;
	}

	@Column(name = "Can_Nang", precision = 12, scale = 0)
	public Float getCanNang() {
		return this.canNang;
	}

	public void setCanNang(Float canNang) {
		this.canNang = canNang;
	}

	@Column(name = "Nhom_Mau", length = 30)
	public String getNhomMau() {
		return this.nhomMau;
	}

	public void setNhomMau(String nhomMau) {
		this.nhomMau = nhomMau;
	}

	@Column(name = "Loai_Thuong_Binh", length = 254)
	public String getLoaiThuongBinh() {
		return this.loaiThuongBinh;
	}

	public void setLoaiThuongBinh(String loaiThuongBinh) {
		this.loaiThuongBinh = loaiThuongBinh;
	}

	@Column(name = "Gia_Dinh_Liet_Sy")
	public Boolean getGiaDinhLietSy() {
		return this.giaDinhLietSy;
	}

	public void setGiaDinhLietSy(Boolean giaDinhLietSy) {
		this.giaDinhLietSy = giaDinhLietSy;
	}

	@Column(name = "Luong_Thu_Nhap_Nam")
	public Long getLuongThuNhapNam() {
		return this.luongThuNhapNam;
	}

	public void setLuongThuNhapNam(Long luongThuNhapNam) {
		this.luongThuNhapNam = luongThuNhapNam;
	}

	@Column(name = "Nguon_Thu_Khac", length = 254)
	public String getNguonThuKhac() {
		return this.nguonThuKhac;
	}

	public void setNguonThuKhac(String nguonThuKhac) {
		this.nguonThuKhac = nguonThuKhac;
	}

	@Column(name = "Loai_Nha_Duoc_Cap", length = 62)
	public String getLoaiNhaDuocCap() {
		return this.loaiNhaDuocCap;
	}

	public void setLoaiNhaDuocCap(String loaiNhaDuocCap) {
		this.loaiNhaDuocCap = loaiNhaDuocCap;
	}

	@Column(name = "Dien_Tich_Nha_Duoc_Cap")
	public Integer getDienTichNhaDuocCap() {
		return this.dienTichNhaDuocCap;
	}

	public void setDienTichNhaDuocCap(Integer dienTichNhaDuocCap) {
		this.dienTichNhaDuocCap = dienTichNhaDuocCap;
	}

	@Column(name = "Loai_Nha_Tu_Xay", length = 62)
	public String getLoaiNhaTuXay() {
		return this.loaiNhaTuXay;
	}

	public void setLoaiNhaTuXay(String loaiNhaTuXay) {
		this.loaiNhaTuXay = loaiNhaTuXay;
	}

	@Column(name = "Dien_Tich_Nha_Tu_Xay")
	public Integer getDienTichNhaTuXay() {
		return this.dienTichNhaTuXay;
	}

	public void setDienTichNhaTuXay(Integer dienTichNhaTuXay) {
		this.dienTichNhaTuXay = dienTichNhaTuXay;
	}

	@Column(name = "Dien_Tich_Dat_O_Duoc_Cap")
	public Integer getDienTichDatODuocCap() {
		return this.dienTichDatODuocCap;
	}

	public void setDienTichDatODuocCap(Integer dienTichDatODuocCap) {
		this.dienTichDatODuocCap = dienTichDatODuocCap;
	}

	@Column(name = "Dien_Tich_Dat_O_Tu_Mua")
	public Integer getDienTichDatOTuMua() {
		return this.dienTichDatOTuMua;
	}

	public void setDienTichDatOTuMua(Integer dienTichDatOTuMua) {
		this.dienTichDatOTuMua = dienTichDatOTuMua;
	}

	@Column(name = "Dien_Tich_Dat_San_Xuat")
	public Integer getDienTichDatSanXuat() {
		return this.dienTichDatSanXuat;
	}

	public void setDienTichDatSanXuat(Integer dienTichDatSanXuat) {
		this.dienTichDatSanXuat = dienTichDatSanXuat;
	}

}
