package com.springmvc.qlcb.model;
// Generated Apr 25, 2016 2:33:53 PM by Hibernate Tools 4.3.1.Final

import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.multipart.commons.CommonsMultipartFile;

/**
 * Lylich generated by hbm2java
 */
@Entity
@Table(name = "lylich", catalog = "qlcb")
public class Lylich implements java.io.Serializable {

	
	private int macanbo;
	private Canbo canboByNguoixacnhan;
	private Canbo canboByMaCanBo;
	private Dantoc dantoc;
	private Ngoaingu ngoaingu;
	private Tongiao tongiao;
	private Trinhdochinhtri trinhdochinhtri;
	private Trinhdochuyenmon trinhdochuyenmon;
	@Length(min=0, max=50, message="từ 0 tới 50 ký tự")
	private String tenGoiKhac;
	@Length(min=1, max=50, message="không để trống")
	private String tenCanBo;
	@Length(min=1, max=10, message="không để trống")
	private String ngaySinh;
	private Boolean gioiTinh;
	private String noiSinh;
	private String queQuan;
	private String hoKhauThuongTru;
	private String noiOhienNay;
	private String ngheNgiepKhiDuocTuyenDung;
	private String ngayTuyenDung;
	private String chucVuBenNgoaiHienTai;
	private String congViecChinhDuocGiao;
	private String ngachCongChuc;
	private Float maNgach;
	private Float bacLuong;
	private Float heSo;
	private String ngayHuong;
	private Double phuCapChucVu;
	private Double phuCapKhac;
	private String trinhDoPhoThong;
	private String quanLyNhaNuoc;
	private String tinHoc;
	private String ngayVaoDang;
	private String ngayChinhThuc;
	private String ngayThamGiaToChucChinhTri;
	private String ngayNhapNgu;
	private String ngayXuatNgu;
	private String quanHamCaoNhat;
	private String danhHieuPhongTangCaoNhat;
	private String soTruongCongTac;
	private String tinhTrangSucKhoe;
	private String coQuanTuyenDung; 
	private Float chieuCao;
	private Float canNang;
	private String nhomMau;
	private String laThuongBinhHang;
	private String laConGiaDinhChinhSach;
	private String soCmnd;
	private String ngayCap;
	private String soBhxh;
	private String nhanXetCapTren;
	private Boolean daXacNhan;
	private String hinhanh;
	@Length(min=1, max=50, message="không để trống")
	private String sohieucongchuc;
	private String soTruong;
	private String khenThuongCaoNhat;
	private String kyLuatCaoNhat;
	@Length(min=1, max=50, message="không để trống")
	private String noiSuDung;
	@Length(min=1, max=50, message="không để trống")
	private String noiQuanLy;
	private Dacdienlichsubanthan dacdienlichsubanthan;
	private Set<Dienbienluong> dienbienluongs = new HashSet<Dienbienluong>(0);
 
	//------------------------------------------ t? d?nh nghia, kh�ng mapping
	 @Transient  
	 private ArrayList<Lichsucongtac> lsct; 
	 @Transient 
	 private int loaicanbo;
	 @Transient
	 private String matkhauLTN;
	 @Transient  
	 private CommonsMultipartFile fileLTN; 
	 @Transient  
	 private ArrayList<Daotaochuyenmon> ldtcm;  
	 @Transient  
	 private ArrayList<Dienbienluong> ldbl;  
	 @Transient  
	 private ArrayList<CanboGiadinhBanthan> lqhbt; 
	 @Transient  
	 private ArrayList<CanboGiadinhDoitac> lqhdt; 
	 @Transient  
	 private String noisinh_tinh;  
	 @Transient  
	 private String noisinh_huyen;
	 @Transient  
	 private String noisinh_xa;
	 @Transient  
	 private String quequan_tinh;  
	 @Transient  
	 private String quequan_huyen;
	 @Transient  
	 private String quequan_xa; 
	 @Transient  
	 private String noiquanly;
	 
	 @Transient  
	 private String lngaySinh ;
	 @Transient  
	 private String lngayTuyenDung ;
	 @Transient  
	 private String lngayHuong ;
	 @Transient  
	 private String lngayVaoDang ;
	 @Transient  
	 private String lngayChinhThuc ;
	 @Transient  
	 private String lngayNhapNgu ;
	 @Transient  
	 private String lngayXuatNgu ;
	 @Transient  
	 private String lngayCap ;
	 @Transient  
	 private String lsoTruongCongTac ;
	 @Transient  
	 private String lkhenThuongCaoNhat ;
	 @Transient  
	 private String lkyLuatCaoNhat ;
	 
	@Transient
	public CommonsMultipartFile getFileLTN() {
		return fileLTN;
	}
	@Transient
	public void setFileLTN(CommonsMultipartFile fileLTN) {
		this.fileLTN = fileLTN;
	}
	@Transient
	public ArrayList<CanboGiadinhBanthan> getLqhbt() {
		return lqhbt;
	}
	 @Transient
	public void setLqhbt(ArrayList<CanboGiadinhBanthan> lqhbt) {
		this.lqhbt = lqhbt;
	}
	 @Transient
	public ArrayList<CanboGiadinhDoitac> getLqhdt() {
		return lqhdt;
	}
	 @Transient
	public void setLqhdt(ArrayList<CanboGiadinhDoitac> lqhdt) {
		this.lqhdt = lqhdt;
	}
	 @Transient
	public ArrayList<Dienbienluong> getLdbl() {
		return ldbl;
	}
	 @Transient
	public void setLdbl(ArrayList<Dienbienluong> ldbl) {
		this.ldbl = ldbl;
	}
	 @Transient
	 public String getMatkhauLTN() {
		return matkhauLTN;
	}
	 @Transient
	public void setMatkhauLTN(String matkhauLTN) {
		this.matkhauLTN = matkhauLTN;
	}
	@Transient
	public ArrayList<Daotaochuyenmon> getLdtcm() {
		return ldtcm;
	}
	 @Transient
	 public int getLoaicanbo() {
		return loaicanbo;
	}
	 @Transient
	public void setLoaicanbo(int loaicanbo) {
		this.loaicanbo = loaicanbo;
	}
	@Transient
	public void setLdtcm(ArrayList<Daotaochuyenmon> ldtcm) {
		this.ldtcm = ldtcm;
	}
	 @Transient
	public String getNoiquanly() {
		return noiquanly;
	}
	 @Transient
	public void setNoiquanly(String noiquanly) {
		this.noiquanly = noiquanly;
	}
	 
	 @Transient
	public Dacdienlichsubanthan getDacdienlichsubanthan() {
		return dacdienlichsubanthan;
	}
	 @Transient
	public void setDacdienlichsubanthan(Dacdienlichsubanthan lsbt) {
		this.dacdienlichsubanthan = lsbt;
	}
	 @Transient
	public ArrayList<Lichsucongtac> getLsct() {
		return lsct;
	}
	 @Transient
	public void setLsct(ArrayList<Lichsucongtac> lsct) {
		this.lsct = lsct;
	}
	 @Transient
	public String getNoisinh_tinh() {
		return noisinh_tinh;
	}
	 @Transient
	public void setNoisinh_tinh(String noisinh_tinh) {
		this.noisinh_tinh = noisinh_tinh;
	}
	 @Transient
	public String getNoisinh_huyen() {
		return noisinh_huyen;
	}
	 @Transient
	public void setNoisinh_huyen(String noisinh_huyen) {
		this.noisinh_huyen = noisinh_huyen;
	}
	 @Transient
	public String getNoisinh_xa() {
		return noisinh_xa;
	}
	 @Transient
	public void setNoisinh_xa(String noisinh_xa) {
		this.noisinh_xa = noisinh_xa;
	}
	 @Transient
	public String getQuequan_tinh() {
		return quequan_tinh;
	}
	 @Transient
	public void setQuequan_tinh(String quequan_tinh) {
		this.quequan_tinh = quequan_tinh;
	}
	 @Transient
	public String getQuequan_huyen() {
		return quequan_huyen;
	}
	 @Transient
	public void setQuequan_huyen(String quequan_huyen) {
		this.quequan_huyen = quequan_huyen;
	}
	 @Transient
	public String getQuequan_xa() {
		return quequan_xa;
	}
 
	 @Transient
	public void setQuequan_xa(String quequan_xa) {
		this.quequan_xa = quequan_xa;
	}
	 @Transient
	public String getLngaySinh() {
		return lngaySinh;
	}
	 @Transient
	public void setLngaySinh(String lngaySinh) {
		this.lngaySinh = lngaySinh;
	}
	 @Transient
	public String getLngayTuyenDung() {
		return lngayTuyenDung;
	}
	 @Transient
	public void setLngayTuyenDung(String lngayTuyenDung) {
		this.lngayTuyenDung = lngayTuyenDung;
	}
	 @Transient
	public String getLngayHuong() {
		return lngayHuong;
	}
	 @Transient
	public void setLngayHuong(String lngayHuong) {
		this.lngayHuong = lngayHuong;
	}
	 @Transient
	public String getLngayVaoDang() {
		return lngayVaoDang;
	}
	 @Transient
	public void setLngayVaoDang(String lngayVaoDang) {
		this.lngayVaoDang = lngayVaoDang;
	}
	 @Transient
	public String getLngayChinhThuc() {
		return lngayChinhThuc;
	}
	 @Transient
	public void setLngayChinhThuc(String lngayChinhThuc) {
		this.lngayChinhThuc = lngayChinhThuc;
	}
	 @Transient
	public String getLngayNhapNgu() {
		return lngayNhapNgu;
	}
	 @Transient
	public void setLngayNhapNgu(String lngayNhapNgu) {
		this.lngayNhapNgu = lngayNhapNgu;
	}
	 @Transient
	public String getLngayXuatNgu() {
		return lngayXuatNgu;
	}
	 @Transient
	public void setLngayXuatNgu(String lngayXuatNgu) {
		this.lngayXuatNgu = lngayXuatNgu;
	}
	 @Transient
	public String getLngayCap() {
		return lngayCap;
	}
	 @Transient
	public void setLngayCap(String lngayCap) {
		this.lngayCap = lngayCap;
	}
	 @Transient
	public String getLsoTruongCongTac() {
		return lsoTruongCongTac;
	}
	 @Transient
	public String getLkhenThuongCaoNhat() {
		return lkhenThuongCaoNhat;
	}
	 @Transient
	public void setLkhenThuongCaoNhat(String lkhenThuongCaoNhat) {
		this.lkhenThuongCaoNhat = lkhenThuongCaoNhat;
	}
	 @Transient
	public String getLkyLuatCaoNhat() {
		return lkyLuatCaoNhat;
	}
	 @Transient
	public void setLkyLuatCaoNhat(String lkyLuatCaoNhat) {
		this.lkyLuatCaoNhat = lkyLuatCaoNhat;
	}
	 @Transient
	public void setLsoTruongCongTac(String lsoTruongCongTac) {
		this.lsoTruongCongTac = lsoTruongCongTac;
	}
	
	

 
	//---------------------------------------------------------------------------
	public Lylich() {
	}

	public Lylich(Canbo canboByMaCanBo) {
		this.canboByMaCanBo = canboByMaCanBo;
	}

	public Lylich(Canbo canboByNguoixacnhan, Canbo canboByMaCanBo, Dantoc dantoc, Ngoaingu ngoaingu, Tongiao tongiao,
			Trinhdochinhtri trinhdochinhtri, Trinhdochuyenmon trinhdochuyenmon, String tenGoiKhac, String tenCanBo,
			String ngaySinh, Boolean gioiTinh, String noiSinh, String queQuan, String hoKhauThuongTru, String noiOhienNay,
			String ngheNgiepKhiDuocTuyenDung, String ngayTuyenDung, String chucVuBenNgoaiHienTai,
			String congViecChinhDuocGiao, String ngachCongChuc, Float maNgach, Float bacLuong, Float heSo,
			String ngayHuong, Double phuCapChucVu, Double phuCapKhac, String trinhDoPhoThong, String quanLyNhaNuoc,
			String tinHoc, String ngayVaoDang, String ngayChinhThuc, String ngayThamGiaToChucChinhTri, String ngayNhapNgu,
			String ngayXuatNgu, String quanHamCaoNhat, String danhHieuPhongTangCaoNhat, String soTruongCongTac,
			String tinhTrangSucKhoe, Float chieuCao, Float canNang, String nhomMau, String laThuongBinhHang,
			String laConGiaDinhChinhSach, String soCmnd, String ngayCap, String soBhxh, String nhanXetCapTren,
			Boolean daXacNhan, String hinhanh, String sohieucongchuc, String soTruong, String khenThuongCaoNhat,
			String kyLuatCaoNhat, Set<Dienbienluong> dienbienluongs) {
		this.canboByNguoixacnhan = canboByNguoixacnhan;
		this.canboByMaCanBo = canboByMaCanBo;
		this.dantoc = dantoc;
		this.ngoaingu = ngoaingu;
		this.tongiao = tongiao;
		this.trinhdochinhtri = trinhdochinhtri;
		this.trinhdochuyenmon = trinhdochuyenmon;
		this.tenGoiKhac = tenGoiKhac;
		this.tenCanBo = tenCanBo;
		this.ngaySinh = ngaySinh;
		this.gioiTinh = gioiTinh;
		this.noiSinh = noiSinh;
		this.queQuan = queQuan;
		this.hoKhauThuongTru = hoKhauThuongTru;
		this.noiOhienNay = noiOhienNay;
		this.ngheNgiepKhiDuocTuyenDung = ngheNgiepKhiDuocTuyenDung;
		this.ngayTuyenDung = ngayTuyenDung;
		this.chucVuBenNgoaiHienTai = chucVuBenNgoaiHienTai;
		this.congViecChinhDuocGiao = congViecChinhDuocGiao;
		this.ngachCongChuc = ngachCongChuc;
		this.maNgach = maNgach;
		this.bacLuong = bacLuong;
		this.heSo = heSo;
		this.ngayHuong = ngayHuong;
		this.phuCapChucVu = phuCapChucVu;
		this.phuCapKhac = phuCapKhac;
		this.trinhDoPhoThong = trinhDoPhoThong;
		this.quanLyNhaNuoc = quanLyNhaNuoc;
		this.tinHoc = tinHoc;
		this.ngayVaoDang = ngayVaoDang;
		this.ngayChinhThuc = ngayChinhThuc;
		this.ngayThamGiaToChucChinhTri = ngayThamGiaToChucChinhTri;
		this.ngayNhapNgu = ngayNhapNgu;
		this.ngayXuatNgu = ngayXuatNgu;
		this.quanHamCaoNhat = quanHamCaoNhat;
		this.danhHieuPhongTangCaoNhat = danhHieuPhongTangCaoNhat;
		this.soTruongCongTac = soTruongCongTac;
		this.tinhTrangSucKhoe = tinhTrangSucKhoe;
		this.chieuCao = chieuCao;
		this.canNang = canNang;
		this.nhomMau = nhomMau;
		this.laThuongBinhHang = laThuongBinhHang;
		this.laConGiaDinhChinhSach = laConGiaDinhChinhSach;
		this.soCmnd = soCmnd;
		this.ngayCap = ngayCap;
		this.soBhxh = soBhxh;
		this.nhanXetCapTren = nhanXetCapTren;
		this.daXacNhan = daXacNhan;
		this.hinhanh = hinhanh;
		this.sohieucongchuc = sohieucongchuc;
		this.soTruong = soTruong;
		this.khenThuongCaoNhat = khenThuongCaoNhat;
		this.kyLuatCaoNhat = kyLuatCaoNhat;
		this.dienbienluongs = dienbienluongs;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "canboByMaCanBo"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "Macanbo", unique = true, nullable = false)
	public int getMacanbo() {
		return this.macanbo;
	}

	public void setMacanbo(int macanbo) {
		this.macanbo = macanbo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Nguoixacnhan")
	public Canbo getCanboByNguoixacnhan() {
		return this.canboByNguoixacnhan;
	}

	public void setCanboByNguoixacnhan(Canbo canboByNguoixacnhan) {
		this.canboByNguoixacnhan = canboByNguoixacnhan;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Canbo getCanboByMaCanBo() {
		return this.canboByMaCanBo;
	}

	public void setCanboByMaCanBo(Canbo canboByMaCanBo) {
		this.canboByMaCanBo = canboByMaCanBo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaDanToc")
	public Dantoc getDantoc() {
		return this.dantoc;
	}

	public void setDantoc(Dantoc dantoc) {
		this.dantoc = dantoc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NgoaiNgu")
	public Ngoaingu getNgoaingu() {
		return this.ngoaingu;
	}

	public void setNgoaingu(Ngoaingu ngoaingu) {
		this.ngoaingu = ngoaingu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaTonGiao")
	public Tongiao getTongiao() {
		return this.tongiao;
	}

	public void setTongiao(Tongiao tongiao) {
		this.tongiao = tongiao;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaTrinhDoChinhTri")
	public Trinhdochinhtri getTrinhdochinhtri() {
		return this.trinhdochinhtri;
	}

	public void setTrinhdochinhtri(Trinhdochinhtri trinhdochinhtri) {
		this.trinhdochinhtri = trinhdochinhtri;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaTrinhDoChuyenMon")
	public Trinhdochuyenmon getTrinhdochuyenmon() {
		return this.trinhdochuyenmon;
	}

	public void setTrinhdochuyenmon(Trinhdochuyenmon trinhdochuyenmon) {
		this.trinhdochuyenmon = trinhdochuyenmon;
	}

	@Column(name = "TenGoiKhac", length = 200)
	public String getTenGoiKhac() {
		return this.tenGoiKhac;
	}

	public void setTenGoiKhac(String tenGoiKhac) {
		this.tenGoiKhac = tenGoiKhac;
	}

	@Column(name = "TenCanBo", length = 200)
	public String getTenCanBo() {
		return this.tenCanBo;
	}

	public void setTenCanBo(String tenCanBo) {
		this.tenCanBo = tenCanBo;
	}

 
	@Column(name = "NgaySinh", length = 100)
	public String getNgaySinh() {
		return this.ngaySinh;
	}

	public void setNgaySinh(String ngaySinh) {
		this.ngaySinh = ngaySinh;
	}

	@Column(name = "GioiTinh")
	public Boolean getGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(Boolean gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	@Column(name = "NoiSinh", length = 200)
	public String getNoiSinh() {
		return this.noiSinh;
	}

	public void setNoiSinh(String noiSinh) {
		this.noiSinh = noiSinh;
	}

	@Column(name = "QueQuan", length = 200)
	public String getQueQuan() {
		return this.queQuan;
	}

	public void setQueQuan(String queQuan) {
		this.queQuan = queQuan;
	}

	@Column(name = "HoKhauThuongTru", length = 500)
	public String getHoKhauThuongTru() {
		return this.hoKhauThuongTru;
	}

	public void setHoKhauThuongTru(String hoKhauThuongTru) {
		this.hoKhauThuongTru = hoKhauThuongTru;
	}

	@Column(name = "NoiOHienNay", length = 500)
	public String getNoiOhienNay() {
		return this.noiOhienNay;
	}

	public void setNoiOhienNay(String noiOhienNay) {
		this.noiOhienNay = noiOhienNay;
	}

	@Column(name = "NgheNgiepKhiDuocTuyenDung", length = 200)
	public String getNgheNgiepKhiDuocTuyenDung() {
		return this.ngheNgiepKhiDuocTuyenDung;
	}

	public void setNgheNgiepKhiDuocTuyenDung(String ngheNgiepKhiDuocTuyenDung) {
		this.ngheNgiepKhiDuocTuyenDung = ngheNgiepKhiDuocTuyenDung;
	}
 
	@Column(name = "NgayTuyenDung", length = 100)
	public String getNgayTuyenDung() {
		return this.ngayTuyenDung;
	}

	public void setNgayTuyenDung(String ngayTuyenDung) {
		this.ngayTuyenDung = ngayTuyenDung;
	}

	@Column(name = "ChucVuBenNgoaiHienTai", length = 200)
	public String getChucVuBenNgoaiHienTai() {
		return this.chucVuBenNgoaiHienTai;
	}

	public void setChucVuBenNgoaiHienTai(String chucVuBenNgoaiHienTai) {
		this.chucVuBenNgoaiHienTai = chucVuBenNgoaiHienTai;
	}

	@Column(name = "CongViecChinhDuocGiao", length = 500)
	public String getCongViecChinhDuocGiao() {
		return this.congViecChinhDuocGiao;
	}

	public void setCongViecChinhDuocGiao(String congViecChinhDuocGiao) {
		this.congViecChinhDuocGiao = congViecChinhDuocGiao;
	}

	@Column(name = "NgachCongChuc", length = 500)
	public String getNgachCongChuc() {
		return this.ngachCongChuc;
	}

	public void setNgachCongChuc(String ngachCongChuc) {
		this.ngachCongChuc = ngachCongChuc;
	}

	@Column(name = "MaNgach", precision = 12, scale = 0)
	public Float getMaNgach() {
		return this.maNgach;
	}

	public void setMaNgach(Float maNgach) {
		this.maNgach = maNgach;
	}

	@Column(name = "BacLuong", precision = 12, scale = 0)
	public Float getBacLuong() {
		return this.bacLuong;
	}

	public void setBacLuong(Float bacLuong) {
		this.bacLuong = bacLuong;
	}

	@Column(name = "HeSo", precision = 12, scale = 0)
	public Float getHeSo() {
		return this.heSo;
	}

	public void setHeSo(Float heSo) {
		this.heSo = heSo;
	}

 
	@Column(name = "NgayHuong", length = 100)
	public String getNgayHuong() {
		return this.ngayHuong;
	}

	public void setNgayHuong(String ngayHuong) {
		this.ngayHuong = ngayHuong;
	}

	@Column(name = "PhuCapChucVu", precision = 22, scale = 0)
	public Double getPhuCapChucVu() {
		return this.phuCapChucVu;
	}

	public void setPhuCapChucVu(Double phuCapChucVu) {
		this.phuCapChucVu = phuCapChucVu;
	}

	@Column(name = "PhuCapKhac", precision = 22, scale = 0)
	public Double getPhuCapKhac() {
		return this.phuCapKhac;
	}

	public void setPhuCapKhac(Double phuCapKhac) {
		this.phuCapKhac = phuCapKhac;
	}

	@Column(name = "TrinhDoPhoThong", length = 200)
	public String getTrinhDoPhoThong() {
		return this.trinhDoPhoThong;
	}

	public void setTrinhDoPhoThong(String trinhDoPhoThong) {
		this.trinhDoPhoThong = trinhDoPhoThong;
	}

	@Column(name = "QuanLyNhaNuoc", length = 200)
	public String getQuanLyNhaNuoc() {
		return this.quanLyNhaNuoc;
	}

	public void setQuanLyNhaNuoc(String quanLyNhaNuoc) {
		this.quanLyNhaNuoc = quanLyNhaNuoc;
	}

	@Column(name = "TinHoc", length = 200)
	public String getTinHoc() {
		return this.tinHoc;
	}

	public void setTinHoc(String tinHoc) {
		this.tinHoc = tinHoc;
	}

 
	@Column(name = "NgayVaoDang", length = 100)
	public String getNgayVaoDang() {
		return this.ngayVaoDang;
	}

	public void setNgayVaoDang(String ngayVaoDang) {
		this.ngayVaoDang = ngayVaoDang;
	}

 
	@Column(name = "NgayChinhThuc", length = 100)
	public String getNgayChinhThuc() {
		return this.ngayChinhThuc;
	}

	public void setNgayChinhThuc(String ngayChinhThuc) {
		this.ngayChinhThuc = ngayChinhThuc;
	}

	@Column(name = "NgayThamGiaToChucChinhTri", length = 65535)
	public String getNgayThamGiaToChucChinhTri() {
		return this.ngayThamGiaToChucChinhTri;
	}

	public void setNgayThamGiaToChucChinhTri(String ngayThamGiaToChucChinhTri) {
		this.ngayThamGiaToChucChinhTri = ngayThamGiaToChucChinhTri;
	}

 
	@Column(name = "NgayNhapNgu", length = 100)
	public String getNgayNhapNgu() {
		return this.ngayNhapNgu;
	}

	public void setNgayNhapNgu(String ngayNhapNgu) {
		this.ngayNhapNgu = ngayNhapNgu;
	}

	 
	@Column(name = "NgayXuatNgu", length = 100)
	public String getNgayXuatNgu() {
		return this.ngayXuatNgu;
	}

	public void setNgayXuatNgu(String ngayXuatNgu) {
		this.ngayXuatNgu = ngayXuatNgu;
	}

	@Column(name = "QuanHamCaoNhat", length = 200)
	public String getQuanHamCaoNhat() {
		return this.quanHamCaoNhat;
	}

	public void setQuanHamCaoNhat(String quanHamCaoNhat) {
		this.quanHamCaoNhat = quanHamCaoNhat;
	}

	@Column(name = "DanhHieuPhongTangCaoNhat", length = 200)
	public String getDanhHieuPhongTangCaoNhat() {
		return this.danhHieuPhongTangCaoNhat;
	}

	public void setDanhHieuPhongTangCaoNhat(String danhHieuPhongTangCaoNhat) {
		this.danhHieuPhongTangCaoNhat = danhHieuPhongTangCaoNhat;
	}

	@Column(name = "SoTruongCongTac", length = 200)
	public String getSoTruongCongTac() {
		return this.soTruongCongTac;
	}

	public void setSoTruongCongTac(String soTruongCongTac) {
		this.soTruongCongTac = soTruongCongTac;
	}

	@Column(name = "TinhTrangSucKhoe", length = 200)
	public String getTinhTrangSucKhoe() {
		return this.tinhTrangSucKhoe;
	}

	public void setTinhTrangSucKhoe(String tinhTrangSucKhoe) {
		this.tinhTrangSucKhoe = tinhTrangSucKhoe;
	}

	@Column(name = "ChieuCao", precision = 12, scale = 0)
	public Float getChieuCao() {
		return this.chieuCao;
	}

	public void setChieuCao(Float chieuCao) {
		this.chieuCao = chieuCao;
	}

	@Column(name = "CanNang", precision = 12, scale = 0)
	public Float getCanNang() {
		return this.canNang;
	}

	public void setCanNang(Float canNang) {
		this.canNang = canNang;
	}
	@Column(name = "NoiSuDung", precision = 12, scale = 0)
	public String getNoiSuDung() {
		return this.noiSuDung;
	}

	public void setNoiSuDung(String canNang) {
		this.noiSuDung = canNang;
	}
	@Column(name = "NoiQuanLy", precision = 12, scale = 0)
	public String getNoiQuanLy() {
		return this.noiQuanLy;
	}

	public void setNoiQuanLy(String canNang) {
		this.noiQuanLy = canNang;
	}

	@Column(name = "NhomMau", length = 200)
	public String getNhomMau() {
		return this.nhomMau;
	}

	public void setNhomMau(String nhomMau) {
		this.nhomMau = nhomMau;
	}

	@Column(name = "LaThuongBinhHang", length = 200)
	public String getLaThuongBinhHang() {
		return this.laThuongBinhHang;
	}

	public void setLaThuongBinhHang(String laThuongBinhHang) {
		this.laThuongBinhHang = laThuongBinhHang;
	}

	@Column(name = "LaConGiaDinhChinhSach", length = 200)
	public String getLaConGiaDinhChinhSach() {
		return this.laConGiaDinhChinhSach;
	}

	public void setLaConGiaDinhChinhSach(String laConGiaDinhChinhSach) {
		this.laConGiaDinhChinhSach = laConGiaDinhChinhSach;
	}

	@Column(name = "SoCMND", length = 20)
	public String getSoCmnd() {
		return this.soCmnd;
	}

	public void setSoCmnd(String soCmnd) {
		this.soCmnd = soCmnd;
	}

 
	@Column(name = "NgayCap", length = 100)
	public String getNgayCap() {
		return this.ngayCap;
	}

	public void setNgayCap(String ngayCap) {
		this.ngayCap = ngayCap;
	}

	@Column(name = "SoBHXH", length = 200)
	public String getSoBhxh() {
		return this.soBhxh;
	}

	public void setSoBhxh(String soBhxh) {
		this.soBhxh = soBhxh;
	}

	@Column(name = "NhanXetCapTren", length = 65535)
	public String getNhanXetCapTren() {
		return this.nhanXetCapTren;
	}

	public void setNhanXetCapTren(String nhanXetCapTren) {
		this.nhanXetCapTren = nhanXetCapTren;
	}

	@Column(name = "DaXacNhan")
	public Boolean getDaXacNhan() {
		return this.daXacNhan;
	}

	public void setDaXacNhan(Boolean daXacNhan) {
		this.daXacNhan = daXacNhan;
	}

	@Column(name = "hinhanh", length = 555)
	public String getHinhanh() {
		return this.hinhanh;
	}

	public void setHinhanh(String hinhanh) {
		this.hinhanh = hinhanh;
	}

	@Column(name = "Sohieucongchuc", length = 405)
	public String getSohieucongchuc() {
		return this.sohieucongchuc;
	}

	public void setSohieucongchuc(String sohieucongchuc) {
		this.sohieucongchuc = sohieucongchuc;
	}

	@Column(name = "SoTruong", length = 555)
	public String getSoTruong() {
		return this.soTruong;
	}

	public void setSoTruong(String soTruong) {
		this.soTruong = soTruong;
	}

	@Column(name = "KhenThuongCaoNhat", length = 555)
	public String getKhenThuongCaoNhat() {
		return this.khenThuongCaoNhat;
	}
	@Column(name = "CoQuanTuyenDung", length = 45)
	public String getCoQuanTuyenDung() {
		return coQuanTuyenDung;
	}
	public void setCoQuanTuyenDung(String coQuanTuyenDung) {
		this.coQuanTuyenDung = coQuanTuyenDung;
	}

	public void setKhenThuongCaoNhat(String khenThuongCaoNhat) {
		this.khenThuongCaoNhat = khenThuongCaoNhat;
	}

	@Column(name = "KyLuatCaoNhat", length = 555)
	public String getKyLuatCaoNhat() {
		return this.kyLuatCaoNhat;
	}

	public void setKyLuatCaoNhat(String kyLuatCaoNhat) {
		this.kyLuatCaoNhat = kyLuatCaoNhat;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lylich")
	public Set<Dienbienluong> getDienbienluongs() {
		return this.dienbienluongs;
	}

	public void setDienbienluongs(Set<Dienbienluong> dienbienluongs) {
		this.dienbienluongs = dienbienluongs;
	}

}
