package com.springmvc.qlcb.model;
// Generated Apr 19, 2016 9:35:55 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mucdohoanthanh generated by hbm2java
 */
@Entity
@Table(name = "mucdohoanthanh", catalog = "qlcb_new")
public class Mucdohoanthanh implements java.io.Serializable {

	private int id;
	private String tenMucDoHoanThanh;
	private Set<Danhgiacanbo> danhgiacanbos = new HashSet<Danhgiacanbo>(0);

	public Mucdohoanthanh() {
	}

	public Mucdohoanthanh(int id, String tenMucDoHoanThanh) {
		this.id = id;
		this.tenMucDoHoanThanh = tenMucDoHoanThanh;
	}

	public Mucdohoanthanh(int id, String tenMucDoHoanThanh, Set<Danhgiacanbo> danhgiacanbos) {
		this.id = id;
		this.tenMucDoHoanThanh = tenMucDoHoanThanh;
		this.danhgiacanbos = danhgiacanbos;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "TenMucDoHoanThanh", nullable = false, length = 200)
	public String getTenMucDoHoanThanh() {
		return this.tenMucDoHoanThanh;
	}

	public void setTenMucDoHoanThanh(String tenMucDoHoanThanh) {
		this.tenMucDoHoanThanh = tenMucDoHoanThanh;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mucdohoanthanh")
	public Set<Danhgiacanbo> getDanhgiacanbos() {
		return this.danhgiacanbos;
	}

	public void setDanhgiacanbos(Set<Danhgiacanbo> danhgiacanbos) {
		this.danhgiacanbos = danhgiacanbos;
	}

}
