package com.springmvc.qlcb.model;
// Generated Apr 25, 2016 2:33:53 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mucdohoanthanh generated by hbm2java
 */
@Entity
@Table(name = "mucdohoanthanh", catalog = "qlcb")
public class Mucdohoanthanh implements java.io.Serializable {

	private int maMucDoHoanThanh;
	private String tenMucDoHoanThanh;
	private Set<Danhgiacanbo> danhgiacanbos = new HashSet<Danhgiacanbo>(0);

	public Mucdohoanthanh() {
	}

	public Mucdohoanthanh(int maMucDoHoanThanh, String tenMucDoHoanThanh) {
		this.maMucDoHoanThanh = maMucDoHoanThanh;
		this.tenMucDoHoanThanh = tenMucDoHoanThanh;
	}

	public Mucdohoanthanh(int maMucDoHoanThanh, String tenMucDoHoanThanh, Set<Danhgiacanbo> danhgiacanbos) {
		this.maMucDoHoanThanh = maMucDoHoanThanh;
		this.tenMucDoHoanThanh = tenMucDoHoanThanh;
		this.danhgiacanbos = danhgiacanbos;
	}

	@Id

	@Column(name = "MaMucDoHoanThanh", unique = true, nullable = false)
	public int getMaMucDoHoanThanh() {
		return this.maMucDoHoanThanh;
	}

	public void setMaMucDoHoanThanh(int maMucDoHoanThanh) {
		this.maMucDoHoanThanh = maMucDoHoanThanh;
	}

	@Column(name = "TenMucDoHoanThanh", nullable = false, length = 200)
	public String getTenMucDoHoanThanh() {
		return this.tenMucDoHoanThanh;
	}

	public void setTenMucDoHoanThanh(String tenMucDoHoanThanh) {
		this.tenMucDoHoanThanh = tenMucDoHoanThanh;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mucdohoanthanh")
	public Set<Danhgiacanbo> getDanhgiacanbos() {
		return this.danhgiacanbos;
	}

	public void setDanhgiacanbos(Set<Danhgiacanbo> danhgiacanbos) {
		this.danhgiacanbos = danhgiacanbos;
	}

}
