package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MucDoHoanThanh generated by hbm2java
 */
@Entity
@Table(name = "muc_do_hoan_thanh", catalog = "qlcb")
public class MucDoHoanThanh implements java.io.Serializable {

	private Byte maMdht;
	private String tenMdht;
	private Set<DanhGiaCanBo> danhGiaCanBosForMaMdhtTuDanhGia = new HashSet<DanhGiaCanBo>(0);
	private Set<DanhGiaCanBo> danhGiaCanBosForMaMdht = new HashSet<DanhGiaCanBo>(0);

	public MucDoHoanThanh() {
	}

	public MucDoHoanThanh(String tenMdht, Set<DanhGiaCanBo> danhGiaCanBosForMaMdhtTuDanhGia,
			Set<DanhGiaCanBo> danhGiaCanBosForMaMdht) {
		this.tenMdht = tenMdht;
		this.danhGiaCanBosForMaMdhtTuDanhGia = danhGiaCanBosForMaMdhtTuDanhGia;
		this.danhGiaCanBosForMaMdht = danhGiaCanBosForMaMdht;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Ma_MDHT", unique = true, nullable = false)
	public Byte getMaMdht() {
		return this.maMdht;
	}

	public void setMaMdht(Byte maMdht) {
		this.maMdht = maMdht;
	}

	@Column(name = "Ten_MDHT", length = 254)
	public String getTenMdht() {
		return this.tenMdht;
	}

	public void setTenMdht(String tenMdht) {
		this.tenMdht = tenMdht;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mucDoHoanThanhByMaMdhtTuDanhGia")
	public Set<DanhGiaCanBo> getDanhGiaCanBosForMaMdhtTuDanhGia() {
		return this.danhGiaCanBosForMaMdhtTuDanhGia;
	}

	public void setDanhGiaCanBosForMaMdhtTuDanhGia(Set<DanhGiaCanBo> danhGiaCanBosForMaMdhtTuDanhGia) {
		this.danhGiaCanBosForMaMdhtTuDanhGia = danhGiaCanBosForMaMdhtTuDanhGia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mucDoHoanThanhByMaMdht")
	public Set<DanhGiaCanBo> getDanhGiaCanBosForMaMdht() {
		return this.danhGiaCanBosForMaMdht;
	}

	public void setDanhGiaCanBosForMaMdht(Set<DanhGiaCanBo> danhGiaCanBosForMaMdht) {
		this.danhGiaCanBosForMaMdht = danhGiaCanBosForMaMdht;
	}

}
