package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MucSuaDoiId generated by hbm2java
 */
@Embeddable
public class MucSuaDoiId implements java.io.Serializable {

	private long maYeuCau;
	private String tenCotThayDoi;

	public MucSuaDoiId() {
	}

	public MucSuaDoiId(long maYeuCau, String tenCotThayDoi) {
		this.maYeuCau = maYeuCau;
		this.tenCotThayDoi = tenCotThayDoi;
	}

	@Column(name = "Ma_Yeu_Cau", nullable = false)
	public long getMaYeuCau() {
		return this.maYeuCau;
	}

	public void setMaYeuCau(long maYeuCau) {
		this.maYeuCau = maYeuCau;
	}

	@Column(name = "Ten_Cot_Thay_Doi", nullable = false, length = 254)
	public String getTenCotThayDoi() {
		return this.tenCotThayDoi;
	}

	public void setTenCotThayDoi(String tenCotThayDoi) {
		this.tenCotThayDoi = tenCotThayDoi;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MucSuaDoiId))
			return false;
		MucSuaDoiId castOther = (MucSuaDoiId) other;

		return (this.getMaYeuCau() == castOther.getMaYeuCau())
				&& ((this.getTenCotThayDoi() == castOther.getTenCotThayDoi())
						|| (this.getTenCotThayDoi() != null && castOther.getTenCotThayDoi() != null
								&& this.getTenCotThayDoi().equals(castOther.getTenCotThayDoi())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getMaYeuCau();
		result = 37 * result + (getTenCotThayDoi() == null ? 0 : this.getTenCotThayDoi().hashCode());
		return result;
	}

}
