package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MucThuongTheoDien generated by hbm2java
 */
@Entity
@Table(name = "muc_thuong_theo_dien", catalog = "qlcb")
public class MucThuongTheoDien implements java.io.Serializable {

	private MucThuongTheoDienId id;
	private DienKhenThuong dienKhenThuong;
	private KqXetThiDua kqXetThiDua;
	private Long mucThuong;

	public MucThuongTheoDien() {
	}

	public MucThuongTheoDien(MucThuongTheoDienId id, DienKhenThuong dienKhenThuong, KqXetThiDua kqXetThiDua) {
		this.id = id;
		this.dienKhenThuong = dienKhenThuong;
		this.kqXetThiDua = kqXetThiDua;
	}

	public MucThuongTheoDien(MucThuongTheoDienId id, DienKhenThuong dienKhenThuong, KqXetThiDua kqXetThiDua,
			Long mucThuong) {
		this.id = id;
		this.dienKhenThuong = dienKhenThuong;
		this.kqXetThiDua = kqXetThiDua;
		this.mucThuong = mucThuong;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "maDien", column = @Column(name = "Ma_Dien", nullable = false)),
			@AttributeOverride(name = "maDsKhenThuong", column = @Column(name = "Ma_DS_Khen_Thuong", nullable = false)) })
	public MucThuongTheoDienId getId() {
		return this.id;
	}

	public void setId(MucThuongTheoDienId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ma_Dien", nullable = false, insertable = false, updatable = false)
	public DienKhenThuong getDienKhenThuong() {
		return this.dienKhenThuong;
	}

	public void setDienKhenThuong(DienKhenThuong dienKhenThuong) {
		this.dienKhenThuong = dienKhenThuong;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ma_DS_Khen_Thuong", nullable = false, insertable = false, updatable = false)
	public KqXetThiDua getKqXetThiDua() {
		return this.kqXetThiDua;
	}

	public void setKqXetThiDua(KqXetThiDua kqXetThiDua) {
		this.kqXetThiDua = kqXetThiDua;
	}

	@Column(name = "Muc_Thuong")
	public Long getMucThuong() {
		return this.mucThuong;
	}

	public void setMucThuong(Long mucThuong) {
		this.mucThuong = mucThuong;
	}

}
