package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MucThuongTheoDienId generated by hbm2java
 */
@Embeddable
public class MucThuongTheoDienId implements java.io.Serializable {

	private short maDien;
	private int maDsKhenThuong;

	public MucThuongTheoDienId() {
	}

	public MucThuongTheoDienId(short maDien, int maDsKhenThuong) {
		this.maDien = maDien;
		this.maDsKhenThuong = maDsKhenThuong;
	}

	@Column(name = "Ma_Dien", nullable = false)
	public short getMaDien() {
		return this.maDien;
	}

	public void setMaDien(short maDien) {
		this.maDien = maDien;
	}

	@Column(name = "Ma_DS_Khen_Thuong", nullable = false)
	public int getMaDsKhenThuong() {
		return this.maDsKhenThuong;
	}

	public void setMaDsKhenThuong(int maDsKhenThuong) {
		this.maDsKhenThuong = maDsKhenThuong;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MucThuongTheoDienId))
			return false;
		MucThuongTheoDienId castOther = (MucThuongTheoDienId) other;

		return (this.getMaDien() == castOther.getMaDien())
				&& (this.getMaDsKhenThuong() == castOther.getMaDsKhenThuong());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMaDien();
		result = 37 * result + this.getMaDsKhenThuong();
		return result;
	}

}
