package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NgachLuong generated by hbm2java
 */
@Entity
@Table(name = "ngach_luong", catalog = "qlcb")
public class NgachLuong implements java.io.Serializable {

	private String maSoNgach;
	private String kyHieuNgach;
	private String tenNgach;
	private Set<QuaTrinhLuong> quaTrinhLuongs = new HashSet<QuaTrinhLuong>(0);

	public NgachLuong() {
	}

	public NgachLuong(String maSoNgach) {
		this.maSoNgach = maSoNgach;
	}

	public NgachLuong(String maSoNgach, String kyHieuNgach, String tenNgach, Set<QuaTrinhLuong> quaTrinhLuongs) {
		this.maSoNgach = maSoNgach;
		this.kyHieuNgach = kyHieuNgach;
		this.tenNgach = tenNgach;
		this.quaTrinhLuongs = quaTrinhLuongs;
	}

	@Id

	@Column(name = "Ma_So_Ngach", unique = true, nullable = false, length = 32)
	public String getMaSoNgach() {
		return this.maSoNgach;
	}

	public void setMaSoNgach(String maSoNgach) {
		this.maSoNgach = maSoNgach;
	}

	@Column(name = "Ky_Hieu_Ngach", length = 32)
	public String getKyHieuNgach() {
		return this.kyHieuNgach;
	}

	public void setKyHieuNgach(String kyHieuNgach) {
		this.kyHieuNgach = kyHieuNgach;
	}

	@Column(name = "Ten_Ngach", length = 254)
	public String getTenNgach() {
		return this.tenNgach;
	}

	public void setTenNgach(String tenNgach) {
		this.tenNgach = tenNgach;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ngachLuong")
	public Set<QuaTrinhLuong> getQuaTrinhLuongs() {
		return this.quaTrinhLuongs;
	}

	public void setQuaTrinhLuongs(Set<QuaTrinhLuong> quaTrinhLuongs) {
		this.quaTrinhLuongs = quaTrinhLuongs;
	}

}
