package com.springmvc.qlcb.model;
// Generated Apr 21, 2016 1:56:09 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Ngoaingu generated by hbm2java
 */
@Entity
@Table(name = "ngoaingu", catalog = "qlcb")
public class Ngoaingu implements java.io.Serializable {

	private int maNgoaiNgu;
	private String tenNgoaiNgu;
	private Set<Canbo> canbos = new HashSet<Canbo>(0);

	public Ngoaingu() {
	}

	public Ngoaingu(int maNgoaiNgu, String tenNgoaiNgu) {
		this.maNgoaiNgu = maNgoaiNgu;
		this.tenNgoaiNgu = tenNgoaiNgu;
	}

	public Ngoaingu(int maNgoaiNgu, String tenNgoaiNgu, Set<Canbo> canbos) {
		this.maNgoaiNgu = maNgoaiNgu;
		this.tenNgoaiNgu = tenNgoaiNgu;
		this.canbos = canbos;
	}

	@Id

	@Column(name = "MaNgoaiNgu", unique = true, nullable = false)
	public int getMaNgoaiNgu() {
		return this.maNgoaiNgu;
	}

	public void setMaNgoaiNgu(int maNgoaiNgu) {
		this.maNgoaiNgu = maNgoaiNgu;
	}

	@Column(name = "TenNgoaiNgu", nullable = false, length = 200)
	public String getTenNgoaiNgu() {
		return this.tenNgoaiNgu;
	}

	public void setTenNgoaiNgu(String tenNgoaiNgu) {
		this.tenNgoaiNgu = tenNgoaiNgu;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "canbo_ngoaingu", catalog = "qlcb", joinColumns = {
			@JoinColumn(name = "MaNgoaiNgu", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "MaCanBo", nullable = false, updatable = false) })
	public Set<Canbo> getCanbos() {
		return this.canbos;
	}

	public void setCanbos(Set<Canbo> canbos) {
		this.canbos = canbos;
	}

}
