package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NgoaiNgu generated by hbm2java
 */
@Entity
@Table(name = "ngoai_ngu", catalog = "qlcb")
public class NgoaiNgu implements java.io.Serializable {

	private Short maNgoaiNgu;
	private String tenNgoaiNgu;

	public NgoaiNgu() {
	}

	public NgoaiNgu(String tenNgoaiNgu) {
		this.tenNgoaiNgu = tenNgoaiNgu;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Ma_Ngoai_Ngu", unique = true, nullable = false)
	public Short getMaNgoaiNgu() {
		return this.maNgoaiNgu;
	}

	public void setMaNgoaiNgu(Short maNgoaiNgu) {
		this.maNgoaiNgu = maNgoaiNgu;
	}

	@Column(name = "Ten_Ngoai_Ngu", length = 63)
	public String getTenNgoaiNgu() {
		return this.tenNgoaiNgu;
	}

	public void setTenNgoaiNgu(String tenNgoaiNgu) {
		this.tenNgoaiNgu = tenNgoaiNgu;
	}

}
