package com.springmvc.qlcb.model;
// Generated Apr 25, 2016 1:43:12 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ngoaingu generated by hbm2java
 */
@Entity
@Table(name = "ngoaingu", catalog = "qlcb")
public class Ngoaingu implements java.io.Serializable {

	private int maNgoaiNgu;
	private String tenNgoaiNgu;
	private Set<Lylich> lyliches = new HashSet<Lylich>(0);

	public Ngoaingu() {
	}

	public Ngoaingu(int maNgoaiNgu, String tenNgoaiNgu) {
		this.maNgoaiNgu = maNgoaiNgu;
		this.tenNgoaiNgu = tenNgoaiNgu;
	}

	public Ngoaingu(int maNgoaiNgu, String tenNgoaiNgu, Set<Lylich> lyliches) {
		this.maNgoaiNgu = maNgoaiNgu;
		this.tenNgoaiNgu = tenNgoaiNgu;
		this.lyliches = lyliches;
	}

	@Id

	@Column(name = "MaNgoaiNgu", unique = true, nullable = false)
	public int getMaNgoaiNgu() {
		return this.maNgoaiNgu;
	}

	public void setMaNgoaiNgu(int maNgoaiNgu) {
		this.maNgoaiNgu = maNgoaiNgu;
	}

	@Column(name = "TenNgoaiNgu", nullable = false, length = 200)
	public String getTenNgoaiNgu() {
		return this.tenNgoaiNgu;
	}

	public void setTenNgoaiNgu(String tenNgoaiNgu) {
		this.tenNgoaiNgu = tenNgoaiNgu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ngoaingu")
	public Set<Lylich> getLyliches() {
		return this.lyliches;
	}

	public void setLyliches(Set<Lylich> lyliches) {
		this.lyliches = lyliches;
	}

}
