package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Privilege generated by hbm2java
 */
@Entity
@Table(name = "privilege", catalog = "qlcb")
public class Privilege implements java.io.Serializable {

	private String privilegeName;
	private Controller controller;
	private String privilegeDisplayName;
	private Set<RolePrivilegeRelation> rolePrivilegeRelations = new HashSet<RolePrivilegeRelation>(0);

	public Privilege() {
	}

	public Privilege(String privilegeName) {
		this.privilegeName = privilegeName;
	}

	public Privilege(String privilegeName, Controller controller, String privilegeDisplayName,
			Set<RolePrivilegeRelation> rolePrivilegeRelations) {
		this.privilegeName = privilegeName;
		this.controller = controller;
		this.privilegeDisplayName = privilegeDisplayName;
		this.rolePrivilegeRelations = rolePrivilegeRelations;
	}

	@Id

	@Column(name = "Privilege_Name", unique = true, nullable = false, length = 32)
	public String getPrivilegeName() {
		return this.privilegeName;
	}

	public void setPrivilegeName(String privilegeName) {
		this.privilegeName = privilegeName;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Controller_Name")
	public Controller getController() {
		return this.controller;
	}

	public void setController(Controller controller) {
		this.controller = controller;
	}

	@Column(name = "Privilege_Display_Name", length = 254)
	public String getPrivilegeDisplayName() {
		return this.privilegeDisplayName;
	}

	public void setPrivilegeDisplayName(String privilegeDisplayName) {
		this.privilegeDisplayName = privilegeDisplayName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "privilege")
	public Set<RolePrivilegeRelation> getRolePrivilegeRelations() {
		return this.rolePrivilegeRelations;
	}

	public void setRolePrivilegeRelations(Set<RolePrivilegeRelation> rolePrivilegeRelations) {
		this.rolePrivilegeRelations = rolePrivilegeRelations;
	}

}
