package com.springmvc.qlcb.model;
// Generated Apr 19, 2016 9:35:55 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Quanhe generated by hbm2java
 */
@Entity
@Table(name = "quanhe", catalog = "qlcb_new")
public class Quanhe implements java.io.Serializable {

	private int id;
	private String tenQuanHe;
	private Set<Thanhviengiadinh> thanhviengiadinhs = new HashSet<Thanhviengiadinh>(0);

	public Quanhe() {
	}

	public Quanhe(int id, String tenQuanHe) {
		this.id = id;
		this.tenQuanHe = tenQuanHe;
	}

	public Quanhe(int id, String tenQuanHe, Set<Thanhviengiadinh> thanhviengiadinhs) {
		this.id = id;
		this.tenQuanHe = tenQuanHe;
		this.thanhviengiadinhs = thanhviengiadinhs;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "TenQuanHe", nullable = false, length = 200)
	public String getTenQuanHe() {
		return this.tenQuanHe;
	}

	public void setTenQuanHe(String tenQuanHe) {
		this.tenQuanHe = tenQuanHe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quanhe")
	public Set<Thanhviengiadinh> getThanhviengiadinhs() {
		return this.thanhviengiadinhs;
	}

	public void setThanhviengiadinhs(Set<Thanhviengiadinh> thanhviengiadinhs) {
		this.thanhviengiadinhs = thanhviengiadinhs;
	}

}
