package com.springmvc.qlcb.model;
// Generated Apr 25, 2016 1:43:12 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Quanhe generated by hbm2java
 */
@Entity
@Table(name = "quanhe", catalog = "qlcb")
public class Quanhe implements java.io.Serializable {

	private int maQuanHe;
	private String tenQuanHe;
	private Set<CanboGiadinhBanthan> canboGiadinhBanthans = new HashSet<CanboGiadinhBanthan>(0);
	private Set<CanboGiadinhDoitac> canboGiadinhDoitacs = new HashSet<CanboGiadinhDoitac>(0);

	public Quanhe() {
	}

	public Quanhe(int maQuanHe, String tenQuanHe) {
		this.maQuanHe = maQuanHe;
		this.tenQuanHe = tenQuanHe;
	}

	public Quanhe(int maQuanHe, String tenQuanHe, Set<CanboGiadinhBanthan> canboGiadinhBanthans,
			Set<CanboGiadinhDoitac> canboGiadinhDoitacs) {
		this.maQuanHe = maQuanHe;
		this.tenQuanHe = tenQuanHe;
		this.canboGiadinhBanthans = canboGiadinhBanthans;
		this.canboGiadinhDoitacs = canboGiadinhDoitacs;
	}

	@Id

	@Column(name = "MaQuanHe", unique = true, nullable = false)
	public int getMaQuanHe() {
		return this.maQuanHe;
	}

	public void setMaQuanHe(int maQuanHe) {
		this.maQuanHe = maQuanHe;
	}

	@Column(name = "TenQuanHe", nullable = false, length = 200)
	public String getTenQuanHe() {
		return this.tenQuanHe;
	}

	public void setTenQuanHe(String tenQuanHe) {
		this.tenQuanHe = tenQuanHe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quanhe")
	public Set<CanboGiadinhBanthan> getCanboGiadinhBanthans() {
		return this.canboGiadinhBanthans;
	}

	public void setCanboGiadinhBanthans(Set<CanboGiadinhBanthan> canboGiadinhBanthans) {
		this.canboGiadinhBanthans = canboGiadinhBanthans;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quanhe")
	public Set<CanboGiadinhDoitac> getCanboGiadinhDoitacs() {
		return this.canboGiadinhDoitacs;
	}

	public void setCanboGiadinhDoitacs(Set<CanboGiadinhDoitac> canboGiadinhDoitacs) {
		this.canboGiadinhDoitacs = canboGiadinhDoitacs;
	}

}
