package com.springmvc.qlcb.model;
// Generated Apr 23, 2016 3:25:20 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Quanhe generated by hbm2java
 */
@Entity
@Table(name = "quanhe", catalog = "qlcb")
public class Quanhe implements java.io.Serializable {

	private int maQuanHe;
	private String tenQuanHe;
	private Set<Thanhviengiadinh> thanhviengiadinhs = new HashSet<Thanhviengiadinh>(0);

	public Quanhe() {
	}

	public Quanhe(int maQuanHe, String tenQuanHe) {
		this.maQuanHe = maQuanHe;
		this.tenQuanHe = tenQuanHe;
	}

	public Quanhe(int maQuanHe, String tenQuanHe, Set<Thanhviengiadinh> thanhviengiadinhs) {
		this.maQuanHe = maQuanHe;
		this.tenQuanHe = tenQuanHe;
		this.thanhviengiadinhs = thanhviengiadinhs;
	}

	@Id

	@Column(name = "MaQuanHe", unique = true, nullable = false)
	public int getMaQuanHe() {
		return this.maQuanHe;
	}

	public void setMaQuanHe(int maQuanHe) {
		this.maQuanHe = maQuanHe;
	}

	@Column(name = "TenQuanHe", nullable = false, length = 200)
	public String getTenQuanHe() {
		return this.tenQuanHe;
	}

	public void setTenQuanHe(String tenQuanHe) {
		this.tenQuanHe = tenQuanHe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quanhe")
	public Set<Thanhviengiadinh> getThanhviengiadinhs() {
		return this.thanhviengiadinhs;
	}

	public void setThanhviengiadinhs(Set<Thanhviengiadinh> thanhviengiadinhs) {
		this.thanhviengiadinhs = thanhviengiadinhs;
	}

}
