package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QuaTrinhCongTac generated by hbm2java
 */
@Entity
@Table(name = "qua_trinh_cong_tac", catalog = "qlcb")
public class QuaTrinhCongTac implements java.io.Serializable {

	private QuaTrinhCongTacId id;
	private CanBo canBo;
	private Date tuNgay;
	private Date denNgay;
	private String soLuoc;
	private String chucDanh;
	private String chucVu;
	private String donViCongTac;

	public QuaTrinhCongTac() {
	}

	public QuaTrinhCongTac(QuaTrinhCongTacId id, CanBo canBo) {
		this.id = id;
		this.canBo = canBo;
	}

	public QuaTrinhCongTac(QuaTrinhCongTacId id, CanBo canBo, Date tuNgay, Date denNgay, String soLuoc, String chucDanh,
			String chucVu, String donViCongTac) {
		this.id = id;
		this.canBo = canBo;
		this.tuNgay = tuNgay;
		this.denNgay = denNgay;
		this.soLuoc = soLuoc;
		this.chucDanh = chucDanh;
		this.chucVu = chucVu;
		this.donViCongTac = donViCongTac;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "maQtct", column = @Column(name = "Ma_QTCT", nullable = false)),
			@AttributeOverride(name = "maCb", column = @Column(name = "Ma_CB", nullable = false)) })
	public QuaTrinhCongTacId getId() {
		return this.id;
	}

	public void setId(QuaTrinhCongTacId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ma_CB", nullable = false, insertable = false, updatable = false)
	public CanBo getCanBo() {
		return this.canBo;
	}

	public void setCanBo(CanBo canBo) {
		this.canBo = canBo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Tu_Ngay", length = 10)
	public Date getTuNgay() {
		return this.tuNgay;
	}

	public void setTuNgay(Date tuNgay) {
		this.tuNgay = tuNgay;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Den_Ngay", length = 10)
	public Date getDenNgay() {
		return this.denNgay;
	}

	public void setDenNgay(Date denNgay) {
		this.denNgay = denNgay;
	}

	@Column(name = "So_Luoc", length = 254)
	public String getSoLuoc() {
		return this.soLuoc;
	}

	public void setSoLuoc(String soLuoc) {
		this.soLuoc = soLuoc;
	}

	@Column(name = "Chuc_Danh", length = 62)
	public String getChucDanh() {
		return this.chucDanh;
	}

	public void setChucDanh(String chucDanh) {
		this.chucDanh = chucDanh;
	}

	@Column(name = "Chuc_Vu", length = 62)
	public String getChucVu() {
		return this.chucVu;
	}

	public void setChucVu(String chucVu) {
		this.chucVu = chucVu;
	}

	@Column(name = "Don_Vi_Cong_Tac", length = 254)
	public String getDonViCongTac() {
		return this.donViCongTac;
	}

	public void setDonViCongTac(String donViCongTac) {
		this.donViCongTac = donViCongTac;
	}

}
