package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * QuaTrinhCongTacId generated by hbm2java
 */
@Embeddable
public class QuaTrinhCongTacId implements java.io.Serializable {

	private long maQtct;
	private int maCb;

	public QuaTrinhCongTacId() {
	}

	public QuaTrinhCongTacId(long maQtct, int maCb) {
		this.maQtct = maQtct;
		this.maCb = maCb;
	}

	@Column(name = "Ma_QTCT", nullable = false)
	public long getMaQtct() {
		return this.maQtct;
	}

	public void setMaQtct(long maQtct) {
		this.maQtct = maQtct;
	}

	@Column(name = "Ma_CB", nullable = false)
	public int getMaCb() {
		return this.maCb;
	}

	public void setMaCb(int maCb) {
		this.maCb = maCb;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof QuaTrinhCongTacId))
			return false;
		QuaTrinhCongTacId castOther = (QuaTrinhCongTacId) other;

		return (this.getMaQtct() == castOther.getMaQtct()) && (this.getMaCb() == castOther.getMaCb());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getMaQtct();
		result = 37 * result + this.getMaCb();
		return result;
	}

}
