package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * QuaTrinhLuongId generated by hbm2java
 */
@Embeddable
public class QuaTrinhLuongId implements java.io.Serializable {

	private int maCb;
	private Date thoiGianNangLuong;

	public QuaTrinhLuongId() {
	}

	public QuaTrinhLuongId(int maCb, Date thoiGianNangLuong) {
		this.maCb = maCb;
		this.thoiGianNangLuong = thoiGianNangLuong;
	}

	@Column(name = "Ma_CB", nullable = false)
	public int getMaCb() {
		return this.maCb;
	}

	public void setMaCb(int maCb) {
		this.maCb = maCb;
	}

	@Column(name = "Thoi_Gian_Nang_Luong", nullable = false, length = 10)
	public Date getThoiGianNangLuong() {
		return this.thoiGianNangLuong;
	}

	public void setThoiGianNangLuong(Date thoiGianNangLuong) {
		this.thoiGianNangLuong = thoiGianNangLuong;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof QuaTrinhLuongId))
			return false;
		QuaTrinhLuongId castOther = (QuaTrinhLuongId) other;

		return (this.getMaCb() == castOther.getMaCb())
				&& ((this.getThoiGianNangLuong() == castOther.getThoiGianNangLuong())
						|| (this.getThoiGianNangLuong() != null && castOther.getThoiGianNangLuong() != null
								&& this.getThoiGianNangLuong().equals(castOther.getThoiGianNangLuong())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMaCb();
		result = 37 * result + (getThoiGianNangLuong() == null ? 0 : this.getThoiGianNangLuong().hashCode());
		return result;
	}

}
