package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QuaTrinhLuong generated by hbm2java
 */
@Entity
@Table(name = "qua_trinh_luong", catalog = "qlcb")
public class QuaTrinhLuong implements java.io.Serializable {

	private QuaTrinhLuongId id;
	private CanBo canBo;
	private NgachLuong ngachLuong;
	private String bacLuong;
	private Float heSoLuong;
	private Float phuCapVuotKhung;
	private Float heSoPhuCap;
	private Long mucLuongKhoang;

	public QuaTrinhLuong() {
	}

	public QuaTrinhLuong(QuaTrinhLuongId id, CanBo canBo) {
		this.id = id;
		this.canBo = canBo;
	}

	public QuaTrinhLuong(QuaTrinhLuongId id, CanBo canBo, NgachLuong ngachLuong, String bacLuong, Float heSoLuong,
			Float phuCapVuotKhung, Float heSoPhuCap, Long mucLuongKhoang) {
		this.id = id;
		this.canBo = canBo;
		this.ngachLuong = ngachLuong;
		this.bacLuong = bacLuong;
		this.heSoLuong = heSoLuong;
		this.phuCapVuotKhung = phuCapVuotKhung;
		this.heSoPhuCap = heSoPhuCap;
		this.mucLuongKhoang = mucLuongKhoang;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "maCb", column = @Column(name = "Ma_CB", nullable = false)),
			@AttributeOverride(name = "thoiGianNangLuong", column = @Column(name = "Thoi_Gian_Nang_Luong", nullable = false, length = 10)) })
	public QuaTrinhLuongId getId() {
		return this.id;
	}

	public void setId(QuaTrinhLuongId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ma_CB", nullable = false, insertable = false, updatable = false)
	public CanBo getCanBo() {
		return this.canBo;
	}

	public void setCanBo(CanBo canBo) {
		this.canBo = canBo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ma_So_Ngach")
	public NgachLuong getNgachLuong() {
		return this.ngachLuong;
	}

	public void setNgachLuong(NgachLuong ngachLuong) {
		this.ngachLuong = ngachLuong;
	}

	@Column(name = "Bac_Luong", length = 32)
	public String getBacLuong() {
		return this.bacLuong;
	}

	public void setBacLuong(String bacLuong) {
		this.bacLuong = bacLuong;
	}

	@Column(name = "He_So_Luong", precision = 12, scale = 0)
	public Float getHeSoLuong() {
		return this.heSoLuong;
	}

	public void setHeSoLuong(Float heSoLuong) {
		this.heSoLuong = heSoLuong;
	}

	@Column(name = "Phu_Cap_Vuot_Khung", precision = 12, scale = 0)
	public Float getPhuCapVuotKhung() {
		return this.phuCapVuotKhung;
	}

	public void setPhuCapVuotKhung(Float phuCapVuotKhung) {
		this.phuCapVuotKhung = phuCapVuotKhung;
	}

	@Column(name = "He_So_Phu_Cap", precision = 12, scale = 0)
	public Float getHeSoPhuCap() {
		return this.heSoPhuCap;
	}

	public void setHeSoPhuCap(Float heSoPhuCap) {
		this.heSoPhuCap = heSoPhuCap;
	}

	@Column(name = "Muc_Luong_Khoang")
	public Long getMucLuongKhoang() {
		return this.mucLuongKhoang;
	}

	public void setMucLuongKhoang(Long mucLuongKhoang) {
		this.mucLuongKhoang = mucLuongKhoang;
	}

}
