package com.springmvc.qlcb.model;
// Generated Apr 19, 2016 9:35:55 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Quy generated by hbm2java
 */
@Entity
@Table(name = "quy", catalog = "qlcb_new")
public class Quy implements java.io.Serializable {

	private int id;
	private String tenQuy;
	private Set<Danhgiacanbo> danhgiacanbos = new HashSet<Danhgiacanbo>(0);

	public Quy() {
	}

	public Quy(int id, String tenQuy) {
		this.id = id;
		this.tenQuy = tenQuy;
	}

	public Quy(int id, String tenQuy, Set<Danhgiacanbo> danhgiacanbos) {
		this.id = id;
		this.tenQuy = tenQuy;
		this.danhgiacanbos = danhgiacanbos;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "TenQuy", nullable = false, length = 100)
	public String getTenQuy() {
		return this.tenQuy;
	}

	public void setTenQuy(String tenQuy) {
		this.tenQuy = tenQuy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quy")
	public Set<Danhgiacanbo> getDanhgiacanbos() {
		return this.danhgiacanbos;
	}

	public void setDanhgiacanbos(Set<Danhgiacanbo> danhgiacanbos) {
		this.danhgiacanbos = danhgiacanbos;
	}

}
