package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RolePrivilegeRelationId generated by hbm2java
 */
@Embeddable
public class RolePrivilegeRelationId implements java.io.Serializable {

	private String roleName;
	private String privilegeName;

	public RolePrivilegeRelationId() {
	}

	public RolePrivilegeRelationId(String roleName, String privilegeName) {
		this.roleName = roleName;
		this.privilegeName = privilegeName;
	}

	@Column(name = "Role_Name", nullable = false, length = 32)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "Privilege_Name", nullable = false, length = 32)
	public String getPrivilegeName() {
		return this.privilegeName;
	}

	public void setPrivilegeName(String privilegeName) {
		this.privilegeName = privilegeName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RolePrivilegeRelationId))
			return false;
		RolePrivilegeRelationId castOther = (RolePrivilegeRelationId) other;

		return ((this.getRoleName() == castOther.getRoleName()) || (this.getRoleName() != null
				&& castOther.getRoleName() != null && this.getRoleName().equals(castOther.getRoleName())))
				&& ((this.getPrivilegeName() == castOther.getPrivilegeName())
						|| (this.getPrivilegeName() != null && castOther.getPrivilegeName() != null
								&& this.getPrivilegeName().equals(castOther.getPrivilegeName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRoleName() == null ? 0 : this.getRoleName().hashCode());
		result = 37 * result + (getPrivilegeName() == null ? 0 : this.getPrivilegeName().hashCode());
		return result;
	}

}
