package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RolePrivilegeRelation generated by hbm2java
 */
@Entity
@Table(name = "role_privilege_relation", catalog = "qlcb")
public class RolePrivilegeRelation implements java.io.Serializable {

	private RolePrivilegeRelationId id;
	private Privilege privilege;
	private Role role;
	private Boolean isAllowed;

	public RolePrivilegeRelation() {
	}

	public RolePrivilegeRelation(RolePrivilegeRelationId id, Privilege privilege, Role role) {
		this.id = id;
		this.privilege = privilege;
		this.role = role;
	}

	public RolePrivilegeRelation(RolePrivilegeRelationId id, Privilege privilege, Role role, Boolean isAllowed) {
		this.id = id;
		this.privilege = privilege;
		this.role = role;
		this.isAllowed = isAllowed;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "roleName", column = @Column(name = "Role_Name", nullable = false, length = 32)),
			@AttributeOverride(name = "privilegeName", column = @Column(name = "Privilege_Name", nullable = false, length = 32)) })
	public RolePrivilegeRelationId getId() {
		return this.id;
	}

	public void setId(RolePrivilegeRelationId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Privilege_Name", nullable = false, insertable = false, updatable = false)
	public Privilege getPrivilege() {
		return this.privilege;
	}

	public void setPrivilege(Privilege privilege) {
		this.privilege = privilege;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Role_Name", nullable = false, insertable = false, updatable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "isAllowed")
	public Boolean getIsAllowed() {
		return this.isAllowed;
	}

	public void setIsAllowed(Boolean isAllowed) {
		this.isAllowed = isAllowed;
	}

}
