package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "status", catalog = "qlcb")
public class Status implements java.io.Serializable {

	private byte statusCode;
	private String statusName;
	private Set<User> users = new HashSet<User>(0);

	public Status() {
	}

	public Status(byte statusCode) {
		this.statusCode = statusCode;
	}

	public Status(byte statusCode, String statusName, Set<User> users) {
		this.statusCode = statusCode;
		this.statusName = statusName;
		this.users = users;
	}

	@Id

	@Column(name = "Status_Code", unique = true, nullable = false)
	public byte getStatusCode() {
		return this.statusCode;
	}

	public void setStatusCode(byte statusCode) {
		this.statusCode = statusCode;
	}

	@Column(name = "Status_Name", length = 254)
	public String getStatusName() {
		return this.statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "status")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
