package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ThanhVienGiaDinh generated by hbm2java
 */
@Entity
@Table(name = "thanh_vien_gia_dinh", catalog = "qlcb")
public class ThanhVienGiaDinh implements java.io.Serializable {

	private ThanhVienGiaDinhId id;
	private CanBo canBo;
	private boolean benVo;
	private String quanHe;
	private String hoTen;
	private Date namSinh;
	private String thongTinSoLuoc;
	private String queQuan;
	private String ngheNghiep;
	private String chucDanh;
	private String chucVu;
	private String donViCongTac;
	private String hocTap;
	private String noiO;
	private String thanhVienCacToChuc;

	public ThanhVienGiaDinh() {
	}

	public ThanhVienGiaDinh(ThanhVienGiaDinhId id, CanBo canBo, boolean benVo, String quanHe) {
		this.id = id;
		this.canBo = canBo;
		this.benVo = benVo;
		this.quanHe = quanHe;
	}

	public ThanhVienGiaDinh(ThanhVienGiaDinhId id, CanBo canBo, boolean benVo, String quanHe, String hoTen,
			Date namSinh, String thongTinSoLuoc, String queQuan, String ngheNghiep, String chucDanh, String chucVu,
			String donViCongTac, String hocTap, String noiO, String thanhVienCacToChuc) {
		this.id = id;
		this.canBo = canBo;
		this.benVo = benVo;
		this.quanHe = quanHe;
		this.hoTen = hoTen;
		this.namSinh = namSinh;
		this.thongTinSoLuoc = thongTinSoLuoc;
		this.queQuan = queQuan;
		this.ngheNghiep = ngheNghiep;
		this.chucDanh = chucDanh;
		this.chucVu = chucVu;
		this.donViCongTac = donViCongTac;
		this.hocTap = hocTap;
		this.noiO = noiO;
		this.thanhVienCacToChuc = thanhVienCacToChuc;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "maQuanHe", column = @Column(name = "Ma_Quan_He", nullable = false)),
			@AttributeOverride(name = "maCb", column = @Column(name = "Ma_CB", nullable = false)) })
	public ThanhVienGiaDinhId getId() {
		return this.id;
	}

	public void setId(ThanhVienGiaDinhId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ma_CB", nullable = false, insertable = false, updatable = false)
	public CanBo getCanBo() {
		return this.canBo;
	}

	public void setCanBo(CanBo canBo) {
		this.canBo = canBo;
	}

	@Column(name = "Ben_Vo", nullable = false)
	public boolean isBenVo() {
		return this.benVo;
	}

	public void setBenVo(boolean benVo) {
		this.benVo = benVo;
	}

	@Column(name = "Quan_He", nullable = false, length = 62)
	public String getQuanHe() {
		return this.quanHe;
	}

	public void setQuanHe(String quanHe) {
		this.quanHe = quanHe;
	}

	@Column(name = "Ho_Ten", length = 62)
	public String getHoTen() {
		return this.hoTen;
	}

	public void setHoTen(String hoTen) {
		this.hoTen = hoTen;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Nam_Sinh", length = 10)
	public Date getNamSinh() {
		return this.namSinh;
	}

	public void setNamSinh(Date namSinh) {
		this.namSinh = namSinh;
	}

	@Column(name = "Thong_Tin_So_Luoc", length = 65535)
	public String getThongTinSoLuoc() {
		return this.thongTinSoLuoc;
	}

	public void setThongTinSoLuoc(String thongTinSoLuoc) {
		this.thongTinSoLuoc = thongTinSoLuoc;
	}

	@Column(name = "Que_Quan", length = 254)
	public String getQueQuan() {
		return this.queQuan;
	}

	public void setQueQuan(String queQuan) {
		this.queQuan = queQuan;
	}

	@Column(name = "Nghe_Nghiep", length = 254)
	public String getNgheNghiep() {
		return this.ngheNghiep;
	}

	public void setNgheNghiep(String ngheNghiep) {
		this.ngheNghiep = ngheNghiep;
	}

	@Column(name = "Chuc_Danh", length = 254)
	public String getChucDanh() {
		return this.chucDanh;
	}

	public void setChucDanh(String chucDanh) {
		this.chucDanh = chucDanh;
	}

	@Column(name = "Chuc_Vu", length = 254)
	public String getChucVu() {
		return this.chucVu;
	}

	public void setChucVu(String chucVu) {
		this.chucVu = chucVu;
	}

	@Column(name = "Don_Vi_Cong_Tac", length = 254)
	public String getDonViCongTac() {
		return this.donViCongTac;
	}

	public void setDonViCongTac(String donViCongTac) {
		this.donViCongTac = donViCongTac;
	}

	@Column(name = "Hoc_Tap", length = 254)
	public String getHocTap() {
		return this.hocTap;
	}

	public void setHocTap(String hocTap) {
		this.hocTap = hocTap;
	}

	@Column(name = "Noi_O", length = 254)
	public String getNoiO() {
		return this.noiO;
	}

	public void setNoiO(String noiO) {
		this.noiO = noiO;
	}

	@Column(name = "Thanh_Vien_Cac_To_Chuc", length = 254)
	public String getThanhVienCacToChuc() {
		return this.thanhVienCacToChuc;
	}

	public void setThanhVienCacToChuc(String thanhVienCacToChuc) {
		this.thanhVienCacToChuc = thanhVienCacToChuc;
	}

}
