package com.springmvc.qlcb.model;
// Generated Apr 25, 2016 1:43:12 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Thanhviengiadinh generated by hbm2java
 */
@Entity
@Table(name = "thanhviengiadinh", catalog = "qlcb")
public class Thanhviengiadinh implements java.io.Serializable {

	private int maThanhVienGiaDinh;
	private String tenThanhVienGiaDinh;
	private Boolean gioiTinh;
	private String chucVu;
	private String ghiChu;
	private Set<CanboGiadinhBanthan> canboGiadinhBanthans = new HashSet<CanboGiadinhBanthan>(0);
	private Set<CanboGiadinhDoitac> canboGiadinhDoitacs = new HashSet<CanboGiadinhDoitac>(0);

	public Thanhviengiadinh() {
	}

	public Thanhviengiadinh(int maThanhVienGiaDinh) {
		this.maThanhVienGiaDinh = maThanhVienGiaDinh;
	}

	public Thanhviengiadinh(int maThanhVienGiaDinh, String tenThanhVienGiaDinh, Boolean gioiTinh, String chucVu,
			String ghiChu, Set<CanboGiadinhBanthan> canboGiadinhBanthans, Set<CanboGiadinhDoitac> canboGiadinhDoitacs) {
		this.maThanhVienGiaDinh = maThanhVienGiaDinh;
		this.tenThanhVienGiaDinh = tenThanhVienGiaDinh;
		this.gioiTinh = gioiTinh;
		this.chucVu = chucVu;
		this.ghiChu = ghiChu;
		this.canboGiadinhBanthans = canboGiadinhBanthans;
		this.canboGiadinhDoitacs = canboGiadinhDoitacs;
	}

	@Id

	@Column(name = "MaThanhVienGiaDinh", unique = true, nullable = false)
	public int getMaThanhVienGiaDinh() {
		return this.maThanhVienGiaDinh;
	}

	public void setMaThanhVienGiaDinh(int maThanhVienGiaDinh) {
		this.maThanhVienGiaDinh = maThanhVienGiaDinh;
	}

	@Column(name = "TenThanhVienGiaDinh", length = 200)
	public String getTenThanhVienGiaDinh() {
		return this.tenThanhVienGiaDinh;
	}

	public void setTenThanhVienGiaDinh(String tenThanhVienGiaDinh) {
		this.tenThanhVienGiaDinh = tenThanhVienGiaDinh;
	}

	@Column(name = "GioiTinh")
	public Boolean getGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(Boolean gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	@Column(name = "ChucVu", length = 65535)
	public String getChucVu() {
		return this.chucVu;
	}

	public void setChucVu(String chucVu) {
		this.chucVu = chucVu;
	}

	@Column(name = "GhiChu", length = 65535)
	public String getGhiChu() {
		return this.ghiChu;
	}

	public void setGhiChu(String ghiChu) {
		this.ghiChu = ghiChu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "thanhviengiadinh")
	public Set<CanboGiadinhBanthan> getCanboGiadinhBanthans() {
		return this.canboGiadinhBanthans;
	}

	public void setCanboGiadinhBanthans(Set<CanboGiadinhBanthan> canboGiadinhBanthans) {
		this.canboGiadinhBanthans = canboGiadinhBanthans;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "thanhviengiadinh")
	public Set<CanboGiadinhDoitac> getCanboGiadinhDoitacs() {
		return this.canboGiadinhDoitacs;
	}

	public void setCanboGiadinhDoitacs(Set<CanboGiadinhDoitac> canboGiadinhDoitacs) {
		this.canboGiadinhDoitacs = canboGiadinhDoitacs;
	}

}
