package com.springmvc.qlcb.model;
// Generated Apr 19, 2016 9:35:55 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Thanhviengiadinh generated by hbm2java
 */
@Entity
@Table(name = "thanhviengiadinh", catalog = "qlcb_new")
public class Thanhviengiadinh implements java.io.Serializable {

	private int id;
	private Loaiquanhe loaiquanhe;
	private Quanhe quanhe;
	private String ten;
	private String noiDung;
	private Set<Canbo> canbos = new HashSet<Canbo>(0);

	public Thanhviengiadinh() {
	}

	public Thanhviengiadinh(int id, Loaiquanhe loaiquanhe, Quanhe quanhe, String ten, String noiDung) {
		this.id = id;
		this.loaiquanhe = loaiquanhe;
		this.quanhe = quanhe;
		this.ten = ten;
		this.noiDung = noiDung;
	}

	public Thanhviengiadinh(int id, Loaiquanhe loaiquanhe, Quanhe quanhe, String ten, String noiDung,
			Set<Canbo> canbos) {
		this.id = id;
		this.loaiquanhe = loaiquanhe;
		this.quanhe = quanhe;
		this.ten = ten;
		this.noiDung = noiDung;
		this.canbos = canbos;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaLoaiQuanHe", nullable = false)
	public Loaiquanhe getLoaiquanhe() {
		return this.loaiquanhe;
	}

	public void setLoaiquanhe(Loaiquanhe loaiquanhe) {
		this.loaiquanhe = loaiquanhe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaQuanHe", nullable = false)
	public Quanhe getQuanhe() {
		return this.quanhe;
	}

	public void setQuanhe(Quanhe quanhe) {
		this.quanhe = quanhe;
	}

	@Column(name = "Ten", nullable = false, length = 200)
	public String getTen() {
		return this.ten;
	}

	public void setTen(String ten) {
		this.ten = ten;
	}

	@Column(name = "NoiDung", nullable = false, length = 65535)
	public String getNoiDung() {
		return this.noiDung;
	}

	public void setNoiDung(String noiDung) {
		this.noiDung = noiDung;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "canbo_thanhviengiadinh", catalog = "qlcb_new", joinColumns = {
			@JoinColumn(name = "ThanhVienGiaDinh_ID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "CanBo_ID", nullable = false, updatable = false) })
	public Set<Canbo> getCanbos() {
		return this.canbos;
	}

	public void setCanbos(Set<Canbo> canbos) {
		this.canbos = canbos;
	}

}
