package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ThanhVienGiaDinhId generated by hbm2java
 */
@Embeddable
public class ThanhVienGiaDinhId implements java.io.Serializable {

	private long maQuanHe;
	private int maCb;

	public ThanhVienGiaDinhId() {
	}

	public ThanhVienGiaDinhId(long maQuanHe, int maCb) {
		this.maQuanHe = maQuanHe;
		this.maCb = maCb;
	}

	@Column(name = "Ma_Quan_He", nullable = false)
	public long getMaQuanHe() {
		return this.maQuanHe;
	}

	public void setMaQuanHe(long maQuanHe) {
		this.maQuanHe = maQuanHe;
	}

	@Column(name = "Ma_CB", nullable = false)
	public int getMaCb() {
		return this.maCb;
	}

	public void setMaCb(int maCb) {
		this.maCb = maCb;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ThanhVienGiaDinhId))
			return false;
		ThanhVienGiaDinhId castOther = (ThanhVienGiaDinhId) other;

		return (this.getMaQuanHe() == castOther.getMaQuanHe()) && (this.getMaCb() == castOther.getMaCb());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getMaQuanHe();
		result = 37 * result + this.getMaCb();
		return result;
	}

}
