package com.springmvc.qlcb.model;
// Generated Apr 21, 2016 1:56:09 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Thanhviengiadinh generated by hbm2java
 */
@Entity
@Table(name = "thanhviengiadinh", catalog = "qlcb")
public class Thanhviengiadinh implements java.io.Serializable {

	private int maThanhVienGiaDinh;
	private Loaiquanhe loaiquanhe;
	private Quanhe quanhe;
	private String tenThanhVienGiaDinh;
	private String noiDung;
	private Set<Canbo> canbos = new HashSet<Canbo>(0);

	public Thanhviengiadinh() {
	}

	public Thanhviengiadinh(int maThanhVienGiaDinh, Loaiquanhe loaiquanhe, Quanhe quanhe, String tenThanhVienGiaDinh,
			String noiDung) {
		this.maThanhVienGiaDinh = maThanhVienGiaDinh;
		this.loaiquanhe = loaiquanhe;
		this.quanhe = quanhe;
		this.tenThanhVienGiaDinh = tenThanhVienGiaDinh;
		this.noiDung = noiDung;
	}

	public Thanhviengiadinh(int maThanhVienGiaDinh, Loaiquanhe loaiquanhe, Quanhe quanhe, String tenThanhVienGiaDinh,
			String noiDung, Set<Canbo> canbos) {
		this.maThanhVienGiaDinh = maThanhVienGiaDinh;
		this.loaiquanhe = loaiquanhe;
		this.quanhe = quanhe;
		this.tenThanhVienGiaDinh = tenThanhVienGiaDinh;
		this.noiDung = noiDung;
		this.canbos = canbos;
	}

	@Id

	@Column(name = "MaThanhVienGiaDinh", unique = true, nullable = false)
	public int getMaThanhVienGiaDinh() {
		return this.maThanhVienGiaDinh;
	}

	public void setMaThanhVienGiaDinh(int maThanhVienGiaDinh) {
		this.maThanhVienGiaDinh = maThanhVienGiaDinh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaLoaiQuanHe", nullable = false)
	public Loaiquanhe getLoaiquanhe() {
		return this.loaiquanhe;
	}

	public void setLoaiquanhe(Loaiquanhe loaiquanhe) {
		this.loaiquanhe = loaiquanhe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaQuanHe", nullable = false)
	public Quanhe getQuanhe() {
		return this.quanhe;
	}

	public void setQuanhe(Quanhe quanhe) {
		this.quanhe = quanhe;
	}

	@Column(name = "TenThanhVienGiaDinh", nullable = false, length = 200)
	public String getTenThanhVienGiaDinh() {
		return this.tenThanhVienGiaDinh;
	}

	public void setTenThanhVienGiaDinh(String tenThanhVienGiaDinh) {
		this.tenThanhVienGiaDinh = tenThanhVienGiaDinh;
	}

	@Column(name = "NoiDung", nullable = false, length = 65535)
	public String getNoiDung() {
		return this.noiDung;
	}

	public void setNoiDung(String noiDung) {
		this.noiDung = noiDung;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "canbo_thanhviengiadinh", catalog = "qlcb", joinColumns = {
			@JoinColumn(name = "MaThanhVienGiaDinh", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "MaCanBo", nullable = false, updatable = false) })
	public Set<Canbo> getCanbos() {
		return this.canbos;
	}

	public void setCanbos(Set<Canbo> canbos) {
		this.canbos = canbos;
	}

}
