package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ThongTinThamGiaBanId generated by hbm2java
 */
@Embeddable
public class ThongTinThamGiaBanId implements java.io.Serializable {

	private int maCb;
	private int maBan;
	private Date ngayGiaNhap;

	public ThongTinThamGiaBanId() {
	}

	public ThongTinThamGiaBanId(int maCb, int maBan, Date ngayGiaNhap) {
		this.maCb = maCb;
		this.maBan = maBan;
		this.ngayGiaNhap = ngayGiaNhap;
	}

	@Column(name = "Ma_CB", nullable = false)
	public int getMaCb() {
		return this.maCb;
	}

	public void setMaCb(int maCb) {
		this.maCb = maCb;
	}

	@Column(name = "Ma_Ban", nullable = false)
	public int getMaBan() {
		return this.maBan;
	}

	public void setMaBan(int maBan) {
		this.maBan = maBan;
	}

	@Column(name = "Ngay_Gia_Nhap", nullable = false, length = 10)
	public Date getNgayGiaNhap() {
		return this.ngayGiaNhap;
	}

	public void setNgayGiaNhap(Date ngayGiaNhap) {
		this.ngayGiaNhap = ngayGiaNhap;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ThongTinThamGiaBanId))
			return false;
		ThongTinThamGiaBanId castOther = (ThongTinThamGiaBanId) other;

		return (this.getMaCb() == castOther.getMaCb()) && (this.getMaBan() == castOther.getMaBan())
				&& ((this.getNgayGiaNhap() == castOther.getNgayGiaNhap())
						|| (this.getNgayGiaNhap() != null && castOther.getNgayGiaNhap() != null
								&& this.getNgayGiaNhap().equals(castOther.getNgayGiaNhap())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMaCb();
		result = 37 * result + this.getMaBan();
		result = 37 * result + (getNgayGiaNhap() == null ? 0 : this.getNgayGiaNhap().hashCode());
		return result;
	}

}
