package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ToCongTac generated by hbm2java
 */
@Entity
@Table(name = "to_cong_tac", catalog = "qlcb")
public class ToCongTac implements java.io.Serializable {

	private ToCongTacId id;
	private Ban ban;
	private String tenTo;
	private Set<ThongTinThamGiaBan> thongTinThamGiaBans = new HashSet<ThongTinThamGiaBan>(0);

	public ToCongTac() {
	}

	public ToCongTac(ToCongTacId id, Ban ban) {
		this.id = id;
		this.ban = ban;
	}

	public ToCongTac(ToCongTacId id, Ban ban, String tenTo, Set<ThongTinThamGiaBan> thongTinThamGiaBans) {
		this.id = id;
		this.ban = ban;
		this.tenTo = tenTo;
		this.thongTinThamGiaBans = thongTinThamGiaBans;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "maBan", column = @Column(name = "Ma_Ban", nullable = false)),
			@AttributeOverride(name = "sttTo", column = @Column(name = "STT_To", nullable = false)) })
	public ToCongTacId getId() {
		return this.id;
	}

	public void setId(ToCongTacId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Ma_Ban", nullable = false, insertable = false, updatable = false)
	public Ban getBan() {
		return this.ban;
	}

	public void setBan(Ban ban) {
		this.ban = ban;
	}

	@Column(name = "Ten_To", length = 254)
	public String getTenTo() {
		return this.tenTo;
	}

	public void setTenTo(String tenTo) {
		this.tenTo = tenTo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "toCongTac")
	public Set<ThongTinThamGiaBan> getThongTinThamGiaBans() {
		return this.thongTinThamGiaBans;
	}

	public void setThongTinThamGiaBans(Set<ThongTinThamGiaBan> thongTinThamGiaBans) {
		this.thongTinThamGiaBans = thongTinThamGiaBans;
	}

}
