package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ToCongTacId generated by hbm2java
 */
@Embeddable
public class ToCongTacId implements java.io.Serializable {

	private int maBan;
	private byte sttTo;

	public ToCongTacId() {
	}

	public ToCongTacId(int maBan, byte sttTo) {
		this.maBan = maBan;
		this.sttTo = sttTo;
	}

	@Column(name = "Ma_Ban", nullable = false)
	public int getMaBan() {
		return this.maBan;
	}

	public void setMaBan(int maBan) {
		this.maBan = maBan;
	}

	@Column(name = "STT_To", nullable = false)
	public byte getSttTo() {
		return this.sttTo;
	}

	public void setSttTo(byte sttTo) {
		this.sttTo = sttTo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ToCongTacId))
			return false;
		ToCongTacId castOther = (ToCongTacId) other;

		return (this.getMaBan() == castOther.getMaBan()) && (this.getSttTo() == castOther.getSttTo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMaBan();
		result = 37 * result + this.getSttTo();
		return result;
	}

}
