package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TonGiao generated by hbm2java
 */
@Entity
@Table(name = "ton_giao", catalog = "qlcb")
public class TonGiao implements java.io.Serializable {

	private Short maTonGiao;
	private String tenTonGiao;
	private Set<LyLich> lyLiches = new HashSet<LyLich>(0);

	public TonGiao() {
	}

	public TonGiao(String tenTonGiao, Set<LyLich> lyLiches) {
		this.tenTonGiao = tenTonGiao;
		this.lyLiches = lyLiches;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Ma_Ton_Giao", unique = true, nullable = false)
	public Short getMaTonGiao() {
		return this.maTonGiao;
	}

	public void setMaTonGiao(Short maTonGiao) {
		this.maTonGiao = maTonGiao;
	}

	@Column(name = "Ten_Ton_Giao", length = 62)
	public String getTenTonGiao() {
		return this.tenTonGiao;
	}

	public void setTenTonGiao(String tenTonGiao) {
		this.tenTonGiao = tenTonGiao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tonGiao")
	public Set<LyLich> getLyLiches() {
		return this.lyLiches;
	}

	public void setLyLiches(Set<LyLich> lyLiches) {
		this.lyLiches = lyLiches;
	}

}
