package com.springmvc.qlcb.model;
// Generated Apr 19, 2016 9:35:55 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Trinhdochuyenmon generated by hbm2java
 */
@Entity
@Table(name = "trinhdochuyenmon", catalog = "qlcb_new")
public class Trinhdochuyenmon implements java.io.Serializable {

	private int id;
	private String tenTrinhDo;
	private Set<Lylich> lyliches = new HashSet<Lylich>(0);

	public Trinhdochuyenmon() {
	}

	public Trinhdochuyenmon(int id, String tenTrinhDo) {
		this.id = id;
		this.tenTrinhDo = tenTrinhDo;
	}

	public Trinhdochuyenmon(int id, String tenTrinhDo, Set<Lylich> lyliches) {
		this.id = id;
		this.tenTrinhDo = tenTrinhDo;
		this.lyliches = lyliches;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "TenTrinhDo", nullable = false, length = 200)
	public String getTenTrinhDo() {
		return this.tenTrinhDo;
	}

	public void setTenTrinhDo(String tenTrinhDo) {
		this.tenTrinhDo = tenTrinhDo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trinhdochuyenmon")
	public Set<Lylich> getLyliches() {
		return this.lyliches;
	}

	public void setLyliches(Set<Lylich> lyliches) {
		this.lyliches = lyliches;
	}

}
