package com.springmvc.qlcb.model;
// Generated Apr 25, 2016 2:33:53 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.Length;

/**
 * Trinhdochuyenmon generated by hbm2java
 */
@Entity
@Table(name = "trinhdochuyenmon", catalog = "qlcb")
public class Trinhdochuyenmon implements java.io.Serializable {

	private int maTrinhDoChuyenMon;
	@Length(min=1, max=50,message="không để trống")
	private String tenTrinhDoChuyenMon;
	private Set<Lylich> lyliches = new HashSet<Lylich>(0);

	public Trinhdochuyenmon() {
	}

	public Trinhdochuyenmon(int maTrinhDoChuyenMon, String tenTrinhDoChuyenMon) {
		this.maTrinhDoChuyenMon = maTrinhDoChuyenMon;
		this.tenTrinhDoChuyenMon = tenTrinhDoChuyenMon;
	}

	public Trinhdochuyenmon(int maTrinhDoChuyenMon, String tenTrinhDoChuyenMon, Set<Lylich> lyliches) {
		this.maTrinhDoChuyenMon = maTrinhDoChuyenMon;
		this.tenTrinhDoChuyenMon = tenTrinhDoChuyenMon;
		this.lyliches = lyliches;
	}

	@Id

	@Column(name = "MaTrinhDoChuyenMon", unique = true, nullable = false)
	public int getMaTrinhDoChuyenMon() {
		return this.maTrinhDoChuyenMon;
	}

	public void setMaTrinhDoChuyenMon(int maTrinhDoChuyenMon) {
		this.maTrinhDoChuyenMon = maTrinhDoChuyenMon;
	}

	@Column(name = "TenTrinhDoChuyenMon", nullable = false, length = 200)
	public String getTenTrinhDoChuyenMon() {
		return this.tenTrinhDoChuyenMon;
	}

	public void setTenTrinhDoChuyenMon(String tenTrinhDoChuyenMon) {
		this.tenTrinhDoChuyenMon = tenTrinhDoChuyenMon;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trinhdochuyenmon")
	public Set<Lylich> getLyliches() {
		return this.lyliches;
	}

	public void setLyliches(Set<Lylich> lyliches) {
		this.lyliches = lyliches;
	}

}
