package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TrinhDoLyLuanChinhTri generated by hbm2java
 */
@Entity
@Table(name = "trinh_do_ly_luan_chinh_tri", catalog = "qlcb")
public class TrinhDoLyLuanChinhTri implements java.io.Serializable {

	private BigDecimal capDoLlct;
	private String tenCtll;
	private String vietTatCtll;
	private Set<LyLich> lyLiches = new HashSet<LyLich>(0);

	public TrinhDoLyLuanChinhTri() {
	}

	public TrinhDoLyLuanChinhTri(BigDecimal capDoLlct, String vietTatCtll) {
		this.capDoLlct = capDoLlct;
		this.vietTatCtll = vietTatCtll;
	}

	public TrinhDoLyLuanChinhTri(BigDecimal capDoLlct, String tenCtll, String vietTatCtll, Set<LyLich> lyLiches) {
		this.capDoLlct = capDoLlct;
		this.tenCtll = tenCtll;
		this.vietTatCtll = vietTatCtll;
		this.lyLiches = lyLiches;
	}

	@Id

	@Column(name = "Cap_Do_LLCT", unique = true, nullable = false, precision = 4)
	public BigDecimal getCapDoLlct() {
		return this.capDoLlct;
	}

	public void setCapDoLlct(BigDecimal capDoLlct) {
		this.capDoLlct = capDoLlct;
	}

	@Column(name = "Ten_CTLL", length = 254)
	public String getTenCtll() {
		return this.tenCtll;
	}

	public void setTenCtll(String tenCtll) {
		this.tenCtll = tenCtll;
	}

	@Column(name = "Viet_Tat_CTLL", nullable = false, length = 32)
	public String getVietTatCtll() {
		return this.vietTatCtll;
	}

	public void setVietTatCtll(String vietTatCtll) {
		this.vietTatCtll = vietTatCtll;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trinhDoLyLuanChinhTri")
	public Set<LyLich> getLyLiches() {
		return this.lyLiches;
	}

	public void setLyLiches(Set<LyLich> lyLiches) {
		this.lyLiches = lyLiches;
	}

}
