package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TrinhDoChuyenMon generated by hbm2java
 */
@Entity
@Table(name = "trinh_do_chuyen_mon", catalog = "qlcb")
public class TrinhDoChuyenMon implements java.io.Serializable {

	private BigDecimal capDoTdcm;
	private String tenTdcm;
	private String vietTatTdcm;
	private Set<LyLich> lyLiches = new HashSet<LyLich>(0);

	public TrinhDoChuyenMon() {
	}

	public TrinhDoChuyenMon(BigDecimal capDoTdcm, String vietTatTdcm) {
		this.capDoTdcm = capDoTdcm;
		this.vietTatTdcm = vietTatTdcm;
	}

	public TrinhDoChuyenMon(BigDecimal capDoTdcm, String tenTdcm, String vietTatTdcm, Set<LyLich> lyLiches) {
		this.capDoTdcm = capDoTdcm;
		this.tenTdcm = tenTdcm;
		this.vietTatTdcm = vietTatTdcm;
		this.lyLiches = lyLiches;
	}

	@Id

	@Column(name = "Cap_Do_TDCM", unique = true, nullable = false, precision = 4)
	public BigDecimal getCapDoTdcm() {
		return this.capDoTdcm;
	}

	public void setCapDoTdcm(BigDecimal capDoTdcm) {
		this.capDoTdcm = capDoTdcm;
	}

	@Column(name = "Ten_TDCM", length = 254)
	public String getTenTdcm() {
		return this.tenTdcm;
	}

	public void setTenTdcm(String tenTdcm) {
		this.tenTdcm = tenTdcm;
	}

	@Column(name = "Viet_Tat_TDCM", nullable = false, length = 8)
	public String getVietTatTdcm() {
		return this.vietTatTdcm;
	}

	public void setVietTatTdcm(String vietTatTdcm) {
		this.vietTatTdcm = vietTatTdcm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trinhDoChuyenMon")
	public Set<LyLich> getLyLiches() {
		return this.lyLiches;
	}

	public void setLyLiches(Set<LyLich> lyLiches) {
		this.lyLiches = lyLiches;
	}

}
