package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TtTaiDonVi generated by hbm2java
 */
@Entity
@Table(name = "tt_tai_don_vi", catalog = "qlcb")
public class TtTaiDonVi implements java.io.Serializable {

	private TtTaiDonViId id;

	public TtTaiDonVi() {
	}

	public TtTaiDonVi(TtTaiDonViId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "ngayDen", column = @Column(name = "NgayDen", length = 19)),
			@AttributeOverride(name = "lidoChuyenDen", column = @Column(name = "LidoChuyenDen", length = 254)),
			@AttributeOverride(name = "hoSoXacNhan", column = @Column(name = "HoSoXacNhan", length = 254)) })
	public TtTaiDonViId getId() {
		return this.id;
	}

	public void setId(TtTaiDonViId id) {
		this.id = id;
	}

}
