package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TtTaiDonViId generated by hbm2java
 */
@Embeddable
public class TtTaiDonViId implements java.io.Serializable {

	private Date ngayDen;
	private String lidoChuyenDen;
	private String hoSoXacNhan;

	public TtTaiDonViId() {
	}

	public TtTaiDonViId(Date ngayDen, String lidoChuyenDen, String hoSoXacNhan) {
		this.ngayDen = ngayDen;
		this.lidoChuyenDen = lidoChuyenDen;
		this.hoSoXacNhan = hoSoXacNhan;
	}

	@Column(name = "NgayDen", length = 19)
	public Date getNgayDen() {
		return this.ngayDen;
	}

	public void setNgayDen(Date ngayDen) {
		this.ngayDen = ngayDen;
	}

	@Column(name = "LidoChuyenDen", length = 254)
	public String getLidoChuyenDen() {
		return this.lidoChuyenDen;
	}

	public void setLidoChuyenDen(String lidoChuyenDen) {
		this.lidoChuyenDen = lidoChuyenDen;
	}

	@Column(name = "HoSoXacNhan", length = 254)
	public String getHoSoXacNhan() {
		return this.hoSoXacNhan;
	}

	public void setHoSoXacNhan(String hoSoXacNhan) {
		this.hoSoXacNhan = hoSoXacNhan;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TtTaiDonViId))
			return false;
		TtTaiDonViId castOther = (TtTaiDonViId) other;

		return ((this.getNgayDen() == castOther.getNgayDen()) || (this.getNgayDen() != null
				&& castOther.getNgayDen() != null && this.getNgayDen().equals(castOther.getNgayDen())))
				&& ((this.getLidoChuyenDen() == castOther.getLidoChuyenDen())
						|| (this.getLidoChuyenDen() != null && castOther.getLidoChuyenDen() != null
								&& this.getLidoChuyenDen().equals(castOther.getLidoChuyenDen())))
				&& ((this.getHoSoXacNhan() == castOther.getHoSoXacNhan())
						|| (this.getHoSoXacNhan() != null && castOther.getHoSoXacNhan() != null
								&& this.getHoSoXacNhan().equals(castOther.getHoSoXacNhan())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNgayDen() == null ? 0 : this.getNgayDen().hashCode());
		result = 37 * result + (getLidoChuyenDen() == null ? 0 : this.getLidoChuyenDen().hashCode());
		result = 37 * result + (getHoSoXacNhan() == null ? 0 : this.getHoSoXacNhan().hashCode());
		return result;
	}

}
