package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UserLog generated by hbm2java
 */
@Entity
@Table(name = "user_log", catalog = "qlcb")
public class UserLog implements java.io.Serializable {

	private UserLogId id;
	private Integer maCbThucHien;
	private String chucNang;
	private String noiDung;

	public UserLog() {
	}

	public UserLog(UserLogId id) {
		this.id = id;
	}

	public UserLog(UserLogId id, Integer maCbThucHien, String chucNang, String noiDung) {
		this.id = id;
		this.maCbThucHien = maCbThucHien;
		this.chucNang = chucNang;
		this.noiDung = noiDung;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "thoiGian", column = @Column(name = "Thoi_Gian", nullable = false, length = 19)),
			@AttributeOverride(name = "maUserThucHien", column = @Column(name = "Ma_User_Thuc_Hien", nullable = false)) })
	public UserLogId getId() {
		return this.id;
	}

	public void setId(UserLogId id) {
		this.id = id;
	}

	@Column(name = "Ma_CB_Thuc_Hien")
	public Integer getMaCbThucHien() {
		return this.maCbThucHien;
	}

	public void setMaCbThucHien(Integer maCbThucHien) {
		this.maCbThucHien = maCbThucHien;
	}

	@Column(name = "Chuc_Nang", length = 254)
	public String getChucNang() {
		return this.chucNang;
	}

	public void setChucNang(String chucNang) {
		this.chucNang = chucNang;
	}

	@Column(name = "Noi_Dung", length = 65535)
	public String getNoiDung() {
		return this.noiDung;
	}

	public void setNoiDung(String noiDung) {
		this.noiDung = noiDung;
	}

}
