package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserLogId generated by hbm2java
 */
@Embeddable
public class UserLogId implements java.io.Serializable {

	private Date thoiGian;
	private int maUserThucHien;

	public UserLogId() {
	}

	public UserLogId(Date thoiGian, int maUserThucHien) {
		this.thoiGian = thoiGian;
		this.maUserThucHien = maUserThucHien;
	}

	@Column(name = "Thoi_Gian", nullable = false, length = 19)
	public Date getThoiGian() {
		return this.thoiGian;
	}

	public void setThoiGian(Date thoiGian) {
		this.thoiGian = thoiGian;
	}

	@Column(name = "Ma_User_Thuc_Hien", nullable = false)
	public int getMaUserThucHien() {
		return this.maUserThucHien;
	}

	public void setMaUserThucHien(int maUserThucHien) {
		this.maUserThucHien = maUserThucHien;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserLogId))
			return false;
		UserLogId castOther = (UserLogId) other;

		return ((this.getThoiGian() == castOther.getThoiGian()) || (this.getThoiGian() != null
				&& castOther.getThoiGian() != null && this.getThoiGian().equals(castOther.getThoiGian())))
				&& (this.getMaUserThucHien() == castOther.getMaUserThucHien());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getThoiGian() == null ? 0 : this.getThoiGian().hashCode());
		result = 37 * result + this.getMaUserThucHien();
		return result;
	}

}
