package com.springmvc.qlcb.model;
// Generated Apr 25, 2016 2:33:53 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CanboDonviId generated by hbm2java
 */
@Embeddable
public class usersandrolesId implements java.io.Serializable {

	private int user_id;
	private int role_id;

	public usersandrolesId() {
	}

	public usersandrolesId(int user_id, int role_id) {
		this.user_id = user_id;
		this.role_id = role_id;
	}

	@Column(name = "user_id", nullable = false)
	public int getuser_id() {
		return this.user_id;
	}

	public void setuser_id(int user_id) {
		this.user_id = user_id;
	}

	@Column(name = "role_id", nullable = false)
	public int getrole_id() {
		return this.role_id;
	}

	public void setrole_id(int role_id) {
		this.role_id = role_id;
	}

	 

}
