package com.springmvc.qlcb.model;
// Generated Apr 11, 2016 10:54:37 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "qlcb", uniqueConstraints = @UniqueConstraint(columnNames = "Username"))
public class User implements java.io.Serializable {

	private Integer userId;
	private Role role;
	private Status status;
	private String username;
	private String password;
	private Integer identifierInfo;
	private String passwordKey;
	private Profile profile;

	public User() {
	}

	public User(String username, String passwordKey) {
		this.username = username;
		this.passwordKey = passwordKey;
	}

	public User(Role role, Status status, String username, String password, Integer identifierInfo, String passwordKey,
			Profile profile) {
		this.role = role;
		this.status = status;
		this.username = username;
		this.password = password;
		this.identifierInfo = identifierInfo;
		this.passwordKey = passwordKey;
		this.profile = profile;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "UserID", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Role_Name")
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Status_Code")
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@Column(name = "Username", unique = true, nullable = false, length = 254)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "Password", length = 254)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "Identifier_Info")
	public Integer getIdentifierInfo() {
		return this.identifierInfo;
	}

	public void setIdentifierInfo(Integer identifierInfo) {
		this.identifierInfo = identifierInfo;
	}

	@Column(name = "Password_Key", nullable = false, length = 254)
	public String getPasswordKey() {
		return this.passwordKey;
	}

	public void setPasswordKey(String passwordKey) {
		this.passwordKey = passwordKey;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "user")
	public Profile getProfile() {
		return this.profile;
	}

	public void setProfile(Profile profile) {
		this.profile = profile;
	}

}
